### ISSUE TITLE
Table Storage API (CosmosDB) Query Entities not working with OData filter parameter

### ISSUE THREAD

**Issue by dchw** [Azure/azure-sdk-for-go#1020]
I am trying to query Cosmos DB (Table Storage api) via the storage api package. Every time I provide a filter parameter; I get the following response:

Here is how I am setting up the client:
````
func InitDB() error {
	// DbBaseUrl is set to 'cosmosdb.azure.com:443'
	// DbApiVersion is set to '2015-06-01-preview'
	client, err := storage.NewClient(config.DbAccountName, config.DbAccountKey, config.DbBaseURL, config.DbApiVersion, true)
	if err != nil {
		return err
	}

	tableClient = client.GetTableService()
	return nil
}
````

Here is my query code. *I know the entities exist, and that I can at least get something, because when I make a query without a filter parameter, I can see the entity I want.* If I even reuse the values from that entity and make this request, it still fails:
````
func Lookup(partitionKey, rowKey string) (*Info, error) {
	table := tableClient.GetTableReference(config.DbTableName)

	queryOptions := &storage.QueryOptions{
		Filter: fmt.Sprintf("PartitionKey eq %s and RowKey eq %s", partitionKey, rowKey),
	}

	results, err := table.QueryEntities(config.DbQueryTimeout, storage.FullMetadata, queryOptions)

	// Walk over results.Entities. and choose one

	return &Info{/*Fill in details from chosen entity*/}, nil
}
````
````
storage: service returned error: StatusCode=400, ErrorCode=BadRequest, ErrorMessage=Request url is invalid.
ActivityId: c416e037-d05e-4035-a6ad-4cd50cfd3679, documentdb-dotnet-sdk/1.19.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
RequestID:c416e037-d05e-4035-a6ad-4cd50cfd3679
, RequestInitiated=Tue, 30 Jan 2018 21:20:17 GMT, RequestId=c416e037-d05e-4035-a6ad-4cd50cfd3679, API Version=, QueryParameterName=, QueryParameterValue=
````

Interestingly, I get a 404 instead of a 400 error message when I try to select the entity directly:
````
func Lookup(partitionKey, rowKey string) (*Info, error) {
	table := tableClient.GetTableReference(config.DbTableName)
	entity := table.GetEntityReference(partitionKey, rowKey)

	err := entity.Get(config.DbQueryTimeout, storage.FullMetadata, &storage.GetEntityOptions{/*Select the parts I want*/})
	if err != nil {
		return nil, err
	}

	return &Info{/*Fill in details from retrieved entity*/}, nil
}
````
````
storage: service returned error: StatusCode=404, ErrorCode=ResourceNotFound, ErrorMessage=The specified resource does not exist.
RequestID:3e7a84c8-3a98-441d-a5e2-f309315d6485
, RequestInitiated=Tue, 30 Jan 2018 21:21:22 GMT, RequestId=3e7a84c8-3a98-441d-a5e2-f309315d6485, API Version=, QueryParameterName=, QueryParameterValue=
````

Am I doing something wrong? Can I use the table storage APIs here with Cosmos?

**Comment by joshgav** [comment]
Hi @dchw, so sorry for the delayed response! We'll need to investigate this with the Cosmos team. Are you still having this issue?

**Comment by dchw** [comment]
@joshgav No, not anymore. We moved to a C# and non-Cosmos backed solution, this was part of the reason

**Comment by yhere** [comment]
@joshgav  @vladbarosan  @marstr
We are having the same problem
We can't do basic call's:
1) table.QueryEntities(...
2) entity.Get(...

Can you help?
Tx.

**Comment by mamoorkhan** [comment]
is there any update on this one?

**Comment by shurd** [comment]
We are looking into this issue. I will update as I find out more.

**Comment by shurd** [comment]
It looks like the problem on "get" might be that there is a space (%20) between PartitionKey and RowKey in the URI: 

account.table.cosmosdb.azure.com/table%28PartitionKey=%27tree%27,%20RowKey=%27car%27%29?%24select=other&timeout=1000

Make sure you are using an updated APIVersion (2018-03-28). The API version you originally provided would give 400 if the URL was encoded. 

The Cosmos DB team does not own this package, and it is in maintenance only, so we will not be making changes that might break another service that the package works for. If you need to use this package for your Cosmos DB project, you can make the change to remove the space inbetween the PartitionKey and the RowKey. In [buildPath of entity.go](https://github.com/Azure/azure-sdk-for-go/blob/master/storage/entity.go#L237), remove the space:

```go
    return fmt.Sprintf("%s(PartitionKey='%s',RowKey='%s')", e.Table.buildPath(), e.PartitionKey, e.RowKey)
```

I confirmed that this does not break the default table API (core.windows.net).

The 400 request on query is likely due to an OData version mismatch. For the queries to work, you should include the header "MaxDataServiceVersion: 3.0;NetFx". If you want to make the change for your Cosmos DB project, you can add this pair as a standard header in ["getStandardHeaders" in client.go](https://github.com/Azure/azure-sdk-for-go/blob/7971189ecf5a584b9211f2527737f94bb979644e/storage/client.go#L696). 

```go
func (c Client) getStandardHeaders() map[string]string {
    return map[string]string{
        userAgentHeader: c.userAgent,
        "x-ms-version":  c.apiVersion,
        "x-ms-date":     currentTimeRfc1123Formatted(),
        "MaxDataServiceVersion": "3.0;NetFx",
    }
}
```

As this package will soon be deprecated, we suggest looking into using one of our other SDKs for developing your Cosmos DB Tables project. You can find more details here: https://docs.microsoft.com/en-us/azure/cosmos-db/
