### ISSUE TITLE
'json: cannot unmarshal number into Go struct field UsageSample.quantity of type map[string]interface {}'

### ISSUE THREAD

**Issue by dak52** [Azure/azure-sdk-for-go#1050]
https://github.com/Azure/azure-sdk-for-go/blob/f111fc2fa3861c5fdced76cae4c9c71821969577/arm/commerce/models.go#L342

**Comment by dak52** [comment]
I believe this should be a float...

**Comment by jhendrixMSFT** [comment]
The [Quantity field](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/commerce/resource-manager/Microsoft.Commerce/preview/2015-06-01-preview/commerce.json#L182) is missing a type specifier which means it's a wildcard type.  The Go generator didn't handle this properly in the past, it has been fixed in v14.0.0 (the field is now an interface).  I will follow up with the spec owner to ensure this behavior is intentional.

**Comment by amarzavery** [comment]
Can you provide a snapshot of the response body? I would like to see how the quantity property looks like.

**Comment by amarzavery** [comment]
not required, i found an example from this doc https://msdn.microsoft.com/en-us/library/azure/mt219001.aspx

**Comment by jhendrixMSFT** [comment]
Spec has been updated in https://github.com/Azure/azure-rest-api-specs/pull/2489.

**Comment by jhendrixMSFT** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v15.0.0
