### ISSUE TITLE
Add TokenRefresh Offset functionality

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-go#10567]
Specs: https://gist.github.com/jianghaolu/c56bd46dfa96dfff9bd7e5df8aca58e7

**Comment by chlowell** [comment]
Instead of adding public API as described in the gist, we (identity v-team) decided to implement the behavior internally with a fixed default configuration. Specifically, we wanted a credential / bearer token auth policy (which one depends on SDK implementation) to behave like this when asked for a token / authorizing a request:
- if no access token on hand: acquire a new one; use that
- if access token on hand
    - and it won't expire soon (within 5 minutes): use the cached token
    - and it will expire soon
        - if recently attempted to acquire a new token (within the last 30s): use the cached token (which is still valid)
        - otherwise: attempt to acquire a new token
            - if this fails, swallow any error and return the cached token

This behavior is [mostly implemented by `bearerTokenPolicy`](https://github.com/Azure/azure-sdk-for-go/blob/dcadd9be9421b0f2d671af1459b88a71a6ebdd06/sdk/azidentity/bearer_token_policy.go#L151) already, albeit with a refresh window of 2 minutes instead of 5 and no observance of the minimum 30s wait between token requests. I'll close this issue when those two small tweaks are in place. I wouldn't block a release on them; they're implementation details.
