### ISSUE TITLE
Get rid of the noisy PR's 

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1057]
there are around 40 PR's dangling on our repo that are automatically generated. What is the status of these.

@marstr either merge those or close them please.

**Comment by jhendrixMSFT** [comment]
I do see the value in having these PRs as it's convenient for the reviewer to understand how a specs change will affect the SDK.  However we need to ensure that for now these PRs do not get merged as it would interfere with our current plan of automated SDK updates.  If we want to continue to create these PRs then the tool that creates them should close them and delete the branch once the specs PR has been merged/closed.

**Comment by marstr** [comment]
I'll close out the existing ones, so that they don't interfere with the v14 release.

However, the idea from me, @salameer, and @lmazuel and was that we would use these PRs as the mechanism to commit changes to `master` ("fast-lane") or now the new "slow-lane" concept for Swagger-inspired breaking changes. These PRs would let us sort them, update our [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md), and pick an appropriate version number.

**Comment by jhendrixMSFT** [comment]
@marstr I think you mean committing them to the latest branch which is the fast lane, yes?

**Comment by marstr** [comment]
@jhendrixMSFT Errr, sorry I might be misusing the "fast-lane" and "slow-lane" terminology. Even though I'm a native-speaker, I'm bad at English idioms. I think we're on the same page here, but let me confirm by breaking it down a little more:

My position is that non-breaking changes like new API Versions, new services, and tweaks to Swaggers, are all merged to `master` with an official release tag as quickly as possible. There would be another branch that accumulates all swagger changes, breaking or otherwise. We can name that branch `latest`, `edge`, `nightly` or whatever.

On some cadence, we merge those two branches and cut a major release. Hopefully, we learn that breaking Swagger changes are more rare than we thought, and major changes don't have to happen very often. Maybe we see that they happen all the time. :/ Major bumps due to Swagger changes will not warrant an opportunity to introduce generator or `go-autorest` breaking changes.

We will have a separate cycle, which is far less frequent, where we release breaking changes introduced by changes to the generator.

**Comment by vladbarosan** [comment]
@marstr i think on that we agree, my understanding of what @jhendrixMSFT is referring is what we discussed on Tuesday that for non-breaking changes to not merge automatically to `master` to begin with. first to test it for a while in some other branch.
