### ISSUE TITLE
Properly generate latest profile

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#1066]
Fix remaining from https://github.com/Azure/azure-sdk-for-go/pull/1054 

Currently the latest profile is not generated respecting the stable/preview folder stucture of the rest specs api.

**Comment by marstr** [comment]
To elaborate, in order to fix this, I'm writing two command-line utilities:

1. A tool that inspects the specs repository, to find all "preview" and "stable" README and their tags.
1. A tool that determines the Go package names from a list of Azure REST API Spec READMEs and tags. 

This modular approach will still sit behind `go generate` so no extra complexity should be exposed to the end users. However, this is also necessary functionality for the Swagger -> SDK tooling. I've chatted with @lmazuel this morning to make sure that tool 1 fits the Swagger -> SDK needs.

**Comment by vladbarosan** [comment]
@marstr I think both of does are being done in the generator, you can pull them from there.

**Comment by marstr** [comment]
I'll make sure to checkout the generator, to make sure I'm not duplicating any code.

**Comment by marstr** [comment]
Part 1 of this is done (albeit with some polish missing.) For now, the code can be found here: https://github.com/marstr/az-rest-spec-finder

**Comment by marstr** [comment]
Putting this back in the triage bucket

**Comment by jhendrixMSFT** [comment]
Fixed in `latest`, will ship in v24.
