### ISSUE TITLE
auth.NewAuthorizerFromCLI() missing an audience parameter

### ISSUE THREAD

**Issue by snobu** [Azure/azure-sdk-for-go#10814]
I'm trying to get an access token for Azure Key Vault:

```
keyvaultAuthorizer, err := auth.NewAuthorizerFromCLI()
```

```
C:\app> go run .\app.go
E0625 00:09:06.431056    7296 app.go:85] Failed to fetch secret: Failed to get secret secret1: 
keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=401 --
Original Error: autorest/azure: Service returned an error. Status=401 Code="Unauthorized"
Message="AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.azure.com/."
```

Looks like ` auth.NewAuthorizerFromCLI()` takes no arguments and we're calling `az account get-access-token` without specifying audience, thus defaulting to `https://management.azure.com`.

```
keyvaultAuthorizer, err := auth.NewAuthorizerFromCLI("https://vault.azure.net")
```
```
.\app.go:27:54: too many arguments in call to auth.NewAuthorizerFromCLI
        have (string)
        want ()
```

Is this the expected behavior? `az account get-access-token` has a `--resource` argument we could use here.

**Comment by ArcturusZhang** [comment]
Hi @snobu thanks for this issue!

Actually `go-autorest` should have provided this functionality, but well, it is not documented. Go through the code, first we find [this resource parameter](https://github.com/Azure/go-autorest/blob/9210cb7ab0b17b380b7eb28d6a48c96f858d8f0a/autorest/azure/auth/auth.go#L272), and it is read from [here](https://github.com/Azure/go-autorest/blob/9210cb7ab0b17b380b7eb28d6a48c96f858d8f0a/autorest/azure/auth/auth.go#L94) and it turns out that the SDK is reading an environment variable [`AZURE_AD_RESOURCE`](https://github.com/Azure/go-autorest/blob/9210cb7ab0b17b380b7eb28d6a48c96f858d8f0a/autorest/azure/auth/auth.go#L51). Therefore you will have to first export an environment variable `AZURE_AD_RESOURCE="https://vault.azure.net"` and then call `auth.NewAuthorizerFromCLI` to achieve the same effect as `az account get-access-token --resource "https://vault.azure.net"`

Hi @jhendrixMSFT could you please also have look? I am not quite sure my answer is correct

**Comment by jhendrixMSFT** [comment]
You can also call [NewAuthorizerFromCLIWithResource()](https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L280), or there is a keyvault-specific authorizer you can use [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/keyvault/auth/auth.go) which basically does the same thing.

**Comment by snobu** [comment]
`NewAuthorizerFromCLIWithResource()` is beautiful, thanks!
Should i add it to the README via PR, somewhere around where `auth.NewAuthorizerFromCLI()` gets mentioned?
I would go one step further and only mention `..FromCLIWithResource()` instead of `..FromCLI()`, as the former only adds confusion right now.

**Comment by jhendrixMSFT** [comment]
Glad it worked for you.  Feel free to open a PR and link it to this issue.

**Comment by snobu** [comment]
I confirm exporting `AZURE_AD_RESOURCE="https://vault.azure.net` as env var works with `auth.NewAuthorizerFromCLI()`.
Will add this to the readme as well, seems useful.

**Comment by snobu** [comment]
This is ready to merge from my perspective:
https://github.com/Azure/azure-sdk-for-go/pull/11023

**Comment by jhendrixMSFT** [comment]
Thanks for the PR.  Closing as I believe this is now resolved.
