### ISSUE TITLE
Failed to delete resource NetApp Volume when the delete API of NetApp Snapshot returns 404

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-sdk-for-go#11475]
### Bug Report

- Import path of package in question: https://github.com/Azure/azure-sdk-for-go/tree/master/services/netapp/mgmt/2019-10-01/netapp
- SDK version: v43.2.0
- Output of `go version`: go version go1.12.7 windows/amd64

- What happened?
The resource NetApp Snapshot depends on the resource NetApp Volume. Although the delete API returns 404 which means the NetApp Snapshot resource has been deleted. Then it tries to immediately delete NetApp Volume but it still throws error `Can not delete resource before nested resources are deleted.`, which means the resource NetApp Snapshot still hasn't been deleted. So it failed to delete top resource NetApp Volume.

- What did you expect or want to happen?
It should delete both resources NetApp Snapshot and NetApp Volume successfully.

- How can we reproduce it?
1. Create a resource group
2. Create NetApp Account
3. Create NetApp Pool
4. Create NetApp Volume
5. Create NetApp Snapshot
6. Delete NetApp Snapshot, which returns "202"
7. Immediately call "Get" rest api to get resource NetApp Snapshot, which returns "404"
8. Immediately delete NetApp Volume, which returns error code "409"
9. Then it throws error `Can not delete resource before nested resources are deleted.`

- Anything we should know about your environment.
The error message:
"Error: Error deleting NetApp Volume "acctest-NetAppVolume" (Resource Group "acctestRG-netapp"): netapp.VolumesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."" when the delete API of NetApp Snapshot returns 404.

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei thanks for this issue!
Step 6 when you delete the netapp snapshot, it returns 202, which sounds this should be async to me. If a delete request succeeds and returns, typically it should return 200 instead of 202.

And I just checked the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/115dee0d25929469490cd314f24349ebeff4ea89/specification/netapp/resource-manager/Microsoft.NetApp/stable/2019-10-01/netapp.json#L1422), the delete operation is indeed a long running operation. Would you please try in step 6 to wait for the async operation to complete and then see if it could work well.

Thanks!
