### ISSUE TITLE
Provide a way to get a secret by identifier in KeyVault

### ISSUE THREAD

**Issue by connor4312** [Azure/azure-sdk-for-go#11916]
### Feature Request

Currently the (only) method to get a secret is defined as

```
func (client BaseClient) GetSecret(ctx context.Context, vaultBaseURL string, secretName string, secretVersion string) (result SecretBundle, err error)
```

There's no way to get a secret by its identifier (URI).

- The URI is the easy copy-able value given in the portal, so taking that is convenient
- In calling `GetSecretVersion`, the returned secret also includes its identifier only. If I want to then get th secret value after getting its version, I need to manually parse out the version from the ID, which is awkward and more error-prone

**Comment by ArcturusZhang** [comment]
Hi @connor4312 thanks for this issue!
Unfortunately the keyvault team does not provide such an API for this. And by the nature of the SDK, which is auto-generated from the swagger provided by the service team, we could do very little regarding on this.

But please check out [this implementation](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/key_vault_child.go) in terraform, I believe this is what you want. Heads up, this piece of code is based on some assumption of the structure of the secret URI.

**Comment by sebansal** [comment]
@RandalliLama for key vault team would be looking into it

**Comment by jlichwa** [comment]
@ArcturusZhang can you elaborate what is the ask? Currently there is API to get secret by identifier (URI) with version or get latest version by passing null for version.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang can you elaborate what is the ask? Currently there is API to get secret by identifier (URI) with version or get latest version by passing null for version.

We are requesting a API `GetSecretByURI` with the parameter of a full URI, rather than the parsed pieces from the URI. 
Now the Get API URL is exactly the full URI of the secret, but to use this API, we will have to parse it first, get every segment of the full URI (base URI of the keyvault, secret name and secret version), and before actually sending the request, the SDK will assemble those segments to a full URI again. We wish we could have a method that could directly get the secret using the URI without parsing it locally

**Comment by ArcturusZhang** [comment]
By saying the above, it makes me feel that maybe this could be done on the SDK side. @jhendrixMSFT what do you think? Do we have similar functionality in track 2?

**Comment by jhendrixMSFT** [comment]
We haven't started work on a track 2 implementation of key vault.  If there are plans to add this functionality it would be owned by the service team, likely as part of the convenience layer implementation.

**Comment by jlichwa** [comment]
@jhendrixMSFT  service team provides REST API where full URI is used:
Example:
URI: https://jl-kv.vault.azure.net/secrets/Secret1/1551892c2fc44880aef50509d5e4bc91
API matches URI structure: GET https://jl-kv.vault.azure.net/secrets/Secret1/1551892c2fc44880aef50509d5e4bc91

https://docs.microsoft.com/en-us/rest/api/keyvault/getsecret/getsecret#getsecret

I'm a little confused what changes are you looking for in REST API? Today you can use full URI to get secret. 
Are you looking for changes in SDK instead?

**Comment by ArcturusZhang** [comment]
Hi @jlichwa our SDK is generated from the rest api specs, now we did not define an API in the specs that consumes a full URI of a secret, instead we only have [this](https://github.com/Azure/azure-rest-api-specs/blob/c196ef04fa243b9b1dc92fcef87d85521273154f/specification/keyvault/data-plane/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L962) with a parameterized host, which requires the user to input every segment.
If there is a way to define an API that consumes a full URI, it would be the best (but I am not sure if this could be done in the specs).

@jhendrixMSFT I am thinking that maybe we could introduce a convenience layer of functions like `ListComplete` which requires a full rest api URI as its parameters rather than building the URI from pieces. Do you think this is reasonable?

**Comment by jlichwa** [comment]
Thank you @ArcturusZhang. REST API already define that method (full URI as a method) and it is up to SDK to provide user friendly interface for their consumers. @jhendrixMSFT is @ArcturusZhang suggestion reasonable.

**Comment by jhendrixMSFT** [comment]
We will be doing this for the track 2 key vault implementation, but have no plans to introduce such a convenience layer in track 1.

**Comment by jhendrixMSFT** [comment]
@seankane-msft is this supported in `azkeys`?

**Comment by seankane-msft** [comment]
@connor4312 this has been added to the latest `azsecrets` release. The [`Secret`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets#Secret) type returned by most methods involving secrets will have the Name and ID for each secret. The Name property is parsed from the ID. If you want to get the Version, the [`Properties`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets#Properties) type will have the Version parsed from the ID.
