### ISSUE TITLE
Need LinkedServerDeleteFuture for redis model

### ISSUE THREAD

**Issue by pearcec** [Azure/azure-sdk-for-go#12159]
### Bug Report

Working on a terraform providered for linked servers for geo replication.  The test tears down the linked server and then quickly moved to tearing down the two redis caches.  The provisioningState on the linked server is "Deleting".  It would be handle to have a LinkedServerDeleteFuture. 

https://github.com/Azure/azure-sdk-for-go/blob/f83744196dcfdff5667240eb855a76764ce3eb46/services/redis/mgmt/2018-03-01/redis/linkedserver.go#L139

**Comment by ArcturusZhang** [comment]
Hi @pearcec thanks for this issue!

Since our go SDK is generated from the REST API specs, this is controlled here: https://github.com/Azure/azure-rest-api-specs/blob/50a94ccd66f49aed78efa24ceefd0d5c1186c8db/specification/redis/resource-manager/Microsoft.Cache/stable/2018-03-01/redis.json#L1207
If you want this operation to be async, the service team has to update their swagger by adding a `x-ms-long-running-operation: true` and also alter their service behaviour to return a polling URL in the request header - I am quite sure this operation behaves like a sync operation because in the REST API specs it says only `200` is an acceptable status code, usually an async delete operation should return `201` or `202` as status code, in this case, these two status codes would throw errors.

Therefore I suppose this should be something that the service team should have a look. For workaround, you could make a specific logic (or a generalized framework for this) to query the LinkService by using a GET until you get `404`.

**Comment by pearcec** [comment]
Hi @ArcturusZhang thanks for the quick reply.  I will open an issue and cross link it to this one.  Thanks.

Workaround in place. https://github.com/terraform-providers/terraform-provider-azurerm/pull/8026 addressing this feature request https://github.com/terraform-providers/terraform-provider-azurerm/issues/3294.

**Comment by ArcturusZhang** [comment]
@pearcec thanks for the effort! Since this issue has been tracked [here](https://github.com/Azure/azure-rest-api-specs/issues/10364), I will close this issue in favor of the one in azure-rest-api-specs
