### ISSUE TITLE
Azure Subnet Get Error: Failure preparing request: StatusCode=0 -- Original Error: autorest: No scheme detected in URL

### ISSUE THREAD

**Issue by rahulroshan96** [Azure/azure-sdk-for-go#12226]
### Bug Report

- What happened?
Get subnet api is throwing error while preparing the request.
- What did you expect or want to happen?
Execute the request.
- How can we reproduce it?
Using mentioned code.
- Anything we should know about your environment.
go version go1.14 darwin/amd64

package main
import (
	"fmt"
	"context"
	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
    azureServicePrinciple:= auth.NewClientCredentialsConfig("APPID", "TOKEN", "TENANT")
    subnet_client := network.NewSubnetsClient(raz.subscriptionID)
	a, err := azureServicePrinciple.Authorizer()
	if err!=nil{
		fmt.Println(err)
	}
	subnet_client.Authorizer = a
	ctx:=context.Background()
	subnet_info,err := client.subnet_client.Get(ctx, "RG",
		"VNET",
		"SUBNET", "")
	if err!=nil{
		fmt.Println(err)
	}else{
		fmt.Println(subnet_info)
	}
}

Error is `Failure preparing request: StatusCode=0 -- Original Error: autorest: No scheme detected in URL`

**Comment by ArcturusZhang** [comment]
Hi @rahulroshan96 thanks for this issue!

The error is complaining the host URL in the request is missing the `scheme`, for instance `http` or `https`. 

In your program, you are assigning the authorizer to the variable `subnet_client`, which should be fine, but when you invoke the get function, you use `client.subnet_client`. Are you sure this is the same client as the client you are assigning the authorizer?
If you decide to create the client struct by using native initialization rather than calling the funtion `NewSubnetsClient` you will have to give it a `BaseURI`, otherwise the BaseURI would be empty and then the error in your description will show up.
