### ISSUE TITLE
Cannot sign Azure Marketplace VM image licence

### ISSUE THREAD

**Issue by r0kas** [Azure/azure-sdk-for-go#12325]
### Bug Report

- package `.../services/marketplaceordering/mgmt/2015-06-01/marketplaceordering`
- SDK version - 'latest'
- go 1.14.4

- Was using SDK provided method `MarketplaceAgreementsClient.Sign` to sign Marketplace VM offer to use it programatically.
- Was expecting to get a response that Agreement Terms were signed successfully. Instead got following error:
```marketplaceordering.MarketplaceAgreementsClient#Sign: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code='BadRequest' Message='You must accept the legal terms through the Azure portal (http://go.microsoft.com/fwlink/?LinkId=534873). Correlation Id: '305cfcff-c231-4fa7-9e5f-c77cde28fd11'.```
- You can reproduce it by trying to sign agreement terms of marketplace vm offering. I was trying to do that for CAST.AI Ubuntu Kubernetes image.
**Publisher** 'castaigroupinc1595243474856'
**Offer** 'ubuntu-kubernetes'
**SKU** '1-18-6'

Azure support staff forwarded me here to raise an issue with SDK devs.

**Comment by ArcturusZhang** [comment]
Hi @r0kas thanks for this issue!

Based on the error message, it seems that the service behaviour requires you to accept the legal terms using the URL it gives you on portal, which may not be done by programmable approach.

Also I tagged this issue so that the corresponding service team could have a look and probably give you a valid solution or explanation.

**Comment by wilsonehusin** [comment]
https://github.com/Azure/azure-sdk-for-go/issues/14768 might be relevant 😄
