### ISSUE TITLE
Provide 2019-10-01 version of consumption APIs

### ISSUE THREAD

**Issue by narph** [Azure/azure-sdk-for-go#12452]
### Feature Request

Atm, we see the `/consumption/mgm`t api calls are mapped up to `2019-01-01` https://github.com/Azure/azure-sdk-for-go/tree/master/services/consumption/mgmt.
With `2019-10-01` new improvements were added as supporting more subscription types.
Any idea when we can see this version in the sdk?

**Comment by ArcturusZhang** [comment]
Hi @narph thanks for this issue!

We will release this API version in the next minor version after [this PR](https://github.com/Azure/azure-rest-api-specs/pull/10749) is merged. Thanks

**Comment by vijayrajah** [comment]
@ArcturusZhang .. I see the PR was merged.. Any idea when this will be released?

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang .. I see the PR was merged.. Any idea when this will be released?

Yeah, the PR has been merged. But we have to ask the corresponding service team to see if they want to release the SDK for a new api-version. Usually they will release this, but we have to confirm whether there is anything wrong in the current swagger before we could release this. Please stay tuned and sorry for the delay.

**Comment by vijayrajah** [comment]
@ArcturusZhang . Thanks for the update.. Appreciate it

**Comment by mrsheepuk** [comment]
Any updated on when this is likely to be released? At the current version, as far as I can work out, it's impossible to filter by usage date for anything other than EA accounts...

**Comment by mrsheepuk** [comment]
@ArcturusZhang FYI, I tested the consumption API on this PR https://github.com/Azure/azure-sdk-for-go/pull/13208 and got errors unmarshalling JSON due to being unable to parse the values in the JSON for IsAzureCreditEligible on ModernUsageDetailProperties - the JSON has a value of `"1"` for this and the model defines it as a `*bool` - changing it in the model to `*string` let me get past the error and carry on. I don't believe the go JSON marshaller accepts the string value "1" as a bool when parsing JSON.

I also note that the `startDate` and `endDate` parameters are not available on `UsageDetailsClient.List()` - adding these in by hand, they do work, but I note those are missing from the swagger specs so I'm guessing that problem lies elsewhere.

If there are better places/ways to raise these issues, please let me know and I'll raise them appropriately.

**Comment by ArcturusZhang** [comment]
Hi @mrsheepuk instead of changing the SDK, I suppose this is more of a problem that the service should not return a boolean value in string - it is a better solution if the service team could change their payload.
Could you please open an issue in the [azure-rest-api-specs repo](https://github.com/Azure/azure-rest-api-specs/issues) about this?

**Comment by mrsheepuk** [comment]
Thanks @ArcturusZhang - raised https://github.com/Azure/azure-rest-api-specs/issues/11849 for this.

**Comment by ArcturusZhang** [comment]
> Thanks @ArcturusZhang - raised [Azure/azure-rest-api-specs#11849](https://github.com/Azure/azure-rest-api-specs/issues/11849) for this.

Thanks! And I have labeled the issue to draw service team's attention.

**Comment by adhiraj-g** [comment]
Hi There,

Any update on when the 2019-10-01 version of consumption APIs would likely be available for Azure module billing metricset?

**Comment by lirenhe** [comment]
From https://github.com/Azure/azure-rest-api-specs/issues/11849, I believe the issue was fixed from service side. Close this item and please let me know if you have other asks.
