### ISSUE TITLE
Missing ascLocation in JIT network access policies functions

### ISSUE THREAD

**Issue by beandrad** [Azure/azure-sdk-for-go#12633]
### Bug Report

- import path: `.../services/preview/security/mgmt/v3.0/security`
- go file: `.../services/preview/security/mgmt/v3.0/security/jitnetworkaccesspolicies.go`
- SDK version: 46.4.0
- Commit: https://github.com/Azure/azure-sdk-for-go/commit/e3b3fa36a8a194ac2914270c8f8ecc342d4a1ee5.

- What happened?
All the Jit Network Access Policies REST endpoints expect `ascLocation` as a path parameter (see https://docs.microsoft.com/en-us/rest/api/securitycenter/jitnetworkaccesspolicies). The problem with the Go SDK is that `ascLocation` cannot be passed when calling the corresponding CRUD functions. Instead, the `ascLocation` is taken from the client properties. https://github.com/Azure/azure-sdk-for-go/blob/8b1ae49e53332c534e4263b4d4160aeb81d9d497/services/preview/security/mgmt/v3.0/security/jitnetworkaccesspolicies.go#L99

- What did you expect or want to happen?
The CRUD functions defined in `.../services/preview/security/mgmt/v3.0/security/jitnetworkaccesspolicies.go` should take `ascLocation` as an argument (same as `resourceGroupName ` or `jitNetworkAccessPolicyName `).

- Anything we should know about your environment.
Looking at the Azure API specs version 2020-01-01, it seems that in the `ascLocation` schema, `x-ms-parameter-location` is defined as `client`, which may be causing this issue when generating the Go SDK client.

**Comment by ArcturusZhang** [comment]
Hi @beandrad thanks for this issue! And you are right, [this](https://github.com/Azure/azure-rest-api-specs/blob/fb029cb8f596fbfd1a9c60802a7cf189cc2e0c00/specification/security/resource-manager/common/v1/types.json#L337) is the root cause of this issue and probably this is by the service team's design.

Therefore I have tagged this issue so that the service team could have a look at this, and they may come by and explain why this is designed as a client parameter.
