### ISSUE TITLE
Support MSI Authentication through IDMS

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#1341]
@yugangw-msft , might be a good person to chat with to get some context here.

@mcardosos  can you please get some context on what's required on top of what you've already done for MSI?

**Comment by vladbarosan** [comment]
tagging @jhendrixMSFT as he worked on the MSI support

**Comment by vladbarosan** [comment]
Is this to use IDMS to get the msi Path which is currently hardcoded ? ( https://github.com/Azure/go-autorest/blob/master/autorest/adal/msi_windows.go )

**Comment by yugangw-msft** [comment]
If it clarifies, the token endpoint should switch from `http://locahost:<port>` to `http://169.254.169.254/metadata/identity/oauth2/token`, and you need to take care of the throttling situation, as the current limitation is 10 requests per second from each VM

**Comment by mcardosos** [comment]
@yugangw-msft  So is IDMS used to authenticate, but with this slight differences (endpoint, throttling)?
Is IDMS replacing MSI?

**Comment by vladbarosan** [comment]
@mcardosos  I think to clarify ( correct me if I am wrong @yugangw-msft  ):

1. Right now to access the MSI service , there is an MSI extension provisioned in the VMs which is accessed through a localhost endpoint.

2. The plan is probably to remove the extension and just use an MSI endpoint in IDMS ( which is accessible from all VMs on 169.254.169.254 ).

Hence MSI is still used, just we need to update to use the IDMS endpoint instead of the localhost endpoint.

**Comment by yugangw-msft** [comment]
@vladbarosan, that is right. The additional thing is to add a re-try under throttling

**Comment by mcardosos** [comment]
Okok, so what should be done in the SDK is exactly what @yugangw-msft commented:
- Change endpoint
- Throttling

**Comment by vladbarosan** [comment]
@mcardosos yup
 also maybe handling possible errors returned in case we don't do it already

**Comment by mcardosos** [comment]
Fixed on https://github.com/Azure/go-autorest/pull/263
Retries available on [go-autorest v11 branch](https://github.com/Azure/go-autorest/tree/v11)
