### ISSUE TITLE
applicationgroups not found in Microsoft.DesktopVirtualization for 2020-11-02-preview

### ISSUE THREAD

**Issue by yaegashi** [Azure/azure-sdk-for-go#13855]
### Bug Report

- import path of package: `github.com/Azure/azure-sdk-for-go/profiles/preview/preview/desktopvirtualization/mgmt/desktopvirtualization`
- SDK version: v49.0.0
- output of `go version`: go version go1.15.5 linux/amd64 (on Windows 10 WSL2)

After upgraded to v49.0.0, the API request by `desktopvirtualization.ApplicationGroupsClient` is getting the following error:

```
(2020-12-04T00:33:51.1526652+09:00) INFO: REQUEST: GET https://management.azure.com/subscriptions/a364d88a-716d-4892-a4b6-604312199663/providers/Microsoft.DesktopVirtualization/applicationGroups?api-version=2020-11-02-preview
User-Agent: Go/go1.15.5 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v49.0.0 desktopvirtualization/2020-11-02-preview
Authorization: **REDACTED**
(2020-12-04T00:33:51.3589269+09:00) INFO: RESPONSE: 404 https://management.azure.com/subscriptions/a364d88a-716d-4892-a4b6-604312199663/providers/Microsoft.DesktopVirtualization/applicationGroups?api-version=2020-11-02-preview
X-Ms-Correlation-Request-Id: afbde3e2-c3ba-4b5d-8ea1-7370505ddec6
...
{"error":{"code":"InvalidResourceType","message":"The resource type 'applicationgroups' could not be found in the namespace 'Microsoft.DesktopVirtualization' for api version '2020-11-02-preview'. The supported api-versions are '2019-01-23-preview,2019-09-24-preview,2019-12-10-preview,2020-09-21-preview,2020-10-19-preview'."}}
```

I've had no errors with v47.0.0.  The current workaround is explicitly importing `github.com/Azure/azure-sdk-for-go/services/preview/desktopvirtualization/mgmt/2020-10-19-preview/desktopvirtualization`.

Reproducilbe code: https://play.golang.org/p/T7qEOUgSE3P

**Comment by ArcturusZhang** [comment]
Hi @yaegashi thanks for this issue!

The preview profile will automatically select the package that is latest in the `api-version` segment of the package path - therefore when a SDK version bump happens, the same profile might point to a different package, like in this version `v49.0.0`. In `v47.0.0`, the preview profile for `desktopvirtualization` points to `2019-12-10-preview`, and now it points to `2020-11-02-preview`. To avoid this kind of implicit api-version switch, we recommend to directly use the package from the `services` directory rather than this profile.
As for this error itself, from the error messages, the service is not ready on api-version `2020-11-02-preview` yet. I will let the service team know about this.

**Comment by ArcturusZhang** [comment]
Hi @Goxu92 do you have any insights on this error?

**Comment by lirenhe** [comment]
@yaegashi，as this is the service behaviour, please try the workaround @ArcturusZhang  provided.
BTW, you could also use this latest package https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v60.2.0+incompatible/services/preview/desktopvirtualization/mgmt/2021-09-03-preview/desktopvirtualization to have a try.
Close this issue as this is not related to SDK
