### ISSUE TITLE
Feature Request: Support Pipelines

### ISSUE THREAD

**Issue by EugenMayer** [Azure/azure-sdk-for-go#13997]
### Feature Request

It would be great to be able to run (start) specific pipelines of a project or and check the status of a run and such using and identifier.

I spotted https://github.com/Azure/azure-pipeline-go and i'am not sure if this can be incorporated or how those plans (why the projects have been splitted in the first place)

**Comment by ArcturusZhang** [comment]
Hi @EugenMayer thanks for this issue.

This repo is designed to store those SDKs that are auto-generated from [`azure-rest-api-specs`](https://github.com/Azure/azure-rest-api-specs). We cannot support the SDK of pipelines because we now do not have the corresponding rest api specs. This is also the reason why they have to use a different repo.

Based on the above reason, unfortunately I will close this issue.

**Comment by EugenMayer** [comment]
Thank you for the clarification
