### ISSUE TITLE
ServerVulnerabilityAssessmentClient Delete returns error object even if successful

### ISSUE THREAD

**Issue by martenbohlin** [Azure/azure-sdk-for-go#14120]
### Bug Report

- import path of package in question, e.g. `github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/v3.0/security`
- SDK version `31.1.0`
  - Specify the exact commit if possible: `397140cd20ce375b8da0534436fb918389917264`
- output of `go version` `go version go1.15.6 darwin/amd64`

- What happened?
When invoking Delete for a server vulnerability assessment the API an error object is returned since the backend API responds with 202.

- What did you expect or want to happen?
Error object should be nil if the resource is successfully deleted.

- How can we reproduce it?
  - Create virtual machine
  - Create server vulnerability assessment on that virtual machine
  - Wait for the server vulnerability assessment to be fully created (~1min)
  - Invoke the delete operation and inspect the error object that is returned

- Anything we should know about your environment.
 - Discovered while adding support for server vulnerability assessment to terraform [Pull Request on terraform](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10030)

**Comment by ArcturusZhang** [comment]
Hi @martenbohlin thanks for this issue!

This is a swagger bug - this API appears to be an async operation (otherwise it would not return 202 as response code), but it is not marked as `long-running-operation` in [the swagger](https://github.com/Azure/azure-rest-api-specs/blob/ffc5119f58e1e302748bd21aff7bc01acd2b6d13/specification/security/resource-manager/Microsoft.Security/stable/2020-01-01/serverVulnerabilityAssessments.json#L244) which results in an SDK with issues. 
I have tagged this issue so that the corresponding service team will have a look and provide a fix for the swagger, then we can regenerate our SDK to fix this issue.

**Comment by ArcturusZhang** [comment]
And also this issue has already been reported here: https://github.com/Azure/azure-rest-api-specs/issues/12308
Therefore close this issue in favor of the issue above.
