### ISSUE TITLE
Latest APIs of services/cosmos-db/mgmt no longer available

### ISSUE THREAD

**Issue by manojampalam** [Azure/azure-sdk-for-go#14207]
### Bug Report

A handful of latest API versions of services/cosmos-db/mgmt have been deleted in release v47.0.0
https://github.com/Azure/azure-sdk-for-go/pull/12710/files?file-filters%5B%5D=.go#

Prior to this release, 3 newer versions were available:
https://github.com/Azure/azure-sdk-for-go/tree/v46.4.0/services/cosmos-db/mgmt

v47.0.0 and after - latest 3 have gone missing:
https://github.com/Azure/azure-sdk-for-go/tree/v47.0.0/services/cosmos-db/mgmt

**Comment by ArcturusZhang** [comment]
Hi @manojampalam those are missing because those packages are actually preview ones and have been moved to the `preview` subdirectory. We mentioned this in the [CHANGELOG](https://github.com/Azure/azure-sdk-for-go/blob/v47.0.0/CHANGELOG.md#package-renames).

As explained above, I would close this issue. Please let me know if there are more concerns
