### ISSUE TITLE
making DeviceSecurityGroup sdk more precise and elegant

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-sdk-for-go#14282]
RP: securitycenter
resource: DeviceSecurityGroup 
swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/Microsoft.Security/stable/2019-08-01/deviceSecurityGroups.json#L76
sdk: https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/security/mgmt/v3.0/security/devicesecuritygroups.go#L51

problem: 
the model of deviceSecurityGroup contains such property: 
```
AllowlistRules *[]BasicAllowlistCustomAlertRule `json:"allowlistRules,omitempty"
```

`BasicAllowlistCustomAlertRule` is an interface, and there are many different struct which implement the interface. However, all the struct have exactly the same properties. 

For now, we have to write a lot of repeated and messy codes when initalizing each struct and reading the properties.
We hope the common properties could be placed in a "parent" struct.

**Comment by ArcturusZhang** [comment]
@njuCZ thank you for opening this issue!

We know that the current implementation for the polymorphic types are not elegant enough, and the same topic has been discussed in https://github.com/Azure/azure-sdk-for-go/issues/8367.
Unfortunately we cannot change this right now, because changing this will be a massive breaking change which affects all downstream consumers. Our track 2 azure-sdk-for-go has a better solution of this, but we really cannot backport that to track 1 right now.

Since this issue is also on a duplicated topic of https://github.com/Azure/azure-sdk-for-go/issues/8367, I will close this in favor of https://github.com/Azure/azure-sdk-for-go/issues/8367. Thank you!
