### ISSUE TITLE
Remove support for the `$expand` querystring

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#14329]
### Bug Report

Whilst some API's allow specifying the `$expand` query string to conditionally return extra fields in the response, due to the nature of the Azure SDK's (across all languages) there's no way of accessing these dynamic fields. Whilst one option would be to add a `map[string]interface{}` to each struct of "Additional Fields" (which has been done I think in Track2) - there's no compatibility guarantees across API versions - so this is likely to be a source of crashes in end-user programs.

Instead, I'm wondering if support for the `$expand` querystring should be removed from (all) the Azure SDK's - since whilst this makes sense in the API (and hand-rolled clients), the design of the SDK's (using native structs) makes these a challenge to use. Arguably this is a design issue within the API's themselves and a Swagger issue where these aren't fully documented - but the `$expand` option ends up being a common source of breaking changes to method signatures for essentially zero value (since these fields can't be guaranteed/relied on) - so I'm wondering if this should be removed from the SDK?

**Comment by ArcturusZhang** [comment]
Hi @tombuildsstuff thanks for opening this issue!

Since this involves massive breaking changes acrossing all packages, we might need to discuss more of this to avoid this kind of breaking changes.
Adding @jhendrixMSFT for discussion

**Comment by jhendrixMSFT** [comment]
Hmm I wasn't aware of this param and its behavior.

I took a cursory look through the specs repo, this appears to be authored like any other param.  Unfortunately the authoring is of varying quality.  For example, in [`consumption`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-01-01/consumption.json#L1406) the `additionalProperties` appears to be incorrectly modeled (presumably it should be a dictionary type).  In [`authorization`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-ProviderOperationsCalls.json#L56), the `$expand` param is modeled but not the `additionalProperties` in the response (I don't know if the author forgot or they expected the code generator to implicitly add it).

I don't think we can get into the business of omitting params modeled in a swagger file during codegen, they would have to be removed from the swagger (_maybe_ we could do it for ARM only, but it's a slippery slope I'd prefer to avoid).  Of course, introducing a breaking change for an optional param (fixed in track 2) that doesn't even work is pretty terrible.  I'll follow up with how we can get this fixed on the swagger side.

Track 2 codegen doesn't perform any special handling for `$expand`, so it's just as broken.

**Comment by JeffreyRichter** [comment]
The swagger should define a model that describes (and documents) all possible fields. $expand should just indicate which of these fields should be initialized by the service. A client should not be broken by changes here. If the swagger is bad, then it should be fixed but I do not think the SDK should change its ways.

**Comment by jhendrixMSFT** [comment]
Closing as we have moved optional params to the "optional params struct" to avoid method sig breaking changes (we can't omit this).
