### ISSUE TITLE
Add support for multi-tenant authentication

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#14360]
This is a hard requirement for TF support.

**Comment by magodo** [comment]
Adding more context:

Currently, AzureRM provider makes use of [auxiliary tenant](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/authenticate-multi-tenant) to allow users to provision resource crossing tenants (e.g. cross tenant vnet peering).

The reason why the AzureRM provider works is because it depends on Go SDK Track2, where it can construct a multi-tenant authorizer for service principal either via [`adal.NewMultiTenantServicePrincipalToken`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/b4bdb931286cf5625be889cd60a10b8d7e99a3f3/vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_client_secret_multi_tenant.go#L45-L45), or via [getting the token from azcli (and convert it into SP token)](https://github.com/terraform-providers/terraform-provider-azurerm/blob/b4bdb931286cf5625be889cd60a10b8d7e99a3f3/vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_azure_cli_token_multi_tenant.go#L79-L79).
