### ISSUE TITLE
Resouce name is missed in go sdk

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-go#14408]
resource name is missed in go sdk: https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/v4.0/sql/manageddatabasesensitivitylabels.go#L57
delete method has the same issue.

**Comment by ArcturusZhang** [comment]
@dw511214992 it is not missing - it is hard coded in the generated code because there is only one available value: https://github.com/Azure/azure-sdk-for-go/blob/5464e01dc592545520045c0a59751a893150d6c9/services/preview/sql/mgmt/v4.0/sql/manageddatabasesensitivitylabels.go#L98

swagger reference: https://github.com/Azure/azure-rest-api-specs/blob/8c6d9ca42b208961742596028f914b285a12021c/specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/managedDatabaseSensitivityLabels.json#L140
