### ISSUE TITLE
Support ADFS authentication

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-go#14405]

**Comment by catalinaperalta** [comment]
Also investigate how to document ADFS usage with azidentity.

**Comment by chlowell** [comment]
AzureCliCredential simply execs the CLI, which then gets a token from whatever tenant it's logged in to. That means there's nothing special about this case for the credential: it just works with ADFS when the CLI is configured appropriately, and there's no special azidentity behavior or API to test.

However, we do need to document that other credentials require a magic "adfs" tenant, so rather than close this issue I'll repurpose it to track that.

**Comment by chlowell** [comment]
Related: #17386 (MSAL requires a tenant validation solution to support ADFS)

**Comment by chlowell** [comment]
Closed by #19872, which we included in azidentity v1.3.0-beta.3
