### ISSUE TITLE
ContainerServices: nil returned for nextLink returning 500+ containers per page

### ISSUE THREAD

**Issue by SaiKalyan28** [Azure/azure-sdk-for-go#14426]
I used the List and ListByResourcegroup function for ContainerGroups to list all the containers available. There are 500+ containers under that resource group and all the 500 containers are returned on the first page and the 'nextLink' is nil.

import path of the package used 
"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-12-01/containerservice"

similar behavior observed with
"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2018-03-31/containerservice"

What is the number of records per page? can it be changed as per the requirement?

**Comment by ArcturusZhang** [comment]
Hi @SaiKalyan28 thanks for this issue!

We first need to make sure that you are reporting issues of the List of `ContainerGroups` - but container groups come from the RP containerinstance instead of containerservices.
Could you confirm this?

And for this issue, we have two different circumstances:
1. This is a bug on the service side - they mark their List operation as pagable but do not return paging values
2. This is by-design - it does not mean to be pagable when a return value of a List operation has `nextLink`, non-pagable List operation in some circumstance could have a nextLink (but usually this is a mistake but it does no harm).

To confirm which circumstance this issue falls into, we first need to confirm which RP, which resource, which operation exactly has this issue. Thanks!

**Comment by SaiKalyan28** [comment]
Hi @ArcturusZhang, thanks for the response

I am little new to this terminology, can you please elaborate more.

To be more clear on what I did,
Created a VM client
`vmClient := compute.NewVirtualMachinesClient(subscriptionID)`

Using this client invoked apis 
`vmClient.List(ctx,resourcegroupname)`  or
`vmClient.ListAll(ctx,statusOnly)`

which by description lists all of the virtual machines but also specified to use `nextLink` property in the response to get the next page of virtual machines. So API is supposed to provide paginated response.

and also there is `ListAllComplete` API which by description enumerates all values, automatically crossing page boundaries. `nextLink` in this case is not expected as the API should provide all results as response at once.
Please correct me if my understanding is wrong.

Based on the description the issue falls under the first circumstance that you mentioned (This is a bug on the service side - they mark their List operation as pagable but do not return paging values).

Other resource types VirtualMachines, Disks also have similar API's and similar descriptions, I didnt verified the behaviour in those API's.

Thanks!

**Comment by ArcturusZhang** [comment]
@SaiKalyan28 Your understanding is correct. There is one thing that you can tell whether this list operation supports pagable or not - we will always have a corresponding `ListXXXComplete` function along with the `ListXXX` if `ListXXX` supports paging.

In the source of truth of this SDK, the pagable attribute is defined in an extension of swagger `x-ms-pagable` (I am taking the compute RP as an example): https://github.com/Azure/azure-rest-api-specs/blob/91c09193ab80bbf15e206dd68b7aeb432eb77d03/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L3480

Also could you please provide the SDK function with issues you are calling, so that I could take a look at the corresponding swagger configurations and determine which circumstance this issue belongs to. Thanks!

**Comment by SaiKalyan28** [comment]
@ArcturusZhang The function I am calling is `List` and the SDK also has the function `ListComplete`, so the List should support pageable response as per your comments. 
The `List` function in the following link is what I am using and facing issues (https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2021-02-01/containerservice/containerserviceapi/interfaces.go). 
Hope this is the information you are asking for.

Irrespective of this can I know what would be the maximum records per page if the response is paged and is there any way that it can be altered? 

Thanks :)

**Comment by ArcturusZhang** [comment]
Do you mind changing the title of this issue to avoid the confusion here? Per your replies, I assume it is the List in `ManagedClustersClientAPI` that has this issue, which comes from container services instead of container groups - container group is a resource in another RP `containerinstance`.

As we have discussed, this issue is actually not an issue in the SDK but a service side issue, therefore I have tagged this issue so that the corresponding service team could take a look.

**Comment by SaiKalyan28** [comment]
Thanks @ArcturusZhang for updating the issue.

**Comment by SaiKalyan28** [comment]
Hi 
I found this page https://docs.microsoft.com/en-us/rest/api/azure/#async-operations-throttling-and-paging and there mentioned `Typically, the response includes the nextLink property when the list operation returns more than 1,000 items`. 
In this case is there any option to change the results per page?

**Comment by ArcturusZhang** [comment]
> Hi
> I found this page https://docs.microsoft.com/en-us/rest/api/azure/#async-operations-throttling-and-paging and there mentioned `Typically, the response includes the nextLink property when the list operation returns more than 1,000 items`.
> In this case is there any option to change the results per page?

Some API provides a `top` query parameter to control the number of items in one page, but this API does not provide such parameter, therefore we currently do not have any approach to do this using the SDK.

**Comment by SaiKalyan28** [comment]
Thanks @ArcturusZhang for the details.
I found a similar issue https://github.com/Azure/azure-sdk-for-node/issues/2392. Can we follow the alternate approach provided in this issue using the `resources` package (https://github.com/Azure/azure-sdk-for-go/blob/master/services/resources/mgmt/2020-10-01/resources/resourcesapi/interfaces.go #L122)and filter the results using `resourceType` and `top` parameter.

I feel this is the only alternative that we have to control pagination.
