### ISSUE TITLE
Error: web.AppsClient#GetAppSettingsKeyVaultReferences: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field APIKVReferenceCollection.value of type web.ManagedServiceIdentity'

### ISSUE THREAD

**Issue by Subhajit97** [Azure/azure-sdk-for-go#14509]
### Bug Report

I would like to get the site key vault reference, therefore I am using `web.AppsClient.GetAppSettingsKeyVaultReferences`.
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/web/mgmt/2019-08-01/web#AppsClient.GetAppSettingsKeyVaultReferences
However, the API cause the following error:
```
Error: web.AppsClient#GetAppSettingsKeyVaultReferences: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field APIKVReferenceCollection.value of type web.ManagedServiceIdentity'
```

Indeed, in the JSON file that is reported in the error,
```
{
  "value": [
    {
      "id": "...",
      "name": "...",
      "type": "Microsoft.Web/sites/config/configreferences",
      "location": "...",
      "properties": {
        "reference": "@Microsoft.KeyVault(SecretUri=......)",
        "status": "Resolved",
        "vaultName": "...",
        "secretName": "...",
        "secretVersion": "...",
        "identityType": "...",
        "details": "Key Vault reference has been successfully resolved.",
        "activeVersion": null
      }
    }
  ],
  "nextLink": null,
  "id": null
}
```
- What happened?
- What did you expect or want to happen?
- How can we reproduce it?
- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment]
Hi @Subhajit97 thanks for this issue!

We could confirm that this issue comes from the swagger from which this sdk is generated: https://github.com/Azure/azure-rest-api-specs/blob/273cebe601c137222c802504425047845d4be409/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L21525
Unfortunately to fix this issue will introduce a breaking change to an existing api-version (and this is why we still has this issue here), but it has been fixed in a newer api-version: https://github.com/Azure/azure-sdk-for-go/blob/47e0b1d38a7da6bea826b885c2c605150d852d11/services/web/mgmt/2020-12-01/web/apps.go#L8413
Could you please have a try in the new api-version?

**Comment by Subhajit97** [comment]
Hi @ArcturusZhang,
I have tried with newer api-version 
https://github.com/Azure/azure-sdk-for-go/blob/47e0b1d38a7da6bea826b885c2c605150d852d11/services/web/mgmt/2020-12-01/web/apps.go#L8413

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v53.1.0+incompatible/services/web/mgmt/2020-12-01/web#AppsClient.GetAppSettingKeyVaultReference

Still I am getting the below error
`Error: web.AppsClient#GetAppSettingsKeyVaultReferences: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field APIKVReferenceCollection.value of type web.ManagedServiceIdentity'`

**Comment by ArcturusZhang** [comment]
> Hi @ArcturusZhang,
> I have tried with newer api-version
> https://github.com/Azure/azure-sdk-for-go/blob/47e0b1d38a7da6bea826b885c2c605150d852d11/services/web/mgmt/2020-12-01/web/apps.go#L8413
> 
> https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v53.1.0+incompatible/services/web/mgmt/2020-12-01/web#AppsClient.GetAppSettingKeyVaultReference
> 
> Still I am getting the below error
> `Error: web.AppsClient#GetAppSettingsKeyVaultReferences: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field APIKVReferenceCollection.value of type web.ManagedServiceIdentity'`

Sorry for the delay of response, could you also attach the response body in this new api-version call?

**Comment by Subhajit97** [comment]
@ArcturusZhang Here is the full error that I am getting in this new api-version call
```
Error: web.AppsClient#GetAppSettingsKeyVaultReferences: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field APIKVReferenceCollection.value of type web.ManagedServiceIdentity' JSON = '{"value":[{"id":"...","name":"...","type":"Microsoft.Web/sites/config/configreferences","location":"...","properties":{"reference":"@Microsoft.KeyVault(SecretUri=...)","status":"Resolved","vaultName":"...","secretName":"...","secretVersion":"...","identityType":"...","details":"Key Vault reference has been successfully resolved.","activeVersion":null}}],"nextLink":null,"id":null}'
```

**Comment by ArcturusZhang** [comment]
Hi @Subhajit97 by checking the responses above, this is still an issue that the service returns a model that is different from the one defined in swagger. In detail, the response was: 
```
{
  "value": [
    {
      "id": "...",
      "name": "...",
      "type": "Microsoft.Web/sites/config/configreferences",
      "location": "...",
      "properties": {
        "reference": "@Microsoft.KeyVault(SecretUri=...)",
        "status": "Resolved",
        "vaultName": "...",
        "secretName": "...",
        "secretVersion": "...",
        "identityType": "...",
        "details": "Key Vault reference has been successfully resolved.",
        "activeVersion": null
      }
    }
  ],
  "nextLink": null,
  "id": null
}
```
Please pay attention to the `identityType` here, it is a string in the response. But in swagger, it is defined as a model: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L20935

The swagger is reusing the models that defined for PUT request, which is very reasonable. But it is unreasonable that a List API returns a different model from the PUT request/response.

Since this is a service side issue, I have tagged this issue so that the corresponding service team could take a look and make some fix in the swaggers or the service response.

**Comment by rajlearner17** [comment]
Is there any progress for this?
