### ISSUE TITLE
SecurityInsights GroupingEntityType PossibleType Values don't match API

### ISSUE THREAD

**Issue by jstaffin-presidio** [Azure/azure-sdk-for-go#14506]
### Bug Report

Within /preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/enums.go

The following defines the allowed values for the grouping entity types.  The API does accept these values but when they are then read back the "Ip" and "Url" types are returned as "IP" and "URL". As the values are different than what was set, software that is managing state will see this as a change and re-apply the "Ip" or "Url", software such as the terraform azurerm provider does this.

// GroupingEntityType enumerates the values for grouping entity type.
type GroupingEntityType string

const (
	// Account Account entity
	Account GroupingEntityType = "Account"
	// FileHash FileHash entity
	FileHash GroupingEntityType = "FileHash"
	// Host Host entity
	Host GroupingEntityType = "Host"
	// IP Ip entity
	IP GroupingEntityType = "Ip"
	// URL Url entity
	URL GroupingEntityType = "Url"
)

The SDK should allow the use of "IP" or "URL" instead of "Ip" and "Url"

**Comment by ArcturusZhang** [comment]
Hi @jstaffin-presidio thanks for this issue!

Unfortunately we have the wrong values in the SDK because we have incorrect values in [the swagger from which this SDK is generated](https://github.com/Azure/azure-rest-api-specs/blob/273cebe601c137222c802504425047845d4be409/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json#L11612). To resolve this, I have tagged this issue so that the corresponding service team will take this a look.

**Comment by RickWinter** [comment]
@ArcturusZhang Is this resolved?
