### ISSUE TITLE
[Track2] Return result in response envelope by value

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#14529]
### Track2 Design Proposal

Currently, for non pager/poller api operations of the client, the generated code is like below:

```go
func (c *FooClient) Get(ctx context.Context, ...) (FooResponse, error) {...}

type FooResponse struct {
  Foo *Foo
  RawResponse *http.Response
}
```

In case of error, the users are expected to throw away to `FooResponse`.

However, in happy path, it is confusing for users to whether nil check the `resp.Foo` (same for `RawResponse`) before using it. Persumably, the nil check is not needed. Then shall we change the signature and model a bit to:

```go
func (c *FooClient) Get(ctx context.Context, ...) (*FooResponse, error) {...}

type FooResponse struct {
  Foo Foo
  RawResponse http.Response
}
```

Above, the fields are now non-pointer, while the `Get` returns a non-nil pointer of `FooResponse` in happy path).

Or even:

```go
func (c *FooClient) Get(ctx context.Context, ...) (*Foo, error) {...}
``` 

Above, the `http.Response` is thrown away at all. The reason is that I can't come up with a valid use case that users might want to   directly interact with the raw http response without using the available capabilities provided by the SDK. If there is one, then it is possibly something the SDK needs to support. On the other hand, if users simply wants to inspect/mutate the embedded response, then I think [`azcore.Policy`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#hdr-Processing_the_Response) is a better place to do that.

**Comment by tombuildsstuff** [comment]
@magodo having access to the raw HTTP response can be helpful when working around limitations of the SDK, particularly with the complexity of doing that in AzCore I could see that being useful in the future tbh (for example parsing out headers, or unmarshalling into a more specific type if the model is omitting those fields).

Whilst the happy path would be made easier with these changes, ultimately the fact the Swaggers are incomplete/an afterthought necessitate these escape-hatches for folks who want to use the SDK.

An example of that scenario would be Role Assignment, where there's some critical features not defined in the Swagger (the createdon/updatedon iirc) - since on the backend the service appears during update to temporarily create a new role assignment before reconciling it into the existing one - meaning we end up needing to check these values to check they're the same. Whilst that's doable by duplicating the code, it's a lot easier to do that into a native type rather than doing the whole object (although that's what we're doing today).

>  If there is one, then it is possibly something the SDK needs to support.

Whilst this is a good point, ultimately that requires co-ordination with the service team to patch the associated swagger - which can take months: https://github.com/Azure/azure-rest-api-specs/pull/8435#discussion_r381807854 - leaving users blocked in the interim.

Arguably this SDK could expose some "official" mechanism for working around those limitations - but given the current state of the Swagger, and the delays it takes to get fixes in, I'd argue this'd make it harder for consumers of the SDK to workaround these issues.

WDYT?

**Comment by magodo** [comment]
@tombuildsstuff That makes perfect sense given the complex reality, and thank you for providing these real examples here!

Meanwhile,  I think it still makes sense to change the types of the fields in the `FooResponse` to non-pointers.

**Comment by tombuildsstuff** [comment]
@magodo I can't speak to the original authors intentions, but my guess would be the HTTP Response is a pointer to avoid copying the (potentially large) body. Tbh the Response object itself makes sense as a pointer as it's not guaranteed to be returned, for example if there's an error with an http response but no model (because an error is returned). That allows consumers of the SDK to avoid bugs when the response object isn't returned, rather than being nil (and getting an obvious crash) if the error isn't checked?

**Comment by magodo** [comment]
@tombuildsstuff

The `http.Response`'s heavy part are pointers (the map and the reader), which I feel is not too heavy to copy. Also, once users get the `FooResponse`, then one can pass on the address of the RawResponse along the way.

Regarding the response body, I agree with your point that this can avoid users ignore error and use the response anyway, and a panic is better than being silent. But this is already something out of the goal that the SDK have to provide?

**Comment by jhendrixMSFT** [comment]
After some discussion, we've landed on the following.  https://play.golang.org/p/BGBAPrVA_CO

**Comment by jhendrixMSFT** [comment]
Also here https://gist.github.com/jhendrixMSFT/1b982a7c93708a9ab78a37d089355d99

**Comment by magodo** [comment]
@jhendrixMSFT Would you please indicate some more details about how does this signature benefit the transition to generics? BTW, will generics come with other impacts to the language, which causes making the trasition seamless not necessarily a must have?

**Comment by jhendrixMSFT** [comment]
Generics will let us define a generic response type in `azcore`.

```go
type Response[T any] struct {
    T
    RawResponse *http.Response
}```

This would replace the `GetWidgetResponse` with a `Response[GetWidgetResult]` in the codegen without introducing a breaking change.

**Comment by magodo** [comment]
Good to know. While I guess this is not the reason to make the return type of `GetWidget()` not return a pointer? Also, does `GetWidget()` return an `error`?

**Comment by jhendrixMSFT** [comment]
Real API would return an error yes, it was omitted from the sample for brevity.

**Comment by chamons** [comment]
Given this note:

https://github.com/Azure/autorest.go/pull/658#issuecomment-881608381

I believe this is fixed, and am closing.
