### ISSUE TITLE
Create Azure-Sentinel Scheduled Alert Rule using SubscriptionID other than the client object SubscriptionID

### ISSUE THREAD

**Issue by jstaffin-presidio** [Azure/azure-sdk-for-go#14537]
The CreateOrUpdate function on the AlertRules client within the SDK does not allow for passing a subscription ID as a parameter.  The CreateOrUpdatePreparer function is written such that it only gets the subscription ID from the client object

When using Azure Lighthouse delegated permissions, the targeted subscription may not be the same as the client subscription.  The SDK should allow for the definition of the subscription ID as a parameter to allow for the creation of an alert rule in targeted subscription ID that is different than the client subscription ID.

Please see the below line which is building the path for the AlertRule and is simply looking up the subscription from the client object.

https://github.com/Azure/azure-sdk-for-go/blob/e89292417a2c79d1d660ef90d69a3b46b1f1fdb3/services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/alertrules.go#L89-L113

https://github.com/Azure/azure-sdk-for-go/blob/e89292417a2c79d1d660ef90d69a3b46b1f1fdb3/services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/alertrules.go#L95

The Azure API Allows for this usage but this SDK is not built to allow for passing SubscriptionID as a parameter.

**Comment by ArcturusZhang** [comment]
Hi @jstaffin-presidio thanks for this issue!

Unfortunately this behaviour is encoded in the swagger from which this SDK package was generated and by-design, we are not able to change this because this would be a big breaking change not only for the go SDK but also all other SDK of other languages.
On the other hand, the definition of a SDK "client" is just a method group on one particular subscription id (there are some exceptions for those APIs that could apply to different scopes, but that is another story), therefore in this case, usually you will need to build another client on your desired subscriptionId, or using the easy way that you could copy your client and change the subscriptionId in your copy like this:
```
// say `client` is the pointer of your client on subscription 000000-0000-0000-0000-00000000
newClient := *client // make sure to dereference if client is a pointer
newClient.SubscriptionId = "111111-1111-1111-1111-11111111"
// then you can use the new client
```

**Comment by jhendrixMSFT** [comment]
If the API call needs to pass a subscription ID other than what the client was initialized with the swagger should be fixed.  Can you please follow up with the service team about it?
