### ISSUE TITLE
Support entityMappings and Custom key/value pairs on Scheduled Alert Rule Create or Update - Azure Sentinel

### ISSUE THREAD

**Issue by jstaffin-presidio** [Azure/azure-sdk-for-go#14573]
### Feature Request

Azure Sentinel has added a new method for configuring Entity mappings and a method for defining custom details (key/value pairs).  

This page describes the Azure Portal method for configuring the Entity Mappings on an alert rule
https://docs.microsoft.com/en-us/azure/sentinel/map-data-fields-to-entities

This page describes the Azure Portal method for configuring the custom details key/value Paris on an alert rule
https://docs.microsoft.com/en-us/azure/sentinel/surface-custom-details-in-alerts

Neither the current GA nor the preview REST or SDK for go support configuring these elements on an alert rule.

At the moment all other aspects of our sentinel deployment are automated except for this capability.  We require the ability to map these values to surface required context on the generated alert for use in our SOAR workflows.  We currently deploy rules using an automated method and require Azure Portal manual configuration to perform the remaining entity mapping and custom details configuration.

**Comment by ArcturusZhang** [comment]
Hi @jstaffin-presidio thanks for this issue!

The repo mainly will contain the SDK that generates from the REST APIs [here](https://github.com/Azure/azure-rest-api-specs), therefore we cannot directly help on this until we actually have the REST API published. But I have tagged this issue so that the corresponding service team might see and help.
