### ISSUE TITLE
Support OMS auditing for SQL Server

### ISSUE THREAD

**Issue by nexxai** [Azure/azure-sdk-for-go#14583]
### Feature Request

Now that Azure SQL Server supports auditing using a Log Analytics Workspace as a target, it would be nice if it could actually be configured via the SDK.  

Thoughts?

![Screen Shot 2021-04-22 at 2 47 15 PM](https://user-images.githubusercontent.com/4316564/115786638-50b24800-a37e-11eb-954e-396b97ff48ae.png)

The two fields that are pointed to with red arrows show fields that are currently accessible via the SDK, but the green arrow value is not, so while you can technically enable Log Analytics auditing, you can't choose the Workspace to send to.

**Comment by nexxai** [comment]
For reference, I believe the offending block is here: https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/v4.0/sql/models.go#L5608

This code:
```go
	IsAzureMonitorTargetEnabled *bool `json:"isAzureMonitorTargetEnabled,omitempty"`
```
allows you to enable Azure Monitor targeting, but there's no property to define the OMS Workspace

**Comment by ArcturusZhang** [comment]
Hi @nexxai thanks for this issue!

I just checked the corresponding swagger for sql composite-v4 - they do not have this functionality in the swagger. Therefore I have tagged this issue so that the service team could know of this and update their swagger, after that we could release a new SDK with the new functionalities.
