### ISSUE TITLE
Add v4 and v5 Azure VM Support for VirtualMachineSizeTypes

### ISSUE THREAD

**Issue by christianrowlands** [Azure/azure-sdk-for-go#14646]
### Feature Request

In looking at the [VirtualMachineSizeType options here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/compute/mgmt/2021-03-01/compute/enums.go#L1201), I am not seeing any of the [v4](https://docs.microsoft.com/en-us/azure/virtual-machines/dv4-dsv4-series#dv4-series) or v5 D2 VM options. D2 v5 is in preview currently, so it makes sense not to support those quite yet, but v4 looks ready for use so I am hoping they can get added to the structure.

I am using Rancher to deploy Kubernetes nodes to Azure and I would like to be able to take advantage of the newer VM types in Azure, especially v5 VMs when they are out of "preview" as they are cheaper than the v3 VMs.

I appreciate the help!

**Comment by ArcturusZhang** [comment]
Hi @christianrowlands thanks for this issue!

Currently the compute part in package `github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2021-03-01/compute` comes from compute api-version 2020-12-01 instead of 2020-03-01 (for instance you can find the api-version in one of the operation of compute: https://github.com/Azure/azure-sdk-for-go/blob/6b0c0e55132b69d19f47845d51910bb237191173/services/compute/mgmt/2021-03-01/compute/virtualmachines.go#L72)

We will soon update the compute part in this package to 2021-03-01, generated from [this swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/compute.json#L9438). But in the meantime, I did not find and v4 or v5 in the vm size list here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/compute.json#L9438

In fact, there was once a proposal that the compute service team want to remove the list of candidates of vm size in the swagger, because it is very hard to maintain (I personally agree with this). But considering of the breaking changes this would cause to all of the SDKs, we cannot perform this removal.

As a very valid workaround, as long as you know the correct vm size value, you can always use this 
```
vmSize := compute.VirtualMachineSizeTypes("something")
```
to manually assign a vm size that is not in this list.
In the meantime, we have [this operation](https://github.com/Azure/azure-sdk-for-go/blob/6b0c0e55132b69d19f47845d51910bb237191173/services/compute/mgmt/2021-03-01/compute/virtualmachinesizes.go#L39) to list all supported vm sizes in one location.

Considering that we have a workaround (actually it is the recommended usage) and a way to list all of the vm sizes, I am going to close this issue. Please feel free to post more questions and concerns about this if there is any. Thank you!
