### ISSUE TITLE
Use new postgres API

### ISSUE THREAD

**Issue by johgoe** [Azure/azure-sdk-for-go#14795]
### Feature Request
Current Implementation still uses:
https://github.com/Azure/azure-sdk-for-go/tree/master/services/postgresql/mgmt/2017-12-01/postgresql
but a new version is already available
https://github.com/Azure/azure-sdk-for-go/tree/master/services/postgresql/mgmt/2020-01-01/postgresql

**Comment by ArcturusZhang** [comment]
Hi @johgoe thanks for opening this issue!

Could you please specify the issue?

**Comment by johgoe** [comment]
I'm worried the old api will not be supported one day. That's why I think it's good to plan the switch to a newer api earlier.

**Comment by ArcturusZhang** [comment]
The package for old api-version will stay in this repo until it finishes its official deprecation process. But currently we do not have any deprecation announcement on that api-version yet.
I am not sure if this could fulfill your worry.
If you are tracking that you should use the new package instead of the old one, maybe you need to open the issue in your project instead of here.
