### ISSUE TITLE
DeviceConnectionStateEvents  is missing from IOT management API

### ISSUE THREAD

**Issue by ramondeklein** [Azure/azure-sdk-for-go#14993]
### Bug Report
`DeviceConnectionStateEvents` routing source is missing:
* Enumeration: https://github.com/Azure/azure-sdk-for-go/blob/862673ef08ed0598660f54db809772c921455c23/services/iothub/mgmt/2020-03-01/devices/enums.go#L326
* Possible routing-source values: https://github.com/Azure/azure-sdk-for-go/blob/862673ef08ed0598660f54db809772c921455c23/services/iothub/mgmt/2020-03-01/devices/enums.go#L341

This enumeration was added on May 13 to the Azure SDK (see https://github.com/Azure/azure-sdk-for-net/blob/978837dcd7f8459f4e54ea11fd3934d787b8490b/sdk/iothub/Microsoft.Azure.Management.IotHub/src/Generated/Models/RoutingSource.cs#L24).

**Comment by lirenhe** [comment]
Need to refresh the GO SDK to catch the latest change in Swagger.

**Comment by 804873052** [comment]
Hi @ramondeklein thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by 804873052** [comment]
iothub stable latest version 2021-03-01 released in: https://github.com/Azure/azure-sdk-for-go/tree/v57.4.0/services/iothub/mgmt/2021-03-31/devices
