### ISSUE TITLE
Support tables in [LogAnalytics]

### ISSUE THREAD

**Issue by dmedeiros204** [Azure/azure-sdk-for-go#15407]
### Feature Request

Please add support to update tables in your log-analytics workspace using the following API

https://docs.microsoft.com/en-us/rest/api/loganalytics/tables/update

**Comment by 804873052** [comment]
Hi @dmedeiros204  thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by dmedeiros204** [comment]
Thanks @804873052!
I'd really appreciate using this functionality when available to create a terraform resource on the azurerm provider to enable teams to set the retention on the table level for their LogAnlaytics workspaces.

**Comment by lirenhe** [comment]
API version of 2020-10-01 released. 
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/operationalinsights/mgmt/2020-10-01/operationalinsights
