### ISSUE TITLE
Support Service Bus 2021-06-01-preview

### ISSUE THREAD

**Issue by dylanmorley** [Azure/azure-sdk-for-go#15475]
### Service Package Request

The specification for service bus at [version 2021-06-01-preview](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/servicebus/resource-manager/Microsoft.ServiceBus/preview/2021-06-01-preview) supports parameter 'trustedServiceAccessEnabled' which would enable Terraform to support a parameter, e.g. allow_trusted_microsoft_services_bypass_firewall 

https://github.com/hashicorp/terraform-provider-azurerm/issues/9740

Request to generate a servicebus package 2021-06-01-preview to support this feature

**Comment by 804873052** [comment]
Hi @dylanmorley thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by aristosvo** [comment]
@lirenhe This is also required for https://github.com/hashicorp/terraform-provider-azurerm/issues/13514. Would be great to have!

**Comment by dylanmorley** [comment]
I think now available, from this PR https://github.com/Azure/azure-sdk-for-go/pull/15672 and available on v58

**Comment by lirenhe** [comment]
Close it as the package 2021-06-01-preview was released.
