### ISSUE TITLE
Release Microsoft.ApiManagement/preview/2021-01-01-preview

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-go#15504]
### Service Package Request

Hi can https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2021-01-01-preview please be released to this SDK?

`2020-12-01` is the latest available currently https://github.com/Azure/azure-sdk-for-go/tree/main/services/apimanagement/mgmt

Blocks https://github.com/hashicorp/terraform-provider-azurerm/issues/12021

**Comment by 804873052** [comment]
Hi @timja thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by 804873052** [comment]
released in https://github.com/Azure/azure-sdk-for-go/tree/v57.3.0/services/preview/apimanagement/mgmt/2021-01-01-preview/apimanagement
