### ISSUE TITLE
The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2020-10-01-preview

### ISSUE THREAD

**Issue by ripa1993** [Azure/azure-sdk-for-go#15624]
### Bug Report

- import path: `github.com/Azure/azure-sdk-for-go/sdk/authorization/armauthorization`
- SDK version: 5.74.0
```
github.com/Azure/azure-sdk-for-go v57.4.0+incompatible
github.com/Azure/azure-sdk-for-go/sdk/authorization/armauthorization v0.2.0
```
- output of `go version`:
```
go version go1.17 darwin/amd64
```

- What happened?
It's not possible to create role assignments via `armauthorization.RoleAssignmentsClient` due to
```
Error: error initing provider: {"error":{"code":"InvalidResourceType","message":"The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2020-10-01-preview'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2017-10-01-preview,2018-01-01-preview,2018-07-01,2018-09-01-preview,2018-12-01-preview,2019-04-01-preview,2020-03-01-preview,2020-04-01-preview,2020-08-01-preview,2021-04-01-preview'."}}
```

- What did you expect or want to happen?
I would expect to successfully create the role assignment

- How can we reproduce it?
Invoking the function Create(...) like in 
```go
	_, err := c.Create(
		ctx,
		scope,
		uuid.NewV1().String(),
		armauthorization.RoleAssignmentCreateParameters{
			Properties: &armauthorization.RoleAssignmentProperties{
				RoleDefinitionID: roleDefID,
				PrincipalID:      to.StringPtr(principalID),
				PrincipalType:	  armauthorization.PrincipalTypeServicePrincipal.ToPtr(),
	}}, nil)
```
where: 
1. `roleDefID` is a role definition id retrieved via list API
2. `principalID` is the id of a service principal previously created
3. `scope` is a resource group id

**Comment by 804873052** [comment]
Hi @ripa1993 thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by ripa1993** [comment]
any update?

**Comment by gsosin88** [comment]
Any updates on this one?

**Comment by dagoroz** [comment]
The 2020-10-01-preview issue is “expected” as it includes changes that turned out to be problematic.
That version has been exposed and unexposed multiple times.

For the 2021-04-01-preview that is also expected that is a version for internal use and ARM does not have a way to expose versions exclusively to Microsoft services.

**Comment by Alancere** [comment]
please use: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization/v2

You could also try the following method to specify api-version:
```go
armauthorization.NewRoleAssignmentsClient(subscriptionId, cred, &arm.ClientOptions{
    ClientOptions: policy.ClientOptions{
	    APIVersion: "specify api-version",
    },
})
```
