### ISSUE TITLE
Support Tags on App Service Environments

### ISSUE THREAD

**Issue by larsmaes** [Azure/azure-sdk-for-go#15631]
### Feature Request
Please support defining tags on the app service environments api

**Comment by ArcturusZhang** [comment]
Hi @larsmaes thanks for this issue!

We already supported tags on the AppServiceEnvironment API: https://github.com/Azure/azure-sdk-for-go/blob/68917a8081b5b2362b75be7fd985d50004621fa1/services/web/mgmt/2021-02-01/web/appserviceenvironments.go#L263 (I cannot give you a link to the corresponding models since that file is too big for Github to render)

**Comment by tombuildsstuff** [comment]
@ArcturusZhang this needs to be added to the Patch API too, the PUT endpoint can cause an outage iirc
