### ISSUE TITLE
Release Request For RecoveryServices 2021-08-01

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/azure-sdk-for-go#15764]
### Service Package Request

There are a bunch of new features in the latest recoveryservices RP version 2021-08-01, comparing to the currently available 2016-06-01. Appreciate if we can have that latest version in the Go SDK.

**Comment by 804873052** [comment]
Hi @lonegunmanb thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by Alancere** [comment]
released https://github.com/Azure/azure-sdk-for-go/releases/tag/v60.2.0
