### ISSUE TITLE
fails to be a dependency on go 1.13, works on 1.17

### ISSUE THREAD

**Issue by serprex** [Azure/azure-sdk-for-go#15982]
Using go 1.13, building [my wal-g branch](https://github.com/citusdata/wal-g/tree/azure-sdk-for-go) failed with

`build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/azcore: no Go source files`

I updated infra to use go 1.17 & it worked, just as it worked locally where I'm using 1.17

Personally, I'll just use 1.17, but you might want to bump the minimum version in go.mod

Also causing CI failures for https://github.com/wal-g/wal-g/pull/1135

**Comment by jhendrixMSFT** [comment]
Hello!  We do specify version 1.16 in our go.mod file.  From the [docs](https://golang.org/doc/modules/gomod-ref#go), the `go` directive doesn't prevent compilation on older versions of Go, but aids in compilation failures.  In this case, the compilation failures aren't present due to usage of build constraints that prevent compilation on versions earlier than 1.16.

**Comment by jhendrixMSFT** [comment]
Hello!  We do specify version 1.16 in our go.mod file.  From the [docs](https://golang.org/doc/modules/gomod-ref#go), the `go` directive doesn't prevent compilation on older versions of Go, but aids in compilation failures.  In this case, the compilation failures aren't present due to usage of build constraints that prevent compilation on versions earlier than 1.16.
