### ISSUE TITLE
Request: Add support for policy API-version 2021-06-01

### ISSUE THREAD

**Issue by larsakerlund** [Azure/azure-sdk-for-go#16109]
### Service Package Request

API-version 2021-06-01 has support for `nonComplianceMessages`, which improves the policy experience dramatically.

Terraform provider AzureRM requires an update to the SDK in order to implement support for this, since it is not available in 2019-09-01: https://github.com/hashicorp/terraform-provider-azurerm/issues/10401

**Comment by lirenhe** [comment]
@804873052, could you help to follow up with service team?

**Comment by 804873052** [comment]
Hi @larsakerlund thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by 804873052** [comment]
@larsakerlund this released in https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/resources/mgmt/2021-06-01-preview/policy

**Comment by larsakerlund** [comment]
Completely missed the preview section. Thank you!
