### ISSUE TITLE
Rename blob object

### ISSUE THREAD

**Issue by ior308** [Azure/azure-sdk-for-go#16191]
### Feature Request

Dear,  

is there a "rename" API to rename a blob into a container ? Or I  must read/write to a new blob and delete the old ?

Best Regards

**Comment by RickWinter** [comment]
Renaming a blob involves copying the blob from the old name (location) to the new name (location) and then deleting the old blob.

**Comment by ior308** [comment]
Yes, but consider renaming bigger file... 1T etc... it would be better to have an API to rename the object without having to copy and remove, right ?

**Comment by zezha-msft** [comment]
@ior308 That's a fair point, there is a rename API on the dfs endpoint (ADLS Gen2 API). Once we develop the datalake SDK you'll be able to leverage that rename API instead of copying and deleting blobs. We are currently targeting Q1 2022 for that new SDK.

Please let us know if you have any question.

**Comment by ior308** [comment]
Thanks this is good news

**Comment by WhileLoop** [comment]
@zezha-msft Did this ADLS Gen2 API get added?
