### ISSUE TITLE
Release request for Insights 2021-09-01

### ISSUE THREAD

**Issue by MSSedusch** [Azure/azure-sdk-for-go#16266]
### Feature Request

I would like to implement an Event Hub Receiver in Terraform which was added in the latest Monitor (Insights) API version 2021-09-01.
Can you please create the code for 
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-09-01

Thanks

**Comment by dennis-menge** [comment]
for reference: https://github.com/Azure/sdk-release-request/issues/2259

**Comment by ArcturusZhang** [comment]
Opened a [PR](https://github.com/Azure/azure-rest-api-specs/pull/17128) for this request.
I have to emphasize that the generated code from this version will be buggy for some APIs, since we have some model name collisions on the swaggers. This bug comes from a malformed swagger and our old code generator (which generates everything in the `services` directory) cannot handle this case properly.
But I believe this bug does not impact what @MSSedusch wants to implement in terraform. Just FYI

**Comment by ArcturusZhang** [comment]
close this since this has been released
