### ISSUE TITLE
BotService model doesn't align with its definition in Swagger

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#16297]
The BotService model in current SDK has a property [`isIsolated`](https://github.com/Azure/azure-sdk-for-go/blob/8a696eee495ea9373f6853a9d1574e7db356d7ff/services/botservice/mgmt/2021-03-01/botservice/models.go#L361), which is renamed to `publicNetworkAccess` in the Swagger: https://github.com/azure/azure-rest-api-specs/commit/c4d6f92d3fd35a69ebce68f4c73c35c4238c2ac5.

**Comment by Alancere** [comment]
Hi @magodo thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by Alancere** [comment]
released in https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/botservice/mgmt/2021-05-01-preview/botservice
