### ISSUE TITLE
Create CosmosDB Database/Collections

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/azure-sdk-for-go#1637]
Hi,

Looking through the existing CosmosDB functionality, it looks like I can only programmatically create database accounts, I'm not able to create the database itself or the collection (which have some parameters that can be tuned). Am I stuck calling the API myself or using the portal? It seems like it's possible to do this with the Node SDK and the Java SDK. 

It would be super helpful if we published a client for these like we do in many other languages. Passing the auth header is non trivial and would be much better handled by a go lib like we have for Java/Node/Python/Dot Net.

**Comment by ryancrawcour** [comment]
We need this for Terraform support, so we're able to spin up not only the account, but also the database and the collection. Now that ARM supports database and collection, it makes sense to add this to Terraform as well. In order to do this we need it in the Azure GO SDK. 

Anyone mind if i contribute basic functionality to the Azure GO SDK for this? 
@shireeshthota @kirillg

**Comment by tombuildsstuff** [comment]
@ryancrawcour FWIW Terraform supports creating CosmosDB Collections and Databases now: https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_mongo_collection.html

**Comment by ryancrawcour** [comment]
Thanks, but not interested in the Mongo API
