### ISSUE TITLE
Document how to interact with sovereign/private clouds

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#16638]
We support non-public clouds but don't have any docs/samples on how to connect to them.  This comes up periodically and has been a pain-point in the past.

**Comment by lirenhe** [comment]
@jhendrixMSFT , I suggest adding one page in https://docs.microsoft.com/en-us/azure/developer/go/ for this work.

**Comment by jhendrixMSFT** [comment]
The fits in nicely with the work that @chlowell did for the `cloud` package.

**Comment by patrickdillon** [comment]
@chlowell I see that azidentity for go has moved to stable. Is Azure Stack supported?

**Comment by chlowell** [comment]
Depends on the authentication provider for your Stack. azidentity supports Azure AD but not ADFS. We're tracking ADFS support with #14405.

I see I never came back to update this issue! Let me do that now: the PR I mentioned above shipped, and the current cloud configuration API is covered in the documentation for [azcore/cloud](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore@v1.1.1/cloud). I'll leave this issue open because I agree with Renhe that it would be best to cover this on Microsoft Docs as well.
