### ISSUE TITLE
Resource Health -- Events API

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#16716]
### Bug Report
Neither the mgmt sdks, or the new module SDKs (t2) implement the event API for resource health. Defined [here](https://docs.microsoft.com/en-us/rest/api/resourcehealth/events)

both of these SDK's implement `2017-07-01` version of this API & it apparently does not include events APIs

can we get this added, please?

**Comment by lirenhe** [comment]
@Alancere , could you help to follow up on this?  From the readme file, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resourcehealth/resource-manager/readme.md#basic-information, the default tag is always 'package-2017-07' which is quite out-of-date.

**Comment by Alancere** [comment]
Hi @vijayrajah thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by chrislinan** [comment]
Hi @Alancere, I have the same question with @vijayrajah since it has passed 6 months. Do you have any updates for this?
I am using the SDK: "github.com/Azure/azure-sdk-for-go/profiles/latest/resourcehealth/mgmt/resourcehealth"
I can only find operations and availability clients in this SDK, the other three are missing. 
But I want to read the events information and impacted resources from the SDK. Can you help? Thanks a lot.
![image](https://user-images.githubusercontent.com/12604912/175974003-209ffd5d-c782-4f71-a69d-b2fac2e9fae6.png)

**Comment by lirenhe** [comment]
@Alancere, could you help to follow up with the service team?

**Comment by vijayrajah** [comment]
@lirenhe , @Alancere  -- any update on this one? the module `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth` with version `1.0.0` (latest available version) is still using `2020-05-01` API version & event API is still not available

**Comment by lirenhe** [comment]
@vijayrajah, our SDK are generated by the configuration and their Swagger files from service team 
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/resourcehealth/resource-manager
So, do you know what API version that has the event APIs?    The original link returns 404

**Comment by vijayrajah** [comment]
@lirenhe  -- I think API Version `2022-05-01` has the events API , you can check [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/resourcehealth/resource-manager/Microsoft.ResourceHealth/stable/2022-05-01)

**Comment by lirenhe** [comment]
> @lirenhe -- I think API Version `2022-05-01` has the events API , you can check [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/resourcehealth/resource-manager/Microsoft.ResourceHealth/stable/2022-05-01)

@Alancere, could you help to contact service team for a new release with this tag?  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resourcehealth/resource-manager/readme.md#tag-package-2022-05  thanks

**Comment by Alancere** [comment]
package released(package-2022-10): https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcehealth/armresourcehealth@v1.2.0
