### ISSUE TITLE
InteractiveBrowserCredentialOptions does not have ClientSecret field

### ISSUE THREAD

**Issue by discentem** [Azure/azure-sdk-for-go#16723]
### Bug Report

- Import path: `github.com/Azure/azure-sdk-for-go/sdk/azidentity`
- SDK version: `master`
- go version: `go version go1.17.3 darwin/amd64`

- What happened?

I can use `azidentity.NewInteractiveBrowserCredential` to successfully create a `azblob.NewContainerClient` but when I try to do `container.NewBlobClient("someBlob").GetProperties` this fails with the following error

```
(invalid_client) AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
``` 

- What did you expect or want to happen?

Getting blob properties should succeed

- How can we reproduce it?

Build https://github.com/discentem/bk_azureblob/tree/4c92da8b88b2312e079b92c58728db5b8f45d29f and run without any flags. 

```
./bk_azureblob
```

In contrast

```
./bk_azureblob --device_code
```

will succeed as this credential type does not appear to require a `client_secret`

**Comment by chlowell** [comment]
InteractiveBrowserCredentialOptions has no ClientSecret field because we don't intend to support browser authentication for Azure AD applications requiring a client secret to authenticate ("confidential" applications). So, that's a deliberate omission.

That doesn't mean browser auth is impossible for your application though. Have you configured a redirect URI (see [Azure AD documentation](https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app#add-a-redirect-uri))? If your application has no redirect URI, or only one for the web platform, Azure AD considers it a confidential application in the auth code flow, and so requires a client secret.

**Comment by discentem** [comment]
Hey @chlowell, thanks for the detailed reply!

After changing my redirect URI configuration from web to desktop app, as you suggested, `NewInteractiveBrowserCredential` works as expected. 

Two things that are a bit curious. Please confirm if these are expected

- the landing page for successful auth (`You have logged into Microsoft Azure!`) is listening on a different port than the URI I specified: I specified `http://localhost:9090` and it shows this page on `http://localhost:8681/`. 
- I am not actually running an http server on 9090 but my app does get a auth token. Does `InteractiveBrowserCredentialOptions` automagically handle spinning up a web server on my behalf to pass along the token? 

Cheers,
Brandon

**Comment by chlowell** [comment]
Both are expected. azidentity starts a web server on an arbitrary port to receive the redirect, and Azure AD doesn't always require that port to match the app registration. (If it did, you would set `InteractiveBrowserCredentialOptions.RedirectURL` with the registered URL.)
