### ISSUE TITLE
Add managed identity token caching

### ISSUE THREAD

**Issue by UnwashedMeme** [Azure/azure-sdk-for-go#16765]
### Feature Request

**Scenario**: I'm currently creating many SDK clients because I'm working with many different resource types on many different subscriptions. However each client has its own pipeline with separate BearerTokenPolicy instances with separate token caches, each for the same scope (often management.azure.com). I'm running into MSI rate limits.

Example callstack (all links are to hash 2bdeaff722549f5381a88939ce85149fae079b69 which is for tag v61.1.0)
* A new client: https://github.com/Azure/azure-sdk-for-go/blob/2bdeaff722549f5381a88939ce85149fae079b69/sdk/resourcemanager/compute/armcompute/zz_generated_disks_client.go#L33 creates a new pipeline https://github.com/Azure/azure-sdk-for-go/blob/2bdeaff722549f5381a88939ce85149fae079b69/sdk/resourcemanager/compute/armcompute/zz_generated_disks_client.go#L41
* A new pipeline: https://github.com/Azure/azure-sdk-for-go/blob/2bdeaff722549f5381a88939ce85149fae079b69/sdk/azcore/arm/runtime/pipeline.go#L20 creates a NewBearerTokenPolicy https://github.com/Azure/azure-sdk-for-go/blob/2bdeaff722549f5381a88939ce85149fae079b69/sdk/azcore/arm/runtime/pipeline.go#L28
  * This  NewPipeline version has a new func signature that introduced pipeline options (looks to be currently unreleased) but those plOpts don't have control over the token policy.
  * older versions behave the same
* The BearerToken Policy: https://github.com/Azure/azure-sdk-for-go/blob/2bdeaff722549f5381a88939ce85149fae079b69/sdk/azcore/arm/runtime/policy_bearer_token.go#L53  implements a token cache (L78 is the cache get)

As an SDK user I don't think I have any clean way of controlling this. If I try to provide a custom pipeline perretry policy that has a single BearerTokenPolicy across many clients that doesn't prevent the new pipeline from adding its own BearerTokenPolicy. Since this policy also doesn't check if the header is already set it will also try to get its own token.

#### Suggestions

cache at the azidentity layer, keyed on the TokenRequestOptions.  This could be a separate TokenCache struct that implements `TokenCredential` interface (`GetToken`) which would it allow it to be stacked on an underlying `TokenCredential`, or even another `TokenCache` which might be useful for managing cache contention.

BearerTokenPolicy is doing two different things right now -- adding the header, implementing caching.  This policy should be about header management and rely on an underlying cache.  If there was a standard TokenCache then either NewPipeline or NewBearerTokenPolicy could wrap the credential it receives if we feel the pipeline needs to guarantee a cache in place.
 
#### related
* https://github.com/Azure/azure-sdk-for-go/issues/10567 ?

The now deprecated arm.Connection object seemed like a good place to hold the pipeline and hence the credential cache, but it looks like the only thing it actually did was just hold options that would be used when actually building the pipeline on the client.

**Comment by jhendrixMSFT** [comment]
@chlowell I believe our migration to MSAL will solve this yes?

**Comment by chlowell** [comment]
Correct, the managed identity implementation is entirely ours (no MSAL supports it) and doesn't use a cache. As noted above, clients have a caching layer (a simple performance optimization really, not a proper token cache) in their authentication policies, which doesn't help an application using many clients because each has its own policy instance. We do intend to add a proper token cache to managed identity credentials in all SDKs (e.g. .NET shares this problem), and I think that's a better solution than adding API. We've asked the MSAL team to expose their cache so we can simply use that; now we're past the holidays, I'll follow up on the timeline. Implementing our own token cache is another option. We've been reluctant to do that because of the complexity and redundancy with MSAL. However, managed identity is a simpler domain for token caching because there are no user accounts involved, so we can consider rolling our own implementation if the MSAL change is too far out.

**Comment by chlowell** [comment]
The MSAL team is designing a caching API. I expect that design to be complete before we can roll our own cache here in the SDK, so it will probably make more sense to wait for, or contribute to, MSAL than to implement our own cache. I'm moving this issue to the April milestone, which is optimistic but I believe the earliest we could finish the work.

**Comment by weinong** [comment]
Can you link the issue from msal please, if there is any?

**Comment by chlowell** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/302
