### ISSUE TITLE
Metadata key case is changed while using BlobClient.GetProperties

### ISSUE THREAD

**Issue by jaisonjose89m** [Azure/azure-sdk-for-go#16791]
### Bug Report
- import path of package in question - "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob" v0.2.0
- go version go1.17.5 darwin/amd64

- Issue
We have set a metadata for our block blob object during upload. Metadata set is `correlation_id` with value `D8681D0D-86D1-E91E-0016-7939CB6694D2`. (Note: Verified the metadata by connecting to the container using Azure storage explorer. It appears as expected).
But when we retrieve it using the `BlobClient.GetProperties` we get the key as `Correlation_id` with first character in uppercase.

- What did you expect ?
Key returned should be of the same case as set on the object. ie (`correlation_id` in our case)

- How can we reproduce it?
Create a block blob object set a metadata with all characters in lower case. And use `BlobClient.GetProperties` method to retrieve the metadata.

- Anything we should know about your environment.
We don't think there is anything specific about the environment. It should be reproducible every where. 

- Additional info 
We checked the xml response that is received by the client and could see that the tag name itself contain the metadata with first character in uppercase. 
 ```xml
       <Blob>
            <Name>test/pid-0.json</Name>
            <Properties>
                <Creation-Time>Mon, 10 Jan 2022 10:14:07 GMT</Creation-Time>
                <Last-Modified>Mon, 10 Jan 2022 10:20:27 GMT</Last-Modified>
                <Etag>0x8D9D422D2A9E7B5</Etag>
                <Content-Length>90</Content-Length>
                <Content-Type>application/json</Content-Type>
                <Content-Encoding />
                <Content-Language />
                <Content-CRC64 />
                <Content-MD5>kY+6H0jnsEZ71rmVgg6qtQ==</Content-MD5>
                <Cache-Control />
                <Content-Disposition />
                <BlobType>BlockBlob</BlobType>
                <AccessTier>Hot</AccessTier>
                <AccessTierInferred>true</AccessTierInferred>
                <LeaseStatus>unlocked</LeaseStatus>
                <LeaseState>available</LeaseState>
                <ServerEncrypted>true</ServerEncrypted>
            </Properties>
            <Metadata>
                <Correlation_id>D8681D0D-86D1-E91E-0016-7939CB6694D2</Correlation_id>
            </Metadata>
            <OrMetadata />
        </Blob>
```

Thanks!

**Comment by zezha-msft** [comment]
Hi @jaisonjose89m, thanks for reaching out!

That is unfortunately a known limitation caused by a combination of how the service implemented metadata and how the httpclient in Golang chooses to canonicalize HTTP headers.

The Storage service implemented metadata using HTTP headers, which are case-preserving. In other words, the casing given to the service would be sent back when you do a GET, but the metadata are not case-sensitive, so you cannot have keys with the same content but different casing.

The httpclient in Golang canonicalizes header names off the wire and does not provide any way to read the raw data instead. In the past, we've reached out to the Golang folks but haven't seen much progress. https://github.com/golang/go/issues/37834

Is it possible for you to treat metadata in a case-insensitive way? In other words, lowercase them before you read them or simply expect the canonicalization?

**Comment by jaisonjose89m** [comment]
Thanks @zezha-msft 
We will be handling the metadata in a case-insensitive way. Hence closing the incident.
