### ISSUE TITLE
No azure-sdk-for-go Support Found for Azure Automation Service with Version '2021-06-22'

### ISSUE THREAD

**Issue by balann** [Azure/azure-sdk-for-go#16826]
### Service Package Request

Unable to find the azure-sdk-for-go support for Azure Automation Service with version '2021-06-22'.
https://github.com/Azure/azure-sdk-for-go/tree/main/services/automation/mgmt
Latest version available is 2019-06-01 which lacks few properties in the SDK.

**Comment by RickWinter** [comment]
The latest service is available in beta based on the new sdk design guidelines.
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/automation/armautomation

**Comment by lirenhe** [comment]
@balann, please let us know if the above package could meet your requirement. Thanks.

**Comment by balann** [comment]
> @balann, please let us know if the above package could meet your requirement. Thanks.

@lirenhe  above package is having the latest properties, but when I tried updating the azure sdk for go(v61.1.0+incompatible) from IDE it is not showing this path inside sdk folder. I could find only the data folder inside sdk. With latest available azure sdk version (v61.2.0+incompatible)  the sdk folder itself is not there.

**Comment by ArcturusZhang** [comment]
Hi @balann sorry for the confusion here, our SDK is moving to a next generation which introduces new designed APIs under the `sdk` directory.
You could try it by using this command to install:
```
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/automation/armautomation
```
The new generation of the SDK is versioned individually one for one RP.
Since the new generation of the SDK is using a new API to authenticate, and if you still want to use our old SDK version under the `services` directory, we will also follow up with the corresponding service team to request a new release on this RP. Stay tuned.
cc @Alancere to follow up on this.

**Comment by Alancere** [comment]
Hi @balann 
released in https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/automation/mgmt/2021-06-22-preview/automation
