### ISSUE TITLE
Consider a way to prevent enum values from being at the top level of a package

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-sdk-for-go#16855]
Maybe use Jeff's enum package or @jhendrixMSFT might have an idea with generics.

**Comment by jhendrixMSFT** [comment]
Current thinking is to expose enum values as methods on the enum type.  We'd then export a constant for easy access.
```go
type IntEnum string

// IntEnumVals provides access to the predefined values of IntEnum.
const IntEnumVals = IntEnum("")

// One - This is a really long comment to see what wrapping looks like. This comment is really long and it should wrap for
// readability. Please wrap. This should wrap.
func (IntEnum) One() IntEnum { return IntEnum("1") }

// Three - three
func (IntEnum) Three() IntEnum { return IntEnum("3") }

// Two - two
func (IntEnum) Two() IntEnum { return IntEnum("2") }

// Values returns the predefined values for the IntEnum type.
func (IntEnum) Values() []IntEnum {
	return []IntEnum{
		"1",
		"3",
		"2",
	}
}

// ToPtr returns a *IntEnum pointing to the current value.
func (c IntEnum) ToPtr() *IntEnum {
	return &c
}
```
Consumers we access the values via `IntEnumVals` (how to name these constants is still being discussed).
```go
e := IntEnumVals.One()
```

**Comment by jhendrixMSFT** [comment]
Other option would be to move the const types and their values into a sub-package.  This would have to be done along-side the models.

**Comment by mikekistler** [comment]
I like the "type per enum" idea, but here are a few things to consider:

- This doesn't address plain old consts. In the azblob package, the majority (8 of 15) const values fall into this category.  So for azblob, the "type per enum" approach would only reduce the number of top-level symbols from 15 to 14.  Maybe that's okay, because in other packages we'll get big wins, but I thought it was worth mentioning.

- The large number of top level symbols is really an _intellisense_ problem.  It does not affect the docs in pkg.go.dev, because all the constants are grouped together in one index entry called "Constants" (not expandable). And converting constants to types _will_ increase the sub-index under "Types".  Again, maybe that's okay but worthing noting. And if we thought about this as an intellisense issue, maybe other solutions would pop up -- like could we do something in the Go Plugin to VSCode to hide constants by default, or always group them at the end? (Now that I typed that I kinda like that last idea.)

**Comment by richardpark-msft** [comment]
Even if we do the `function enums` could we still put them into a sub package? That would at least keep them from being at the "top level types" area, which would be nice but since we wouldn't have to have a sub-package per enum it wouldn't be too horrible.

Also, if we call the subpackage 'enum' or similar we wouldn't need to suffix each thing with enum.

**Comment by jhendrixMSFT** [comment]
We could, and if fact I have a prototype of that [here](https://github.com/jhendrixMSFT/autorest.go/tree/track2_refactor/test/autorest/extenumsgroup).  This was the next thing on the list to discuss once we landed on our enums design.

**Comment by jhendrixMSFT** [comment]
We will be keeping our present const pattern for enumerations.
