### ISSUE TITLE
Azure Arc test pass: Azure Identity For Go Client Library

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-go#17143]
Tracking issue to follow up with @zzkaii to unblock manual test pass of Azure Identity for Go Client Library running on Azure Arc:

https://github.com/Azure/azure-sdk/issues/1908
https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1047450255

> Hi,@joshfree
> When test the  Testing azure-identity in Azure Arc(in go) nd run the go test -run TestManagedIdentityCredential_AzureArc command,it display the error:
> ![image](https://user-images.githubusercontent.com/87058034/154901215-4e40edf8-31de-4269-a7f3-0d858aa4f5eb.png)
> 
> Through the investigation , I tried to use [internal](https://github.com/Azure/azure-sdk-for-go/tree/b509a3746c241234ddf116193fa9979cae667a3c/sdk/internal) v0.8.2, it works normally. But use [internal](https://github.com/Azure/azure-sdk-for-go/tree/b509a3746c241234ddf116193fa9979cae667a3c/sdk/internal) v0.8.3 and later version, it can't work. Can you provide some help on this issue?

**Comment by joshfree** [comment]
@chlowell could you please follow up with @zzkaii?

**Comment by chlowell** [comment]
@zzkaii your test run is failing because azidentity wasn't able to configure the server we use to play back test recordings. This test case doesn't use that proxy--it's an offline test using fakes--but test runs always begin with configuring the proxy. Usually, this error means the proxy isn't running. You can start it with the `docker-start-proxy.ps1` script in `eng/common/testproxy`.

All that said, why are you using `internal` 0.8.x? The latest version of azidentity [requires `internal` 0.9.1](https://github.com/Azure/azure-sdk-for-go/blob/sdk/azidentity/v0.13.1/sdk/azidentity/go.mod#L7).

**Comment by zzkaii** [comment]
@chlowell so how can i run this test, I tried to start docker-start-proxy.ps1 script in eng/common/testproxy before I run the test, but the test still can't run. The reason i mention internal 0.8.x is that this error appeared after https://github.com/Azure/azure-sdk-for-go/commit/b509a3746c241234ddf116193fa9979cae667a3c and this version use internal 0.8.2 ,my test version is the latest version.
![image](https://user-images.githubusercontent.com/87058034/156093058-a2d075d3-fd88-4d4c-bb53-7915c49596a3.png)

**Comment by chlowell** [comment]
The script does nothing when not given a parameter. Try this:
```
> ./eng/common/testproxy/docker-start-proxy.ps1 start
Attempting creation of Docker host ambitious_azsdk_test_proxy
...
```

**Comment by zzkaii** [comment]
@chlowell , Thank you for your help. The result of this test is **pass** after execute the command you provided.

**Comment by chlowell** [comment]
I'll close this then, since we're past the original problem. However, note again that the test in question is an offline one that fakes an Azure Arc environment. If you intended to run a live test on a real Arc VM, follow [these instructions](https://github.com/Azure/azure-sdk/issues/1908#issuecomment-1060972307).
