### ISSUE TITLE
Modify Upload function to take ReadSeeker instead of ReadSeekCloser

### ISSUE THREAD

**Issue by kimprice** [Azure/azure-sdk-for-go#17151]
This issue came up from the November Blob Storage UX study.

Modify Upload function to take ReadSeeker instead of ReadSeekCloser, removing the need for people to use NopCloser. Participants were unfamiliar with NopCloser.

**Comment by jhendrixMSFT** [comment]
IIRC the issue is slightly different.  The `http.Request` body takes an `io.ReadCloser`.  We (the Go SDK) added the requirement of `io.Seeker` so that we can rewind the body when we need to retry.  So we require an `io.ReadSeekCloser`.  The `io.NopCloser` in the standard library returns an `io.ReadCloser` which isn't compatible with our SDKs.  So we added our own `streaming.NopCloser` that returns an `io.ReadSeekCloser`.  So our pattern is at odds with the standard library.

We've had asks in the past to remove the requirement for an `io.Seeker`, and I believe that storage did add some APIs that just take an `io.ReadCloser` and perform the buffering themselves (i.e. "adding on" an `io.Seeker`).

**Comment by jhendrixMSFT** [comment]
For the upload stream APIs, we've settled on an `io.Reader`.  This has been deployed in `azblob@v0.5.0`
