### ISSUE TITLE
Group optional method parameters in a struct

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#1716]
Sometimes RPs add optional parameters to APIs; ideally such a change wouldn't be a breaking change (they are optional) however with the codegen we have today it is.  I propose we group all optional parameters in a struct to avoid this issue.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT whilst I can see the benefits of this approach - my only concern with this is that it makes it harder to determine that new optional fields have been added in a particular release?

> ideally such a change wouldn't be a breaking change (they are optional)

I'm assuming this would take effect in a major version of the SDK, rather than in a minor release?

Thanks :)

**Comment by jhendrixMSFT** [comment]
You have a good point.  If the consensus is that obscuring new optional params isn't worth it then we wouldn't add this functionality.  I don't know how often this happens but it did happen recently which is why I opened this issue.
Making this change is a breaking change in itself so yeah wouldn't happen outside of a major version bump.

**Comment by jhendrixMSFT** [comment]
Should include OData filter parameters.

**Comment by jhendrixMSFT** [comment]
Done in track 2.
