### ISSUE TITLE
In FindBlobsByTags API it encode space character to + which result in error from Azure

### ISSUE THREAD

**Issue by ketanpp** [Azure/azure-sdk-for-go#17421]
### Bug Report

- import path of package azblob/url_service.go
- SDK version e.g. `master`, `latest`, `18.1.0`
  

Description:

We are using FindBlobsByTags API in our application and we have an blob in Azure which have following tags
TagKey Tag1  TagValue Val 1

After executing API we are getting following error
FindBlobsByTag github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /extsrc/go_sdk/azure/0.14e/src/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. The MAC signature found in the HTTP request is not the same as any computed signature. Server used following string to sign: 'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:bcd44ba7-54e3-443e-4aa3-58c33b55bf65\nx-ms-date:Sat, 05 Mar 2022 13:49:37 GMT\nx-ms-version:2020-10-02\n/{storage_account_name}/\ncomp:blobs\nwhere:@container={container_name}AND"Tag"='Val+1''.\n

**Comment by SaurabhSharma-MSFT** [comment]
@ketanpp We are looking into it and get back to you for any additional information.

**Comment by ketanpp** [comment]
Just FYI. I have gone through code and one thing i found in  filterBlobsCreateRequest it is Encoding param for Url using Encode method as follows
req.Raw().URL.RawQuery = reqQP.Encode()
as Encode() converts space to + which making problem at Azure
I have tried to query blobs by tags using azure cli which invoke azure REST API and encode query parameter space to %20
So we can use url.PathEscape instead of Encode() method

**Comment by dave-f** [comment]
Hi, I think I'm getting this one too (our tag values also contain space)

**Comment by seanmcc-msft** [comment]
Hi @ketanpp, could you post the expression parameter you are passing into FindBlobsByTag?

**Comment by dave-f** [comment]
Hi

It's really any query with a space in.  Say for example your blob has 2 index tags, `foo=1` and `bar=2`, if you run a query with `foo='1'`  this works (as does `bar='2'`).  The problem is when you try and query `foo='1' and bar='2'`

**Comment by tsroka** [comment]
I've been trying to solve this issue with azure support as well, with no luck yet (to put it mildly, my experience with their support has been quite disappointing so far), the issue is caused by two problems:
1. Azure service does not follow it's own spec when signing the request: [microsoft spec](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#shared-key-format-for-2009-09-19-and-later)  quote from point 6: "URL-decode each query parameter name and value". However azure service when generating HMAC signature on its side does not decode '+' symbol as space, it just leaves it as it. I checked azure java sdk code and it preserves '+' sign when generating HMAC signature so java sdk works fine.
2. However encoding space as + in `where` query param would not work anyway, bc azure service will return 400 with some weird error message. Only encoding space as %20 will work (and there is no issue with HMAC signature as it works as documented). This is again problem on the azure service side, since encoding spaces as '+' is perfectly ok. Moreover go by default encodes spaces as '+' in query params, and similar problem exists in [azure sdk for rust](https://github.com/Azure/azure-sdk-for-rust)

**Comment by siminsavani-msft** [comment]
Hi @ketanpp , @dave-f , and @tsroka ! Thank you for bringing this issue to our attention and providing updates. The fix has been merged. Please let us know if the issue still persists and if you have any other feedback. Thank you again!
