### ISSUE TITLE
Make it easier for customers to figure out the API version used by a package

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17679]
### Feature Request

There's no easy way for a customer to figure out the API version in use by an SDK module.  You have to look at the implementing code (generated or otherwise) to figure it out.

Maybe this goes in the README.md for each module?

**Comment by lirenhe** [comment]
In mgmt SDK, the module may contain APIs with different apiversion, how to display that information in readme?

**Comment by jhendrixMSFT** [comment]
I agree, this has been a confusing aspect of our packages for years.  I don't know that composite packages will go away completely, but I would like to see that we don't include preview APIs with stable APIs and call the package "stable".

CC @mikekistler @JeffreyRichter

**Comment by mikekistler** [comment]
@jhendrixMSFT We absolutely should not include preview APIs with stable APIs and call the package "stable".  This is forbidden by the [general Azure SDK Guidelines](https://azure.github.io/azure-sdk/general_design.html#service-api-versions):

> DO only target generally available service API versions when releasing a stable version of the client library.

I think we should check for violations of this guideline in our PR pipeline and throw an error if there are any preview APIs included in a stable SDK.  Should we open an EngSys issue for this?

**Comment by jhendrixMSFT** [comment]
I think there needs to be more oversight and review of the README.md files in the specs repo.  For example, look at the following tag.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automation/resource-manager/readme.md#tag-package-2022-01-31

Is building an SDK from this tag considered eligible for a stable release?  Given that it includes preview APIs in its set of inputs, I would say no.  However, I have seen service teams try to claim otherwise.

**Comment by tombuildsstuff** [comment]
As a consumer of the SDK, I'd question why the API Version `2022-01-31` is calling out to different versions of the API at all?

My understanding is that the intention is to provide a single package for end-users to consume (e.g. a Go module/NuGet package etc) - containing whatever the latest and greatest of each version is - but in practice this masks which API version is being used by users. I feel like that problem would be better solved through a `latest` and `stable` package for each Service which contained an alias to the relevant Client - and being upfront with users about which API versions are being used.

Instead AutoRest could automatically process all Swaggers for the specific API Version, which whilst that may sound pedantic, would allow the Service Teams to remove these manual mappings within the markdown, remove this complexity for both the Service and SDK Team - and be upfront with users about which API Versions are being used.

**Comment by mikekistler** [comment]
Cc: @Josephine ***@***.***>

Agreed and you are not the only one raising this concern. There are efforts underway to address this.

Mike

From: Joel Hendrix ***@***.***>
Date: Monday, April 25, 2022 at 5:36 PM
To: Azure/azure-sdk-for-go ***@***.***>
Cc: Mike Kistler ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-sdk-for-go] Make it easier for customers to figure out the API version used by a package (Issue #17679)

I think there needs to be more oversight and review of the README.md files in the specs repo. For example, look at the following tag.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automation/resource-manager/readme.md#tag-package-2022-01-31<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2Fmain%2Fspecification%2Fautomation%2Fresource-manager%2Freadme.md%23tag-package-2022-01-31&data=05%7C01%7Cmikekistler%40microsoft.com%7C4c3052e7c9d648d4665d08da270c10c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637865230023718096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ygt5sojyRX9Y1saJv6O5bPMhD2u%2BDfLi5Tmtonx2n40%3D&reserved=0>

Is building an SDK from this tag considered eligible for a stable release? Given that it includes preview APIs in its set of inputs, I would say no. However, I have seen service teams try to claim otherwise.

**Comment by MostefaKamalLala** [comment]
Is it even possible to pass an APIVersion to the client?

**Comment by jhendrixMSFT** [comment]
@MostefaKamalLala not at present.  There's been some discussion on adding support for this, see https://github.com/Azure/autorest.go/issues/784 for more details (it's unclear if we'll actually implement this or not).

**Comment by MostefaKamalLala** [comment]
> @MostefaKamalLala not at present. There's been some discussion on adding support for this, see [Azure/autorest.go#784](https://github.com/Azure/autorest.go/issues/784) for more details (it's unclear if we'll actually implement this or not).

Ok, because in a sens it would respond to this current issue when you can pass the apiVersion you won't care anymore about which one is used in the package except if there is one by default.

I installed an exporter for Prometheus in my AKS which scrapes metrics from Azure. The exporter uses the azure skd which has the apiVersion 2018-01-01. There is many endpoints possible using different apiVersions and metrics namespace to acheive to result I wanted. However since, I was limited to 2018-01-01 It took me sometime to find the proper endpoint and params to get what I wanted with that apiVersion considering I'm new to Azure Metrics Rest Api. 

Referencing [Azure/autorest.go#784](https://github.com/Azure/autorest.go/issues/784)
