### ISSUE TITLE
[StorageBlob] Inconsistent Blob parameters between SDK and CLI output

### ISSUE THREAD

**Issue by diyor-uptycs** [Azure/azure-sdk-for-go#17687]
### Bug Report

- Package  - 
     - **v63.0.0**
	`storage "github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-04-01/storage"`
	`storage "github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-08-01/storage"`
     - **v63.3.0**
	`storage "github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage"`
- SDK version -  `v63.0.0`, `v63.3.0 (latest)` 
- Go version `go1.17.8 linux/amd64`

- What happened?
`BlobItemInternal` (Storage model in SDK) is missing `content`, `encryptedMetadata` and `requestServerEncrypted` fields.
However, CLI output contains those fields.
![Screen Shot 2022-04-21 at 09 41 26](https://user-images.githubusercontent.com/99381687/164401727-104c72cf-c365-4fa8-bb2e-ea3d8d926300.png)
![Screen Shot 2022-04-21 at 09 44 12](https://user-images.githubusercontent.com/99381687/164401780-5b681b05-3055-4659-8a63-ae987a973a22.png)

- What did you expect or want to happen?
**Both CLI and SDK Blob results should have the same fields and be consistent.** 
- How can we reproduce it?
**Compare blob output from CLI and SDK calls.** 

Thanks!

**Comment by lirenhe** [comment]
@tadelesh, could you take a look?  Thanks

**Comment by tadelesh** [comment]
@RickWinter I think this issue is about azblob. Could you help to triage? Thanks.

**Comment by navba-MSFT** [comment]
@diyor-uptycs Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. 
Instead of using the packages at [github.com/Azure/azure-sdk-for-go/services/storage](https://github.com/Azure/azure-sdk-for-go/tree/main/services/storage) which is to manage storage accounts, Could you please use the below package which is for the data plane resources: containers, blobs and check if that helps ? Awaiting your reply.

Service | Import Path/Repo
-- | --
Storage - Blobs | [github.com/Azure/azure-sdk-for-go/sdk/storage/azblob](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob)

Refer the available BlobProperties [here](https://github.com/Azure/azure-sdk-for-go/blob/241bdb849ce431e1a5e398a5649cde93149ee374/storage/blob.go#L86).

**Comment by diyor-uptycs** [comment]
@navba-MSFT Thank you for your reply. 
We are already using [azblob](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob) package. The only problem is that BlobProperties struct doesn't contain `content`, `encryptedMetadata` and `requestServerEncrypted` fields. CLI output does have those fields.

**Comment by mohsha-msft** [comment]
azblob​ SDK is currently using service version 2020-10-02. I was looking at the fields you pointed out and we do publish these fields as well with name specified by the swagger definition here: [azure-rest-api-specs/blob.json at main · [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/data-plane/Microsoft.BlobStorage/preview/2020-10-02/blob.json#L9576). All SDKs follow the same definition so should have the same name with minor differences because of naming conventions.

You can check out the output fields here:
[azblob package](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#BlobPropertiesInternal)

encryptedMetadata -> Metadata
requestServerEncrypted -> ServerEncrypted
content -> ContentLength, ContentType

**Comment by navba-MSFT** [comment]
Thanks @mohsha-msft.
@diyor-uptycs Could you please let me know if you had a chance to look at the above comment?  Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@diyor-uptycs Please let us know if you have any pending questions on this. Awaiting your reply.

**Comment by diyor-uptycs** [comment]
Thank you @mohsha-msft and @navba-MSFT for the help.

@mohsha-msft 's explanation helped us a lot

**Comment by navba-MSFT** [comment]
@diyor-uptycs Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
