### ISSUE TITLE
App Config: enable live test in CI

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-go#17789]
App Config does have the live test, but it is not running in CI. Enable it.

**Comment by RickWinter** [comment]
@benbp Should this be enabled by default for anyone starting from the template?

**Comment by benbp** [comment]
@RickWinter @antkmsft app config does appear to have active live tests running: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1541229&view=results

The live tests only show up on the `internal` devops project, not the `public` one which is the default for PR builds. This is because we don't want to enable any random person to have access to our resource provisioning via the default PR hooks.

**Comment by benbp** [comment]
@RickWinter I think it depends on whether you want it to be a pre-requisite for onboarding a new SDK? If people are copying their templates off core, then it won't have live tests enabled by default. It's also a bit more work to get the live tests working, so I don't know if it's optimal to keep it as a separate change for onboarding or not.

**Comment by antkmsft** [comment]
Thank you Ben! If the test is running, then the situation is better than I thought. I think it may make sense to not run live tests for PRs. Maybe we should use recorded responses when running for PRs.

**Comment by RickWinter** [comment]
@antkmsft Can you work with Ben to ensure that we are using recorded tests in the public CI and live tests in the internal CI.

**Comment by benbp** [comment]
@antkmsft It's not 100% clear to me in what mode the tests are running. The live test pipeline is running but I'm not sure whether the tests themselves are referencing the external resources, given that the runtime is the same as the CI pipeline. Please reach out to me when you get the chance and I can help advise.

**Comment by antkmsft** [comment]
@antkmsft, note to self: boost code coverage to 90
