### ISSUE TITLE
Usage of embedded, unexported types, makes for poor docs

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17801]
For example, the implementation of [`BlobGetPropertiesResponse`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/zm_blob_client_util.go#L215-L220) uses an anonymously embedded type that's not exported.  Unfortunately this breaks the documentation experience.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#BlobGetPropertiesResponse

As you can see, none of the exported fields in `blobClientGetPropertiesResponse` show up in the docs.

This pattern needs to be removed.

**Comment by s8mathur** [comment]
I am a Go developer attempting to find the last modified timestamp of a file blob, and due to this issue, the `LastModified` value or ANY file metadata for that matter can't be accessed: 
https://github.com/Azure/azure-sdk-for-go/blob/8dce4d522a207952d9f0ac2b56b61b9b595b67b6/sdk/storage/azblob/zz_generated_response_types.go#L712

Thanks much @jhendrixMSFT !

**Comment by jhendrixMSFT** [comment]
Fixed in upcoming `azblob@v0.5.0`
