### ISSUE TITLE
Unable to get READ-ONLY fields of struct in Azure-go-sdk

### ISSUE THREAD

**Issue by shivamnutanix** [Azure/azure-sdk-for-go#18207]
- What happened?
I am using the latest azure-go-SDK for compute `github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2021-12-01/compute` earlier when we were using +40.000 version we are getting the required fields but when we shifted to latest SDK , i am unable to get all the READ-ONLY fields because of the custom marshaller [here](https://github.com/Azure/azure-sdk-for-go/blob/cc8c0a5a1ddd9ead333967825522a1e883c09ea9/services/compute/mgmt/2019-12-01/compute/models.go#L8948)
- What did you expect or want to happen?
I want to know how we can have to get the read-only fields in response from azure as those are expected by us for some validation and listing.

**Comment by jhendrixMSFT** [comment]
Unfortunately, this is a known limitation in our legacy SDK.  The good news is that we've fixed this in our newest SDKs.  To replace the `compute` package, you'd want to use the [`armcompute`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute) module instead.

**Comment by jhendrixMSFT** [comment]
The change was intentional as there are some services that will reject a request if you attempt to round-trip a data-structure that contains populated read-only fields, so we remove and read-only content from the payload (more services will work like this over time).

Unfortunately, we underestimated reliance on the JSON marshaller outside of the SDK which is why we took a different approach in our new SDKs (this is not the first time this issue has been reported).

Note that this legacy SDK (i.e. the contents under the `/services` directory) has shifted to maintenance mode and will go out of support on March 31, 2023 (more info on that [here](https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/)).  We've put together a [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md) to help with the transition.
