### ISSUE TITLE
Prevent unbounded growth in changelogs

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#18210]
Since the CHANGELOG.md files aren't pruned from a module we need to ensure that their growth isn't unbounded.  E.g. for NRP the changelog is currently ~1.5MB which is much larger than the combined source files.  While this is a bit of an outlier, we must ensure the files aren't simply allowed to grow.

**Comment by tadelesh** [comment]
The changelog is generated by tools, and it seems other mgmt. SDK do the same way. The problem is there existing too many legacy changelogs caused by code generator change. I suggest removing all the changelogs before GA and set the changelog of first GA version similar with [JS SDK](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/compute/arm-compute/CHANGELOG.md#1700-2021-12-07).
