### ISSUE TITLE
[azservicebus] ASB client stopped receiving messages

### ISSUE THREAD

**Issue by VirajSalaka** [Azure/azure-sdk-for-go#18480]
### Bug Report

pkg: github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus

- SDK version 0.4.0
  
- GO version 1.18.1

- What happened?

ASB client stopped receiving messages forever in its lifetime.

Since it same as a previous issue reported by me, I have added a comment. https://github.com/Azure/azure-sdk-for-go/issues/17408#issuecomment-1166454090

- What did you expect or want to happen?

ASB client should be able to receive messages without any issue as long as the subscription has messages queued. 

- How can we reproduce it?

In our scenario, the message was not completed for like ~10-15 minutes as the application took a bit of time. (For each time, we observed the scenario, this has been a common pattern. But we could not reproduce it)

- Anything we should know about your environment.
Our service is running on AKS

Thanks!

P.S.
I guess we could reopen https://github.com/Azure/azure-sdk-for-go/issues/17408, since it looks like the same issue.

**Comment by richardpark-msft** [comment]
From your log, I think you're seeing some of the fallout from this particular bug (#18323), where we weren't properly cleaning up our network connection. This was fixed in v1.0.1, so upgrading would be your easiest course, especially since this package has released its official GA.

There were two other fixes that you will get that could also be part of this problem:
- #17893 - fixes an issue where we could potentially not return messages when we had them stored in an internal cache
- #18291 - passes the associated-link-name to more calls, which can help extend link lifetime.

I'd recommend upgrading to this latest version. We're also close to releasing the next patch release (v1.0.2) next week but the fixes I've mentioned are in v1.0.1.
