### ISSUE TITLE
[Blob Storage] InvalidBlockList when concurrently writing to the same key

### ISSUE THREAD

**Issue by marwan-at-work** [Azure/azure-sdk-for-go#18490]
This issue is copied over from https://github.com/Azure/azure-storage-blob-go/issues/263

### Which version of the SDK was used?
v0.11.0

### Which platform are you using? (ex: Windows, Linux, Debian)
Darwin

### What problem was encountered?
Given the below code snippet (using gocloud.dev, which uses this library):

```golang
azbucket, err := azureblob.OpenBucket(ctx, pipeline, accountName, containerName, &azureblob.Options{Credential: credential})

var wg sync.WaitGroup
wg.Add(3)
for i := 0; i < 3; i++ {
	go func() {
		defer wg.Done()
		err := azbucket.WriteAll(ctx, "conctest/data", []byte("hello"), &blob.WriterOptions{})
		fmt.Println("WROTE DATA", err)
	}()
}
wg.Wait()
```

Only 1 of the 3 writes succeeds while the other 1 or 2 will almost certainly return a 400 error stating an InvalidBlockList. 

However, when reading the following docs:  https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet

It explicitly says that: 

> If you don't explicitly specify a strategy, then by default the last writer wins.

Would love to confirm if this SDK specifies a non-default strategy and if not, I believe this would be then categorized as a bug either on the SDK or the storage API side? 

Thanks!

### How can we reproduce the problem in the simplest way?
With the snippet provided above. 

### Have you found a mitigation/solution?
I am considering simply ignoring all InvalidBlockList errors, but I want to make sure that that is an appropriate mitigation.

**Comment by zezha-msft** [comment]
Sorry for the delayed reply @marwan-at-work.

I took at look and this appears to be an implementation choice by the gocloud.dev package: it uses the [UploadStreamToBlockBlob](https://github.com/google/go-cloud/blob/60d79299da9fb31d6bd022ae834b6766f45b55b1/blob/azureblob/azureblob.go#L1103) method which takes in a reader, stages blocks as it reads from the reader, and then commit the block list when the reader is closed. 

To clarify, the committing of a block list erases all other uncommitted blocks. In other words, if you have 3 routines all staging blocks at the same time, only one can succeed at committing its block and by the nature of the API used, the other 2 routines will fail because the blocks they are trying to commit no longer exists.

If you wanted the "last writer wins" kind of behavior, I would suggest that you invoke the azblob package directly, using the [Upload call](https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob#BlockBlobURL.Upload), which maps to the [Put Blob API](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks) and accommodates up to 5 GiB.
