### ISSUE TITLE
[azservicebus] Durable subscription with multiple consumers not working

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [Azure/azure-sdk-for-go#18696]
### Bug Report
Trying to work with durable subscriptions, but the subscription is not providing all messages, observing a severe message loss.
(FYI there are no filters applied to this subscription)

- SDK version - 	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v1.0.1
- output of `go version` - ```go version go1.18.2 darwin/amd64```

## What happened?
Not all messages were received by consumers

There are 2 containers of the same component that consume messages from the specific topic using the same subscription name. 
### Issue 1   
Sometimes only 1 component receives some message. Other component doesn't receive any message. 

### Issue 2
Observed the following behavior,
1. Send a message(Message A) to the topic
2. No consumer receives any message
3. Send a message(Message B) to the same topic
4. A consumer receives message A now. But haven't received massage B

### Issue 3 
Consumers receive only "some" messages. Other messages were lost forever.

### Issue 4
1. Start consumer_A
2. Send a message(Message_A) to the topic
3. Consumer_A received message_A
4. Start consumer_B
6. Send multiple messages from time to time
7. Consumer_A not receiving any messages now

## What did you expect or want to happen?
All messages were to be received by consumers.
If one consumer failed to [complete](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus#Receiver.CompleteMessage) the message, another consumer should receive it and complete it. 

## How can we reproduce it?
- Create a durable subscription for a topic
- Create and run multiple consumers with the above subscription. 
- Send and receive messages on this topic.
```
     receiver, _ = client.NewReceiverForSubscription(topicName, subscriptionName, nil)
     messages, err := receiver.ReceiveMessages(ctx, 10, nil)
```

**Comment by richardpark-msft** [comment]
Hi @AmaliMatharaarachchi,

> Issue 1
> Sometimes only 1 component receives some message. Other component doesn't receive any message.


All load balancing is handled by the service here. How many messages are you asking for with each ReceiveMessages() call? Is it 10, as in your example? Do you typically get all 10 messages? If not, you might want to lower it so you don't have a single consumer greedily consuming all available messages.

With regards to the rest of the issues we should try two things:
- Install the latest release of azservicebus. We just released v1.1.0 of azservicebus. It does a better job of maintaining a link, and doesn't rely on drain, both of which were occasionally causing messages to be excessively locked. Messages would not be lost forever. They would still be delivered after the lock timeout for the message expired. 

  Since this would also increment the messages delivery count it's possible the messages were moved into the dead letter queue, as configured by the subscription's max delivery count. 
- Enable debug logging so we can see what's going on in the internals of the library: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/README.md#logging
