### ISSUE TITLE
Azure blob container - missing support for ETags in Set Container Metadata API

### ISSUE THREAD

**Issue by sameershivle** [Azure/azure-sdk-for-go#18770]
### Feature Request

Current azure go sdk implementation of Set Container Metadata (https://docs.microsoft.com/rest/api/storageservices/set-container-metadata) does not have support for "IfMatch" parameter.
The Rest API documentation for azure (https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations) says  that there is support for conditional headers "If-Modified-Since", "If-Unmodified-Since", "If-Match", and "If-None-Match".
However, in the generated file zz_generated_container_client.go I see support only for the header "If-Modified-Since" parameter but the support for header "If-Match" is missing.

#### Suggestion

Can the go sdk generator be modified to include conditional headers for set container metadata API

**Comment by zezha-msft** [comment]
Thanks @sameershivle for reaching out.

To clarify, if you read further in this doc https://learn.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations#Subheading2:



Set Container Metadata | Write | If-Modified-Since
-- | -- | --

So If-Modified-Since is the only one supported for the Set Container Metadata API.
