### ISSUE TITLE
Chicken-and-egg problem for `Link verification check`

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-for-go#18801]
When we release packages with a major version pump and major version is larger than v1, we will meet a chicken-and-egg problem for `Link verification check`. In the `readme.md` file, there is a package reference link which need to have version suffix in the URL. When package is not released, the URL is unreachable which result in blocking the release pipeline. The approach that releasing without version suffix at first and add them after release is not workable because it will leave a wrong doc in the `pkg.go.dev`. One solution is to remove the check in release pipeline. Open for better solution. cc @jhendrixMSFT , @ArcturusZhang , @lirenhe

**Comment by RickWinter** [comment]
I do not want to remove the check entirely.  Perhaps we want a special flag to bypass when doing major version updates?

Note: I would hope this is a rare occurrence :)

**Comment by tadelesh** [comment]
> I do not want to remove the check entirely. Perhaps we want a special flag to bypass when doing major version updates?
> 
> Note: I would hope this is a rare occurrence :)

Agree with adding some special logic for the first onboard of major version.

**Comment by weshaggard** [comment]
Our general link guidance can be found at https://aka.ms/azsdk/guideline/links. In general, we don't want to release any links that we think will be valid in the future because there is never any guarantee, and it is always better to have no link then a broken link. We should ask whether or not the links are needed and if so perhaps have them commented out on first release and then add them in in the next release.

>Note: I would hope this is a rare occurrence :)

A second major might be rare but this problem also exists for the first release of a new library as well. I would expect us to handle both the same way.

**Comment by tadelesh** [comment]
The broken link for Go is the reference doc badge in the package readme file and the link is linked with the package version. Also, this readme file will be showed in `pkg.go.dev` site. As you suggested, we could comment it before any major version first release and add back after release. But it will be an extra manual work out of our toolchain.
