### ISSUE TITLE
[Feature Request] Subscription Management

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#1904]
👋 

This is a feature request for the Service Team more than an SDK feature, but I digress - please let me know if this should be relocated to the Swagger repo?

It's now possible [to create Subscriptions through the API](https://docs.microsoft.com/en-us/rest/api/resources/subscriptionfactory) (I'm assuming, but haven't checked, that there's an SDK for this) - but there's no means of deleting them. I could see this being useful to run programatically - as such are there plans to add support for a Delete API for subscriptions?

From what I can see equivalent functionality exists in other clouds (e.g. [Google has Projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects)) - so it seems like it could be useful; as a user I'd expect the delete call to fail if the subscription was locked, or contained resources to prevent accidental deletion.

Thanks!

**Comment by justinbarias** [comment]
there's this now: https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/resources/mgmt/2018-03-01-preview/management/subscriptions.go

There are Create() and Delete() methods - have you tried these out?

**Comment by hbuckle** [comment]
That's for associating or removing subscriptions from management groups. @tombuildsstuff is correct, the subscription factory API doesn't currently offer a delete method, possibly because Azure itself doesn't offer the option to delete subscriptions, only to cancel them.
In addition the API to get subscriptions doesn't return the same information required to create them, so implementing this in Terraform is pretty much impossible right now.

**Comment by vladbarosan** [comment]
@tombuildsstuff yes can we move this to the specs repo?  We are trying to keep here SDK specific asks.  You can reference this issue there.
