### ISSUE TITLE
Update ContainerService.managedClusters version

### ISSUE THREAD

**Issue by jingai-db** [Azure/azure-sdk-for-go#19197]
### Service Package Request

Currently, the latest ContainerService.managedClusters API (v1) is dated as [2022-03-01](https://github.com/Azure/azure-sdk-for-go/tree/main/services/containerservice/mgmt/2022-03-01/containerservice). In that case, the upstream client (e.g., CAPZ) could not use the feature (e.g., BYO CNI) recently GAed in AKS, where the API spec with the feature has been updated from [2022-06-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-06-01) and onwards.

Therefore, the request is to update the ContainerService.managedClusters version to align with the Azure API spec with 2022-06-01 version or any version onwards.

**Comment by ArcturusZhang** [comment]
Hi @jingai-db thanks for this issue.
Your issue was raised against our "old generation" of the SDK which has been announced as deprecated recently.
Could you have a try on our new generation of the SDK? You could find the source code here: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/containerservice/armcontainerservice
and install it using this command:
```
go get github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice@latest
```
and it is using api-version `2022-08-02-preview`.

**Comment by jingai-db** [comment]
@ArcturusZhang Thanks for the update! I am aware that there are 2 generations of SDKs. However, as the v1 client is used by https://github.com/kubernetes-sigs/cluster-api-provider-azure, I believe it would be straightforward to upgrade the v1 to get the feature working; and then upgrade the client to use SDK v2 as a round of cleanup. Please advise. Thanks!

**Comment by jingai-db** [comment]
I will close the issue as it is tracked by https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2670
