### ISSUE TITLE
[azappconfig] Issue with `getSettings` method's `OnlyIfChanged ` parameter

### ISSUE THREAD

**Issue by pravinpushkar** [Azure/azure-sdk-for-go#19297]
### Bug Report

Creating a different issue get more visibility, earlier I have mentioned this issue as part of a different issue here - https://github.com/Azure/azure-sdk-for-go/issues/19081

According to the document, we can set this parameter to true and response will come only if the value gets modified. I have the below code for `getSettings` - 

```
sentinelKeyResponse, err := r.client.GetSetting(
		ctx,
		"key",
		&azappconfig.GetSettingOptions{
			OnlyIfChanged: true,
			Label:         r.getLabelFromMetadata(req.Metadata),
		},
	)
```
But I always get the response irrespective of value has changed or not. I can see the *sentinelKeyResponse.Etag and can see its value.
My understanding is if the value gets updated, it should give the response only 1st time when accessed after that it should given some error response code.

Kindly share your thoughts and please let me know if I am supposed to use it differently. Thanks

**Comment by pravinpushkar** [comment]
@antkmsft Any help on this would really be awesome. Thanks

**Comment by jhendrixMSFT** [comment]
It appears that the API is incomplete. Since the `Setting` with the `ETag` isn't passed to the API, the condition can never be evaluated (compare this to the [.NET implementation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs#L664)).

It will likely require a breaking change to fix this. I'll bring this up at our next scrum.

**Comment by antkmsft** [comment]
Hi @pravinpushkar, I made a fix. With it, you assign `ETag` from the configuration setting that you used to get earlier to the `OnlyIfChanged` options field, and you get an error in case the setting did not change since the last time you read it:
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azappconfig/client_test.go#L52-L54

**Comment by pravinpushkar** [comment]
@antkmsft Thanks for the fix. I will take a look.
