### ISSUE TITLE
[Container Instance] ListCapabilities API hang forever

### ISSUE THREAD

**Issue by helayoty** [Azure/azure-sdk-for-go#19338]
### Bug Report

- Package path: https://github.com/Azure/azure-sdk-for-go/blob/main/services/containerinstance/mgmt/2021-10-01/containerinstance/location.go
- Import path of the package :  `.../services/compute/mgmt/2018-06-01/compute`
- SDK version: `v63.0.0+incompatible`
- `go version`: `go version go1.18.1 darwin/amd64`

- What happened?

I was trying to list the capabilities for a specific region in the `container instance` service. The code enters an infinite loop at [this](https://github.com/Azure/azure-sdk-for-go/blob/main/services/containerinstance/mgmt/2021-10-01/containerinstance/location.go#L177) line.
- What did you expect or want to happen?
- How can we reproduce it?
  - When trying to list the capabilities using the managed identity. 
  
- Anything we should know about your environment.
  - AKS cluster
  - Running virtual node
  - Using MI to authenticate.

**Comment by lirenhe** [comment]
The library you are using is our old SDK that we are deprecating. The old SDK is relying on some deprecated packages like ADAL and our new SDKs are more secure and comply with the latest SDK guidelines. You can use this migration guidance: [azure-sdk-for-go/MIGRATION_GUIDE.md at main · Azure/azure-sdk-for-go (github.com)](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md) to start your migration now.

**Comment by lirenhe** [comment]
Could you try to use this libarary?  https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerinstance/armcontainerinstance/v2

**Comment by helayoty** [comment]
> Could you try to use this libarary? https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerinstance/armcontainerinstance/v2

@lirenhe we can't migrate to the new SDK as it doesn't support a way to get a preparer and send a HTTP request which we need in our case.

**Comment by lirenhe** [comment]
@tadelesh, could you help on this and can we have a workaround?

**Comment by tadelesh** [comment]
> > Could you try to use this libarary? https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerinstance/armcontainerinstance/v2
> 
> @lirenhe Renhe Li FTE we can't migrate to the new SDK as it doesn't support an exposed method for a preparer and send an HTTP request which we need in our case.

@helayoty Thanks for reach out. We have already deprecated the old SDK and I'm afraid no further version will be released if it supposed to be a bug. I think there is two way we could help:
1. Could you please paste the detailed logs with your request that we could figure out why it enters an infinite loop? (refer [this](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/previous-versions-quickstart.md#built-in-basic-requestresponse-logging))
2. Could you help to explain `an exposed method for a preparer and send an HTTP request` that block your migration? We are very glad to help with your migration.

**Comment by helayoty** [comment]
@tadelesh 
1. I can see `502` error when I debug but the code never returns to be able to collect the logs. I put [this](https://github.com/helayoty/list-capabilities-issue) code together to reproduce the issue by only calling the API.

2. We had to wrap the `ContainerGroup` struct to be able to send an extra property that is not available via SDK for now. ACI team is working to add it later.

**Comment by helayoty** [comment]
@tadelesh  I have put together a code sample to reproduce the issue [here](https://github.com/helayoty/list-capabilities-issue)

**Comment by tadelesh** [comment]
@helayoty Thanks for providing detailed code. It seems the credential process fall into infinite loop. Have you set `MSI_ENDPOINT` and `MSI_SECRET` environment variable when using MSI? What kind of MSI type you are using?

**Comment by jhendrixMSFT** [comment]
I took a look at the repro.  While the hang isn't an infinite loop, it's a Really Long Time.  The problem here is that we have compound retries; one for the API `ListCapabilities` and one for requesting a token from the managed identity provider.

In [`retryForIMDS`](https://github.com/Azure/go-autorest/blob/main/autorest/adal/token.go#L1167-L1231), the code will retry when it fails to obtain a token, sleeping for up to 60 seconds between attempts.  If the authentication fails, the error is propagated to its callers which ends up in [`doRetryForStatusCodesImpl`](https://github.com/Azure/go-autorest/blob/main/autorest/sender.go#L319-L356).  This will also sleep for some time and then retry the request again.  Eventually, this will hit its retry cap and exit, it just takes a really long time.

This is just running on my dev box where there is no managed identity provider.  However, I'm assuming that you're seeing some amount of failures when running on an AKS node which is causing the delays?
