### ISSUE TITLE
newCredentialUnavailableError: "no default identity is assigned to this resource" although it's available 

### ISSUE THREAD

**Issue by realDeveloper45** [Azure/azure-sdk-for-go#19432]
import
github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.13.2

output of go version
go version go1.18.3 linux/amd64

Im facing  "no default identity is assigned to this resource"  intermittent error and request gets canceled. I have user identity set to VMs, no system identity.  It works most of the times but in some cases fails and reports error. How to stop this intermittent error 

Error

``` failed to acquire a token.\n
Attempted credentials: AZURE_TENANT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\t
AzureCLICredential: Azure CLI not found on path
```

**Comment by jhendrixMSFT** [comment]
This is a pretty old, prerelease version.  Can you please try the latest version `v1.1.0` to see if the issue has been resolved?

**Comment by chlowell** [comment]
This error indicates the token endpoint returned a 400 response. The fix depends on the reason for that, and the first step is to get the error message from the response body. The simplest way is to log it:
```go
import azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"

// print IMDS error responses to stdout
azlog.SetListener(func(event azlog.Event, s string) {
    if _, after, found := strings.Cut(s, "http://169.254.169.254"); found && strings.Contains(after, "400 Bad Request") {
        fmt.Println(s)
    }
})
opts := ManagedIdentityCredentialOptions{
    ClientOptions: policy.ClientOptions{
        Logging: policy.LogOptions{
            // Include the body of requests and responses in logs. Note that these can include
            // authentication secrets, so ensure your logs are secure and consider carefully
            // before enabling this in production.
            IncludeBody: true,
        },
    },
}
cred, err := NewManagedIdentityCredential(&opts)
```

**Comment by realDeveloper45** [comment]
@chlowell @jhendrixMSFT Thanks for the suggestion

We have enabled logs in SDK and it looks something like this

`Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request`

what does that mean? how can we resolve this issue? Is it something do with the az identity deployment or configurations?

**Comment by chlowell** [comment]
The error means the VM has no system assigned identity and at least 2 user assigned identities. That makes sense when you want to enable applications on the VM to authenticate different identities. However, with this configuration, each token request must specify the identity for which you want a token. The system won't choose one for you because doing so would violate security boundaries and cause hard to debug failures. So, you just need to specify an identity for the `azidentity` credential. The package documentation has an example showing [how to do this for ManagedIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#example-NewManagedIdentityCredential-UserAssigned) with an identity's client or resource ID. If you're using `DefaultAzureCredential`, set the environment variable `AZURE_CLIENT_ID` with an identity's client ID.

**Comment by realDeveloper45** [comment]
@chlowell Thanks for prompt reply. Issue is intermittent and not consistent, most of the time it will fail when horizontal auto-scaling tried to create new pods. Example PodStartTime _11/10/2022, 8:25:10.000 AM_ and issue reporting time _11/10/2022, 8:34:10.000 AM_

We are using podidenitty labels on our pods,  will it make any difference.?

We have 3 user identities to our VMSS. Is it possible to resolve this without using the clientId for ManagedIdentities for SDK?

**Comment by chlowell** [comment]
Ah, I thought you were running applications directly on a VM. Pod Identity is a different story. Looks like you're hitting a known issue with Pod Identity ([described here](https://github.com/Azure/aad-pod-identity/issues/1212)). The gist is, pods are attempting to authenticate before Pod Identity is ready to intercept their requests and therefore hit the token endpoint on the underlying VM, which has multiple assigned identities and knows nothing about pod metadata, so it demands a specific client/resource ID. This should be a transient failure because Pod Identity just needs more time to get ready. You could even use an init container to determine when Pod Identity is ready but that's a hack. It would be best to prevent this entirely because if the underlying VM's configuration were such that it didn't require a client/resource ID, a pod could authenticate with different privileges than you intend.

To prevent this, I think you would have to ensure the cluster doesn't schedule these pods on a node until NMI, the Pod Identity component that intercepts requests, is ready on that node. The docs I linked above state Kubernetes provides no way to do this. I suppose it's worth some investigation anyway in case things have changed since that document's last update. I'm afraid I don't have any advice past that--the SDK can't avoid these errors, and I don't know enough about Kubernetes to sketch a good solution.
