### ISSUE TITLE
Is it mandatory to pass timespan in query

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-sdk-for-go#19543]
Hello,

While running query using [azquery](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/monitor/azquery#logs-query) is it mandatory to pass timespan.

Let say if we pass timespan with this type of query then does it impact the output. Or, it won't make any difference

```
let startTimestamp = ago(240m);
    let deployment= "test-deployment";
    KubePodInventory
    | where TimeGenerated > startTimestamp and Name has deployment
    | project ContainerID, PodName=Name
    | distinct ContainerID, PodName
    | join(
        ContainerLog
        | where TimeGenerated > startTimestamp) on ContainerID
        |summarize Count=count()

**Comment by smartaquarius10** [comment]
@gracewilcox Hey, could you please help in this.. Thanks :)

**Comment by gracewilcox** [comment]
The API does not require you to pass in a timespan, but it is strongly recommended. If you do not specify the timespan, it will default to querying over the entire dataset which can be quite costly in some cases.
Instead of using the timespan parameter, you can also specify the time in the Kusto query like you did in your example. So, in your case, you can just use that Kusto query and not use the timespan parameter.

**Comment by smartaquarius10** [comment]
@gracewilcox, Got it.. Thank you so much.. One small query, I can observe that the total row count coming via azquery versus checking in portal.azure is a little different. Difference increases with the count of rows. 

For eg. when row count in azure portal is 410.. Azquery was giving 406.. 
When row count in azure portal is 4880.. Azquery was showing 4862.. 

Is there any reason.. Means we can say this as the precision error but is it expected?

**Comment by gracewilcox** [comment]
Hi @smartaquarius10 ! I first recommend enabling logging. Viewing the request and response will really help to narrow down the issue. Instructions for that are [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/monitor/azquery/TROUBLESHOOTING.md#logging). I also recommend viewing your network traffic in the browser to see the query string you sent to the service from the portal. Having the query string from both the portal and library can help see where the issue could be.

Also, could this be related to the timespan you are using for your query? If you ran the queries sequentially then some of the data might have fallen out of the 240 minute time stamp you set in the Kusto query.

**Comment by smartaquarius10** [comment]
@gracewilcox, Sure but. how to capture query string with az query library. This is the code I wrote to get data

**Comment by gracewilcox** [comment]
When you say query string, are you referring to the value of the query variable in your code snippet or something else?
 
To clarify my last comment, it might be a good idea to compare the HTTP request and response between when you query in the portal vs when you query in your code to see if there are differences.
 
But, I suspect that the issue lies in the time you set in your query. You are asking for `KubePodInventory`s that are older than 240 minutes. As time goes on, the number would increase. So, if you ran the query in the portal after you ran it in your code, you may get more rows.
 
Do you get the same results from earlier if you rerun the same queries in your code and in the portal?

**Comment by smartaquarius10** [comment]
@gracewilcox, Hey, I'm so sorry for replying late. I totally missed this. Yes, the buffer is very less, and I can understand that it is because of precision difference which is coming because every second logs are generating. 

Will observe the behavior in production environment and if found any issue will contact you. Thank you so much for immediate help and support. Have a great day ahead :)
