### ISSUE TITLE
Get minimum TLS version of eventhub.namespace

### ISSUE THREAD

**Issue by rachelschifter-wiz** [Azure/azure-sdk-for-go#19625]

**Comment by lirenhe** [comment]
@ArcturusZhang, could you help to check whether we already have this capabiliity from the API definition?

If not, seems this is request for service team.

**Comment by rachelschifter-wiz** [comment]
Hi, can you help us please?

**Comment by ArcturusZhang** [comment]
HI @rachelschifter-wiz our v1.0.0 of `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub` module (short as "eventhub module") does not support get or set minimum tls version because this new property is introduced in a preview api-version.
We already released a new beta version for the eventhub module `v1.1.0-beta.1` and it supports the minimum tls version. You could check its references here: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/eventhub/armeventhub@v1.1.0-beta.1#EHNamespaceProperties
