### ISSUE TITLE
CosmosDB - Request for a ListCollections method

### ISSUE THREAD

**Issue by SebSa** [Azure/azure-sdk-for-go#19749]
### Feature Request

Please could a ListCollections method ([API reference](https://learn.microsoft.com/en-us/rest/api/cosmos-db/list-collections) be added to the type [DatabaseClient](https://github.com/Azure/azure-sdk-for-go/blob/794c96c44d1673be8884240693781678c030ef86/sdk/data/azcosmos/cosmos_database.go#L12-L19) for CosmosDB?

Currently it appears that all the pieces are in place to achieve this but it's not yet been added.

If not possible, would anybody know of an elegant workaround to be able to make this API request to get the list of collections, preferably using [the same connection string based authentication that the the Cosmos SDK uses](https://github.com/Azure/azure-sdk-for-go/blob/794c96c44d1673be8884240693781678c030ef86/sdk/data/azcosmos/cosmos_client.go#L56-L87)

**Comment by ealsur** [comment]
@SebSa Thanks for the detailed clarification of the scenario.

Bulk operations make perfect sense, what I am not sure I fully understand (I might be completely missing the picture) is on which scenario you would dynamically perform these operations in a variable list of Collections. If your application needs to perform bulk operations (let's say, delete 10K items or create 100K items), would the code list all collections and run the operation across all existing collections?

The responsibility separation between Management SDK and Cosmos DB SDK is that the first one is geared towards Management Plane operations (managing databases, collections, accounts), while the second one is geared towards Data Plane operations (performing item level operations). While the second one does contain basic CRUD support for databases and collections, these operations are limited, if you are using AAD/MSI authentication, they might not work (reference https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#permission-model), hence the suggestion to use the Management SDKs if what you need is to handle or work with databases and collections, because that will work with AAD/MSI.

**Comment by ealsur** [comment]
@SebSa Got it. So the user will see a list of databases, then selects one. Once one is selected, then see a list of collections, and select one.

Once one is selected, perform the bulk operations.

In that case, then you could have the responsibilities split. The Management SDK can be responsible of obtaining the databases/collections for the UI (or whatever input method is offered), and once a collection is selected (you have the db and collection names), perform the bulk operations using the Data Plane SDKs?

**Comment by ealsur** [comment]
> is that going to be a problem do you think?

The Management SDK let's you create a client with account keys: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/data/azcosmos#create-cosmos-db-client

**Comment by ealsur** [comment]
Will be released as part of 0.3.3 tomorrow
