### ISSUE TITLE
Telemetry policy should not be setting `User-Agent` if it is already set

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-go#19890]
See https://github.com/Azure/azure-sdk-for-cpp/issues/4297

**Comment by jhendrixMSFT** [comment]
`User-Agent` is always set, so we can't simply predicate it on set/unset.  The current policy will preserve any existing UA content, appending its content to the end.

**Comment by jhendrixMSFT** [comment]
I don't think there's anything we can change here.

CC @JeffreyRichter

**Comment by JeffreyRichter** [comment]
The purpose of the telemetry policy is to set the user-agent.
Why would it already be set? What piece of code is setting it?

**Comment by jhendrixMSFT** [comment]
Typically, it shouldn't be set.  Two cases I can think of, and these are probably highly unlikely, is if a swagger defines this (would we reject such authoring?) or if it's been explicitly added by an SDK when creating the raw HTTP request (as an aside, using the raw client in `azcore`, customers could also go down this path).

Where this gets interesting is our [`WithHTTPHeader`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/runtime/policy_http_header.go#L37) functionality.  Today, the policy that supports `WithHTTPHeader` is injected in the pipeline after the telemetry policy.  This means two things.

- The `User-Agent` header should always be unpopulated (sans the obscure cases I mentioned earlier)
- The `WithHTTPHeader` option can be used to erase any UA content set by the telemetry policy

All this said, given the above, I don't feel super strong about having the telemetry policy preserve an existing UA header.  So if there's consensus, I can change it to no longer do so.  It's also possible that this behavior was part of our early design and is no longer applicable.

**Comment by JeffreyRichter** [comment]
I Agree that a swagger should not attempt to specific user-agent. If we saw this in a swagger, the API Stewardship Board would push back on it hard as it prevents the SDKs from delivering telemetry. So, I think it's safe to say we would not allow this in swagger. 

Customers can always use raw HTTP to talk to Azure and then they can set the UA to whatever they want. But, if a customer is using an SDK, then we (the SDK) own the UA string and we set it to whatever WE want. This is how telemetry lets us know what SDK the customer is using. If customers work hard, they can use the SDK and add their own (transport or other) policy to much with it but we want customers to have to work hard to override us here.

We can debate if WithHTTPHeader is working hard or not. I'd say, if the customer uses this, then they CAN override us because they are explicitly trying to and we should probably allow that.

**Comment by antkmsft** [comment]
Autorest.testserver has a test (https://github.com/Azure/autorest.testserver/blob/main/swagger/header.json) that specifically check that if the swagger says that `User-Agent` should have some specific value, the generated code will send that and nothing else. Not even appending. Java, .NET, and Python do pass that test. C++ and Go don't.

There is another similar test, for `x-ms-client-request-id`, C++ fails it, but Go, .NET, and Python do pass.

`User-Agent` and `x-ms-client-request-id` are in the similar categories. Yet the test is to adhere to what the swagger says. It specifies these headers intentionally, there is no other way to read it. For example, for User-Agent, the value should be `"overwrite"`, i.e. "overwrite the user-agent". As almost it expects that naive policy implementation would simply overwrite the values, and wants to prevent that.

**Comment by antkmsft** [comment]
Here is how Go avoids interfering with `x-ms-client-request-id`:
https://github.com/Azure/azure-sdk-for-go/blob/b386adc15c2e60e3812956f68d244b608330c479/sdk/azcore/runtime/policy_request_id.go#L25-L31

**Comment by jhendrixMSFT** [comment]
I'll add that in the past, folks have treated the tests in the autorest.testserver as the "definitive source of truth", only to discover that the test is malformed in some way (my latest example: https://github.com/Azure/autorest.testserver/pull/413).  So, while the test is an interesting data point, I don't think we should let it influence our decision.

**Comment by jhendrixMSFT** [comment]
@JeffreyRichter given that we're way past GA, I don't think we should change anything here for risk of regression.
