### ISSUE TITLE
`azidentity`: `DefaultAzureCredentialOptions` to allow opting out some of the auth methods

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#20502]
### Feature Request

Currently, the `DefaultAzureCredentialOptions` will always try each defined auth method in the fixed order. Imagine I have a VM and want to run some Go code on it to interact with ARM using this SDK, it will always try the MSI (i.e. the VM's identity) instead of falling back to using Azure CLI (i.e. my user account). The request sent from my App will then fail since I didn't give enough role to the VM, which I deliberately want to avoid.

**Comment by chlowell** [comment]
We decided not to add such options because we want to keep the `DefaultAzureCredential` API simple to avoid overwhelming developers who are just getting started with Azure, and making the credential difficult to use and understand. The credential types used in the default chain are exported so you can use them directly. If you want to authenticate with the Azure CLI, you can simply call [`NewAzureCLICredential`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#AzureCLICredential) instead of `NewDefaultAzureCredential`. If you want to change the composition of the default chain, you can create a custom chain with [`NewChainedTokenCredential`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#define-a-custom-authentication-flow-with-chainedtokencredential).

**Comment by magodo** [comment]
@chlowell I have to disagree

**Comment by chlowell** [comment]
`DisableInstanceDiscovery` is an advanced option I'm not fond of, but without it applications on e.g. Azure Stack can't use the type at all. I don't know a similarly compelling use case for an option like `DisableManagedIdentity`. If I understand your scenario correctly, you want to decide at runtime whether to skip managed identity authentication with code like this (please correct me if I misunderstand):
```go
opts := azidentity.DefaultAzureCredentialOptions{}
if condition {
	opts.DisableManagedIdentity = true
}
cred, err := azidentity.NewDefaultAzureCredential(&opts)
```
Here's a way to get the same result with the current API:
```go
var cred azcore.TokenCredential
if condition {
	cred, err := azidentity.NewAzureCLICredential(nil)
} else {
	cred, err := azidentity.NewManagedIdentityCredential(nil)
}
```
Does that work for your application? I'm sorry to have implied in my first response that more code is necessary.

**Comment by magodo** [comment]
@chlowell Yes, I could do that, whilst I still want to keep checking the environment variables for client certificate/secret auth method in the meanwhile. What I'm actually asking is kind of a togglable `DefaultAzureCredential`, which users can choose which methods to enable/disable via the option.

**Comment by RickWinter** [comment]
By design we do not allow modifying which credentials the DefaultAzureCredential uses.  If you would like fine grained control over which credential is used and in which order, the proper approach is to use the ChainedTokenCredential.
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#define-a-custom-authentication-flow-with-chainedtokencredential

**Comment by magodo** [comment]
@RickWinter Would you mind to point which design are your referring to? I didn't recall there is a design principle about how the default auth should be like in the Azure SDK design principle.

**Comment by magodo** [comment]
BTW, things like `AdditionallyAllowedTenants` are unwieldly designed and implemented in the default credential, which makes it consued to follow in a rewrite.

**Comment by chlowell** [comment]
> Would you mind to point which design are your referring to? I didn't recall there is a design principle about how the default auth should be like in the Azure SDK design principle.

There's a note in the readme (see the bottom of [this section](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#defaultazurecredential)). I'll add something similar to the API documentation.

Why do you want to rewrite `DefaultAzureCredential`? `ChainedTokenCredential` enables combining credential types however you like. Expanding on my example above:
```go
env, err := azidentity.NewEnvironmentCredential(nil)
if err != nil {
	// TODO: handle error
}
creds := []azcore.TokenCredential{env}
if condition {
	mi, err := azidentity.NewManagedIdentityCredential(nil)
	if err != nil {
		// TODO: handle error
	}
	creds = append(creds, mi)
}
cli, err := azidentity.NewAzureCLICredential(nil)
if err != nil {
	// TODO: handle error
}
creds = append(creds, cli)
cred, err := azidentity.NewChainedTokenCredential(creds, nil)
```

**Comment by magodo** [comment]
@chlowell Thanks for the illustration! But I noticed the `// TODO: handle error` part is actually hard to implement in a sensible way without touch the private types (like error). Also, you are simplifying the MSI part that the default one uses a `timeWrapper`, which also access some private error type in its implementation. Meanwhile, you are simplifying the `NewEnvironmentCredential` in regards of its usage of its `additionallyAllowedTenants` fields.
