### ISSUE TITLE
`azidentity` - Azure CLI auth won't be triggered after failed MSI authentication

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-sdk-for-go#20523]
### Version
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.2.0

### Reproduce Process

1. Create a resource group with [terraform-provider-azapi](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Resources/resourceGroups/main.tf) using [AzureCLI authentication](https://github.com/Azure/terraform-provider-azapi/blob/main/docs/guides/azure_cli.md). 

### Expected Behavior

Since terraform-provider-azapi uses the [DefaultAzureCredential ](https://github.com/Azure/terraform-provider-azapi/blob/684d03592b9a7e9c64e4bd1884ef8e21ccf75465/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go#L47)to authenticate and does not use EnvironmentCredential, azidentity should first use ManagedIdentityCredential(**this auth type will be chosen by default as there is not switch to control it**) to authenticate. Since MSI is not configured, the authentication will fail and then AzureCLICredential should be retried. Since Azure CLI is configured, the authentiation should be successful.

### Actual Behavior
MSI authentication failed with 403 Forbidden and Azure CLI authentication was not triggered.

```
GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
   Metadata: REDACTED
   User-Agent: azsdk-go-azidentity/v1.2.0 (go1.18.2; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Forbidden
   Cache-Control: no-cache
   Connection: Keep-Alive
   Content-Length: 32445
   Content-Type: text/html; charset=utf-8
   Pragma: no-cache

```
### Reason
According to [this code](https://github.com/Azure/terraform-provider-azapi/blob/684d03592b9a7e9c64e4bd1884ef8e21ccf75465/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/chained_token_credential.go#L96), if the error type is not **credentialUnavailableError**, next authentication method will not be retried. Since the Status=403 caused azidentity returned [AuthenticationFailedError](https://github.com/Azure/terraform-provider-azapi/blob/684d03592b9a7e9c64e4bd1884ef8e21ccf75465/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go#L198), the retry on Azure CLI authentication was not triggered.

Is it possible to ignore the error type to have a retry?

**Comment by chlowell** [comment]
That's interesting, I've never known IMDS to respond 403 to a token request. Can you share some details about the environment? Is there a proxy?

My first suggestion for working around this is to use a specific credential type, if that's possible for your application. That is to say, if you want to authenticate only with the Azure CLI, call `NewAzureCLICredential` instead of `NewDefaultAzureCredential`.

To give some context for this behavior, a credential returns `credentialUnavailableError` to signal to `ChainedTokenCredential` that it can't attempt to authenticate because some configuration or state is missing. `ManagedIdentityCredential` returns this error only when it's configured to use the system-assigned identity and gets a 400 response from IMDS. That's how IMDS responds when managed identity is disabled for a VM, so we treat it as a "non-fatal" error and try the next credential in the chain. We consider any other error from IMDS "fatal" because it means managed identity is apparently enabled for the VM. We return an error to the application because we don't know whether the developer expected managed identity auth to work.

**Comment by marvinbuss** [comment]
> That's interesting, I've never known IMDS to respond 403 to a token request. Can you share some details about the environment? Is there a proxy?

Yes, there is a proxy in place.

> My first suggestion for working around this is to use a specific credential type, if that's possible for your application. That is to say, if you want to authenticate only with the Azure CLI, call NewAzureCLICredential instead of NewDefaultAzureCredential.

This is not something that the user can control in azapi today. `NewDefaultAzureCredential` is used by default.

> That's how IMDS responds when managed identity is disabled for a VM, so we treat it as a "non-fatal" error and try the next credential in the chain. We consider any other error from IMDS "fatal" because it means managed identity is apparently enabled for the VM. We return an error to the application because we don't know whether the developer expected managed identity auth to work.

Have you considered that this may be executed outside of Azure with different configurations and network policies?
In this scenario, this is executed outside of Azure.
Will share more details directly with you. Thanks @chlowell!

**Comment by chlowell** [comment]
To summarize offline discussion, I recommend that application developers who don't control their application's runtime environment use a specific credential type and/or allow users to configure authentication. Default behavior can't produce the best outcome in all scenarios. The scenario here is a CLI tool running in arbitrary environments, one of which has a proxy responding 403 to IMDS token requests. `DefaultAzureCredential` can't know whether the user expects these requests to succeed or would want to try the next credential type. Trying the next credential type could mean authenticating an unexpected identity having unexpected permissions, so `DefaultAzureCredential` returns an error instead.
