### ISSUE TITLE
costmanagement: support API version "2022-10-01"

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#20678]

**Comment by lirenhe** [comment]
@Alancere, could you contact service team and ask them to submit the release request?

**Comment by Alancere** [comment]
Hi @magodo  thanks for this issue!

Releasing a new package will require the service to submit a new SDK release request, I have added the label on this issue so that the corresponding service team could take this a look.
I also sent some internal emails to the contact of the corresponding service team about this.

**Comment by Alancere** [comment]
package released: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/costmanagement/armcostmanagement/v2@v2.0.0
