### ISSUE TITLE
NewContainerServicesClient not declared by armcompute

### ISSUE THREAD

**Issue by utkarsh5474** [Azure/azure-sdk-for-go#20690]
### Bug Report

Following the [profile migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/profile-migration-guide.md), 
I'm trying to migrate
From
`github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute`
To
`github.com/Azure/azure-sdk-for-go/profile/p20200901/resourcemanager/compute/armcompute`
but can't seem to find NewContainerServicesClient method.
`NewContainerServicesClient not declared by package armcompute[UndeclaredImportedName])`

What should be the correct way to migrate?
- go 1.19

**Comment by lirenhe** [comment]
@utkarsh5474, are you migrating the profile packages?
If not, could you follow this guide instead?    https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

**Comment by utkarsh5474** [comment]
Sure, thanks. 
If I see https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute#pkg-overview, it suggests to migrate to https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute@v1.0.0

While [type ContainerServicesClient](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute#ContainerServicesClient) is available in [compute/mgmt/2019-07-01/compute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute), it's not in [armcompute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute@v1.0.0)
Is there a separate migration guide to be followed for this?

**Comment by tadelesh** [comment]
After `2020-10-01-preview`, the compute tag does not contains the container service resource type: https://github.com/Azure/azure-rest-api-specs/blob/9875670853ce5340877e6ab0c54f0d0e4a597727/specification/compute/resource-manager/readme.md?plain=1#L992. I'll involve service team to help.

**Comment by Drewm3** [comment]
Removing the label "Compute" since that label is used for VMs, and adding AKS because Container Services is covered by the AKS team.

**Comment by tadelesh** [comment]
@utkarsh5474 could you please check if the API you wanted is in https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v3?

**Comment by utkarsh5474** [comment]
My issue is pretty much the same as https://github.com/Azure/azure-sdk-for-go/issues/14915
But there seems to be no satisfactory reply there. Can someone please take a look?

**Comment by tadelesh** [comment]
@FumingZhang could you help to take a look?

**Comment by FumingZhang** [comment]
Hey everyone, there's a new API ListKubernetesVersions available in managed cluster since 2023-03-01 (stable)/2023-03-02-preview (preview) to replace the old API ListOrchestrators in container service.

In latest azure go sdk ([v4](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4)), the corresponding method is [ListKubernetesVersions](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4#ManagedClustersClient.ListKubernetesVersions). The sample response of this new API is listed in [rest api doc](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?tabs=HTTP#list-kubernetes-versions).

@utkarsh5474, @tadelesh
