### ISSUE TITLE
Question: Why the Azure Cost Usage Func does NOT support Pagination?

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#20851]
https://github.com/Azure/azure-sdk-for-go/blob/f252cd9f178d89af5a3b0f595e72c8b1479904c7/sdk/resourcemanager/costmanagement/armcostmanagement/query_client.go#L60

In case, I query the vms' costs within a subscription with the following query and there were thousands of vms in the subscription, without pagination will there be potential problem?

```
        scope := fmt.Sprint("subscriptions/", subscriptionId)
	now := time.Now()
	start := now.Add(-168 * time.Hour)
	end := now
	metricName := armcostmanagement.ExportTypeActualCost
	res, err := client.Usage(ctx, scope, armcostmanagement.QueryDefinition{
		Type:      to.Ptr(metricName),
		Timeframe: to.Ptr(armcostmanagement.TimeframeTypeCustom),
		TimePeriod: &armcostmanagement.QueryTimePeriod{
			From: &start,
			To:   &end,
		},
		Dataset: &armcostmanagement.QueryDataset{
			Aggregation: map[string]*armcostmanagement.QueryAggregation{
				"totalCost": {
					Name:     to.Ptr("PreTaxCost"),
					Function: to.Ptr(armcostmanagement.FunctionTypeSum),
				},
			},
			Granularity: to.Ptr(armcostmanagement.GranularityTypeDaily), //GranularityType("None")
			Grouping: []*armcostmanagement.QueryGrouping{
				{
					Name: to.Ptr("ResourceId"), //ResourceGroup, SubscriptionId
					Type: to.Ptr(armcostmanagement.QueryColumnTypeDimension),
				}},
			Filter: &armcostmanagement.QueryFilter{
				Dimensions: &armcostmanagement.QueryComparisonExpression{
					Name:     to.Ptr("ResourceType"),
					Operator: to.Ptr(armcostmanagement.QueryOperatorTypeIn),
					Values: []*string{
						to.Ptr("microsoft.compute/virtualmachines"),
					},
				},
			},
		},
	}, nil)
```

**Comment by navba-MSFT** [comment]
@xqi-aviatrix Thanks for reaching out to us and reporting this issue. Most ARM APIs deal with Creating/Updating/Getting/Deleting an azure resource, so a get response is usually in the form of a “value” array of objects that represent the resource(s) information.
Example:
<img width="437" alt="image" src="https://github.com/Azure/azure-sdk-for-go/assets/57353862/9c6d2a1c-2eeb-414b-b027-7a0c9c64637f">

In the Cost Management query case, we do not do the above operations on a resource, we simply fetch the aggregated cost of a resource based o what the customer specifies (and I am sure, as customers of the API, you already know that).

Hence, our response in unconventional:

<img width="483" alt="image" src="https://github.com/Azure/azure-sdk-for-go/assets/57353862/9235ac21-3aaa-4bb1-b656-0cca9dd4fc05">

So due to the above we cannot add the x-ms-pageable field in the [REST API specs swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L950-L959). And since this is not available in the swagger, the SDK cannot provide this functionality.

So in short, the ONLY workaround here is to invoke the [Cost management query API](https://learn.microsoft.com/en-us/rest/api/cost-management/query), Get the NextLink marker and enumerate through it until the provided nextLink is null. Samples are [here ](https://gist.github.com/JoramM/c0538593c80822e37f6cd6d0d2c0c65f)and [here](https://github.com/jkroepke/homelab/blob/571c16491f2f2205a3d52e5ce046aa7adfb8a1d2/go/azure-cost-query-pagination/main.go). Hope this helps.

**Comment by navba-MSFT** [comment]
@xqi-aviatrix I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@xqi-aviatrix I hope you had a chance to look at my above comment. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
