### ISSUE TITLE
A way to normalize `ID` values in read calls?

### ISSUE THREAD

**Issue by disq** [Azure/azure-sdk-for-go#20982]
### Feature Request

What's a  good way to hook into the SDK, to normalize each `ID` value returned? There are some casing differences between some get/list methods which make it hard to correlate data (or to have meaningful primary keys around ids) I was wondering if there's a good way to solve that on the SDK side?

**Comment by erezrokah** [comment]
This might help users handle these various casing issues https://github.com/Azure/azure-sdk-for-go/issues?q=is%3Aissue+is%3Aopen+casing

**Comment by lirenhe** [comment]
+ @jhendrixMSFT for awareness.

**Comment by ArcturusZhang** [comment]
Hey @erezrokah we could investigate this. Since I am not very actively working for Go SDK right now, I would like to defer @jhendrixMSFT to take a look at this request.

**Comment by jhendrixMSFT** [comment]
@erezrokah I think implementing a custom pipeline policy to mutate the data is what you're looking for.  You can find the docs for this [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#pkg-overview).  This is a bit of an "advanced" scenario, so please reach out if you have questions and we can update the docs accordingly.

The lack of consistency of resource IDs has been a thorny issue.  CC @JeffreyRichter as we've discussed this in the past.

**Comment by JeffreyRichter** [comment]
According to the URL RFC, URLs are case-sensitive. See https://www.w3.org/TR/WD-html40-970708/htmlweb.html and search for "case". Therefore, IDs in URLs are supposed to be case-sensitive. Unfortunately, Azure's ARM service treats them as case-insensitive for look-up but they are case-preserved when created. This means that there is no such concept as a canonical representation of an ARM resource ID. We've talked about fixing this, but it is too severe of a breaking change to do so now. So, client code MUST perform case-insensitive comparisons when comparing ARM resource IDs. 

Almost all Azure data-plane services do correctly treat resource IDs as case-sensitive. For example, Azure Storage (the biggest service), does this because file names in Linux are case-sensitive and customers need to backup/restore file folders to Azure Storage and treat file names that differ only in case as separate and unique.

**Comment by erezrokah** [comment]
> @erezrokah I think implementing a custom pipeline policy to mutate the data is what you're looking for. You can find the docs for this [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#pkg-overview). This is a bit of an "advanced" scenario, so please reach out if you have questions and we can update the docs accordingly.

Thanks @jhendrixMSFT that seems like exactly what we were looking for 🚀 I don't mind closing this issue if @disq doesn't mind, until we try those docs and report back.
If we get it working we could even contribute back a working example for normalizing IDs to your docs, so others can benefit.
