### ISSUE TITLE
Introduce a new kind of "TokenCredential" to support authentication concurrently

### ISSUE THREAD

**Issue by ywk253100** [Azure/azure-sdk-for-go#21061]
### Feature Request

Currently, the `azidentity.EnvironmentCredential` provides several options to do the authentication(e.g. secret/certificate/username/password) and is quite easy to use. we can load the credentials as the environment variables and authenticate with the `EnvironmentCredential`. It works well in a single-process environment. But when programming with the SDK concurrently, the same solution causes issues as the different credentials may overwrite others.

So how about we introduce a new kind of `TokenCredential` which is like the `EnvironmentCredential` but reads the credentials from a map rather than the environment variables? 

We can implement that locally but I think it's also helpful for other developers, if we can contribute this part to the upstream, this will avoid duplicated codes maintained by different developers.

Besides, we can also introduce a new wrapper just like the `DefaultAzureCredential` which wraps `EnvironmentCredential`, `WorkloadIdentityCredential`, `ManagedIdentityCredential`, and `AzureCLICredential` but replace the `EnvironmentCredential` with the new one that reads from a map. That would be quite helpful for the concurrent programming!

**Comment by chlowell** [comment]
Can you elaborate on your scenario or share some example code? What do you mean by "credentials may overwrite others"? The configuration of an `EnvironmentCredential` instance is immutable--it's set by `NewEnvironmentCredential` according to the current state of the environment. Does your application set environment variables between `NewEnvironmentCredential` calls?

**Comment by ywk253100** [comment]
> Does your application set environment variables between NewEnvironmentCredential calls?
Yes. 
Our application reads from/writes to different Azure storage accounts which have different credentials concurrently. It loads the credentials of the storage account as the environment variables and calls `NewEnvironmentCredential`. So different storage accounts may impact each other

**Comment by chlowell** [comment]
I see. In the abstract, your app does something like this, which is racy because environment variables are global state:
```go
for _, account := range accounts {
	setEnvVars(account)
	go func() {
		cred, _ := azidentity.NewEnvironmentCredential(nil)
		doWork(cred)
	}()
}
```
You propose a new credential type that's constructed with a map of some key type to credential instances. Authenticating with this new type would mean providing a key to identify which credential should actually attempt to authenticate. Off the top of my head I see a number of problems in designing and implementing that. But I also don't see how it would help in your scenario. If I understand correctly, your application maps accounts to environment variables then calls `NewEnvironmentCredential` to map those variables to credential types. The new type you propose would be less racy but no easier to use because it would still require your application to map its accounts to some configuration object.

Couldn't your application map accounts directly to credential types instead? For example, given an account that has tenant and client IDs and a secret, call `NewClientSecretCredential` instead of setting `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET` and `AZURE_TENANT_ID`.

**Comment by ywk253100** [comment]
> Couldn't your application map accounts directly to credential types instead? For example, given an account that has tenant and client IDs and a secret, call NewClientSecretCredential instead of setting AZURE_CLIENT_ID, AZURE_CLIENT_SECRET and AZURE_TENANT_ID.

We could. But as we need to support different kinds of authentication methods in our application(e.g. secrets/cert/username/password and also workload identity), we implemented a new credential type that just works as the `EnvironmentCredential` and `DefaultCredential` but loads the credentials from a map.

That works for us. But seems this is a common scenario when interacting with Azure concurrently, so I'm thinking whether we can contribute this part to the upstream.

**Comment by chlowell** [comment]
> seems this is a common scenario when interacting with Azure concurrently, so I'm thinking whether we can contribute this part to the upstream.

Thanks for considering contributing. To be honest, we're generally conservative when adding public API and I doubt we would want to add this because the scenario seems straightforward to address with the current API and not significantly helped by a new, specialized API. My knowledge of your scenario and design are limited though, so I may be missing something important. Please feel free to add more details here or open a PR if you'd like to discuss the concrete implementation.
