### ISSUE TITLE
Support showonly in ListBlobsFlatPager in order to list directories

### ISSUE THREAD

**Issue by erictg** [Azure/azure-sdk-for-go#21083]
### Feature Request
Ability to list directories in the container client. It is [supported by the API](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad), so it is unclear as to why this is not supported in the sdk. It looks like someone already requested this, but the ticket issue was locked -- #18921. This is an extremely important feature for the sdk to support and the lack of support for this feature may lead to the use of different storage solutions.

**Comment by tasherif-msft** [comment]
Hi @erictg looking at showonly in https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad#uri-parameters all the options have to do with HNS accounts, this flag will be available in our datalake package which we are currently working, since it's not supported in flat namespace accounts.
