### ISSUE TITLE
Expose HTTP header key names

### ISSUE THREAD

**Issue by unmarshall** [Azure/azure-sdk-for-go#21094]
### Feature Request

Packages versions used:
```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.7.0-beta.2
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.4.0-beta.1
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5 v5.1.0-beta.1
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/marketplaceordering/armmarketplaceordering v1.2.0-beta.1
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resourcegraph/armresourcegraph v0.8.0
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources v1.2.0-beta.1
```
> NOTE: Beta versions are used in order to leverage the fake packages introduced.

For traceability we extract the following headers:
1. `X-Ms-Correlation-Request-Id`
2. `X-Ms-Request-Id`
3.  `x-ms-error-code`
4.  `x-ms-client-request-id`

We saw that for the above constants have been defined in [internal/shared](https://github.com/Azure/azure-sdk-for-go/blob/5672baa27b7d01c70eba1a9ddcde33e3170be9aa/sdk/azcore/internal/shared/constants.go#L27-L29) package.
Since these constants are in an internal package having a dependency on that package is not good for any consumer. Is it possible to move these constants to a non-internal package which consumers of the SDK can easily use instead of hard coding these header keys? This will also ensure that if the the name of the header changes the consumers do not have to adapt as long as well defined constant names are used which are kept the same.

> NOTE: We noticed that `x-ms-correlation-request-id` is currently missing from the constants. Is this a miss or is this header no longer set?

**Comment by lirenhe** [comment]
@raych1, could you help to take a look?

**Comment by raych1** [comment]
Hi @jhendrixMSFT , do you think if these constants can be exported to be consumed by the end user?

**Comment by tadelesh** [comment]
Also add @JeffreyRichter to help to evaluate. For azure specific constants, shall we export them?

**Comment by JeffreyRichter** [comment]
I'm opposed to exposing these and moving them to a non-internal package.
There is nothing special about these constants and, in fact, we could get rid of these constants entirely and just hard code the strings in our code where we need them. These headers are all well-documented and our "x-ms-error-code" string is no more special than anyone else's "x-ms-error-code" string. 

- But, by exposing these constants, we open ourselves to having customer dependencies that we would not have otherwise. 
- We have to document these and maintain them in perpetuity which might cut off some opportunities for us in the future. 
- By documenting them, we implicitly raise their importance and customers might take a dependency that we do not want them to take. 
- Also, by documenting them we pollute our public surface area which is already bigger than we'd like it to be for a minimal-value scenario. 

Making these public has no upside to the SDK and does not enable any scenario for a customer that is not already trivially possible. In addition, a customer who wants to use these header values knows that they want to use them and knows what the values are already -- they'd have to somehow discover these constants in the SDK which is very unlikely and so even if we did this work, it is unlikely to be useful.

**Comment by unmarshall** [comment]
It is not uncommon to make certain request/response headers as part of the public API. See [here](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html). Since these are part of the response therefore one can argue that its part of the contract as these are available in the response for consumers of the API to consume.

>Making these public has no upside to the SDK and does not enable any scenario for a customer that is not already trivially possible

`X-Ms-Correlation-Request-Id`, `X-Ms-Request-Id`  - these are typically used by consumers when reporting issues to Azure as this gives a handle to the azure teams to trace a particular request. 
`x-ms-error-code` - this is used by the consumer of the API to extract the azure error code in addition to the HTTP response code and print it in the logs for better diagnostics.

>These headers are all well-documented and our "x-ms-error-code" string is no more special than anyone else's "x-ms-error-code" string.

Sure, request-ID, correlation-ID and error-code are very generic concepts but the name of these properties are MS specific and therefore one can argue that they be part of the contact. If this is part of internal package then can any consumer consume these reliably? The answer is `NO` because it is internal and can be changed which then mandates all the consumers to also always adapt.

>But, by exposing these constants, we open ourselves to having customer dependencies that we would not have otherwise.

Since these are so generic and common properties why would you even have the need to change it?

**Comment by JeffreyRichter** [comment]
These headers are part of the service's REST contract and not part of the Go SDK contract. The only reason the SDK would change these values is because the REST API contract changed. And, I can say with 100% certainty that these header values will never change as I also am on the Azure Breaking Change Board. Changing them would break all the old SDKs too - it will just never happen. 

You are correct: We would never need to change these values (unless we spelled them wrong in the first place). 
We have a goal of minimizing our SDK surface area to keep it simple, easy to maintain, reduce documentation, etc. I just don't see how making these public enables any scenario that isn't trivially solved today by other means.

**Comment by raych1** [comment]
@unmarshall , I close this issue as won't fix. Feel free to re-open this issue if needed.
