### ISSUE TITLE
No error on NewReceiverForQueue if the queue does not exist

### ISSUE THREAD

**Issue by Jummey** [Azure/azure-sdk-for-go#21095]
### Bug Report

- I am using v1.4.0 of github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus
- I am using NewReceiverForQueue with a queue name that does not exist
- I expect the creation of the receiver to fail due to the queue not being there, however I get no error

Is this something you can reproduce and hopefully fix?

**Comment by richardpark-msft** [comment]
Client initialization in Azure SDKs is lazy by design. You won't see a failure until you actually attempt to do something that causes a connection to be initialized.

To get what you want you'll need to actually attempt to receive or use the queue. If you want to avoid mutating the queue (ie, receiving and locking a message, or deleting it) you could also just call PeekMessages(), which won't change anything but does make the connection initialize.
