### ISSUE TITLE
[azopenai] Make deploymentID a per-request parameter

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#21102]
@glecaros brought this up in #21054.

Currently we take the "model deployment" (the Azure OpenAI equivalent of a model) as a constructor parameter, rather than an operation parameter, like OpenAI does.

(from @glecaros)

> I would think this needs to be a per request param, otherwise we would be requiring the developer customer to create, for example, a client for chat completions and another client for embeddings (which may be ok, but I'm not sure if it is the experience we want to provide)

We can adopt the .NET approach of taking the deployment value in the `model` field (they have it named `modelOrDeployment`), which also has the benefit of making normal OpenAI code look the same as Azure OpenAI code.

CC: @JeffreyRichter

**Comment by richardpark-msft** [comment]
@trrwilson, I believe the naming of the parameter started some discussion in the last API review. Was there a conclusion on that, or is `modelOrDeployment` the right thing to do?

**Comment by JeffreyRichter** [comment]
Let me walk through how the Azure SDKs are architected to point out all the issues related to this.

Azure SDK Client types are always constructed with a URL to a resource and then operations are performed on THAT resource.
In some rare cases, a URL may have additional path segments appended to it (KeyVault is an example). In these cases, the path segments are considered mandatory (to make the URL to a resource valid). Client methods would REQUIRE these additional parameter(s) to make the URL valid in order to perform the desired operation. The proposal presented here is for deploymentId to be a mandatory parameter on all the OpenAI client's methods (since deploymentId is mandatory path segment for Azure OpenAI). 

Of course, making deploymentId a mandatory parameter to all methods might be annoying to customers because it forces them to pass the same deploymentId value over and over again if they keep calling the same method repeatedly. So, this is a reason why this proposed design may be unfavorable. 

However, to make matters worse, there is also a serious contradiction here because we also want to make our OpenAI clients usable when talking to non-Azure OpenAI which has no concept of deploymentId at all. So, if we make deploymentId a mandatory parameter, then non-Azure OpenAI customers MUST pass it so that the SDK can ignore it. This makes getting started with our OpenAI SDKs awkward for customers as they must now learn about deploymentId in order to pass something which they need to then understand why this is mandatory and ignored. Clearly, this is an extremely undesirable customer experience.

Furthermore, we want customers to be able to trivially modify their code to make it easy for them to switch from non-Azure OpenAI to Azure OpenAI. So now, they would have to understand all of deplymentId stuff TODAY and how to structure their code to prepare for passing a meaningful deploymentId parameter value in the future - this is a horrible getting-started customer experience and one that I would very strongly council against as it will severely hurt adoption and customer satisfaction of our SDKs.

The current structure of the Go SDK client solves these problems by making customers pass a URL with a deploymentId to an Azure OpenAI constructor and they pass a URL without a deploymentId to a non-Azure OpenAI constructor - all the methods are then the same and, most importantly, customers don't need to understand anything about deploymentId until they want to call Azure OpenAI and they accomplish that by calling a different constructor - the rest of their code is completely identical.

For Azure Open AI only, there is a negative side-effect of this which is (as @glecaros points out) that a URL with a deploymentId which may wrap a single model will have many of its methods (operations) fail. Of course, this is how the service was designed and so the SDK client is merely mimicking the actual service behavior. The job of Azure SDKs is not to fix or improve on service behavior; it is just to make it easier for customers to invoke the service behavior. Perhaps the service should be designed better in this regard?

Also, do we know if the service will ever support multiple models per deployment? If this EVER became possible, then the Go SDK design is definitely the preferred design for customer friendliness as multiple methods will now work correctly and as the customer expects.

An alternative design would be to have our SDKs publicly expose 1 client per deploymentId/Model. So, there could be a ChatCompletionsClient, an EmbeddingsClient, a WhisperClient, and so on. In a way, this is actually the best approach as each client would be constructed with a URL containing a deploymentId for Azure OpenAI and each client would be constructed as usual for non-Azure OpenAI and in both cases, ALL client operations are guaranteed to work correctly all the time and all this would make perfect sense to customers. Perhaps we should consider this design more seriously?

**Comment by richardpark-msft** [comment]
Leaving aside the issue of splitting the clients we completed the work to make `model` a request parameter in #21223, rather than a client parameter, aligning with the other SDKs.

**Comment by richardpark-msft** [comment]
I'm going to create a new issue to track the client separation, since that's a much bigger effort that might not happen at all.
