### ISSUE TITLE
storage: Add User-Agent header to requests

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#212]

**Comment by brendandixon** [comment]
@ahmetalpbalkan I suggest we consider using a dynamic UA string that includes the tag / version level of the package making the request. Otherwise, the data will be too ill-specified to be useful (e.g., it could implicate code that's not at fault and / or miss implicating code that is). Thoughts?

**Comment by ahmetalpbalkan** [comment]
Yep we should probably do that way once we start versioning.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I strongly suggest we start versioning now. It's inexpensive to do once we have defined what we mean by it and the tags we'll use. I realize Go lacks (at present) the facilities to pull by version, but clever developers who care that their code does not suddenly fail, can and will manually vendor at the right tag level.

**Comment by ahmetalpbalkan** [comment]
@brendandixon works for me. Which one first? Adding UA or tagging a version?

**Comment by brendandixon** [comment]
@ahmetalpbalkan We could add UA first since it's quick and will get us our first round of data. Then we can settle on tagging.

Tagging with nested packages is the perennial problem with languages such as Go (or, say, Ruby): Does the tag represent the whole thing or the specific thing. Specific tag references provide greater control and is the direction broadly shared packages have tended to go (in my experience). But they're more difficult and make easy "get all" harder (unless there is an artificial parent package whose work is simply to force inclusion of all children). Let's give this some thought before leaping because once it is in place, we would not want to change it.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Note, by the way, that Ruby addressed this problem by introducing Gemfiles into gems so each could specify its dependencies. Sadly, no such support for Go.

**Comment by robbyt** [comment]
@brendandixon how many projects handle dependencies in go is by using the `/vendor` directory, which can be managed by godep or glide.

Glide seems to be the most similar to rubygems: https://github.com/Masterminds/glide - (it's also my preferred tool)

The `/vendor` directory should then be omitted from the git repo, and only used for local development.

**Comment by brendandixon** [comment]
@robbyt Unclear. The support for /vendor in 1.6 will likely raise the number. Regardless, we no longer include the vendor directory. Consumers need to vendor as they see fit.

**Comment by robbyt** [comment]
@brendandixon Sorry, just making a suggestion from the community how we consume this library :) 

I think the topics of versioning this library, and and setting the version identifier for the user agent are two separate (but dependent) issues. And I understand the need for both.

**Comment by brendandixon** [comment]
@robbyt No worries. We added the Glide manifest because, when we removed the /vendor directory, we wanted some kind of manifest declaring that which we had tested against. Go, in general, is quite immature in this area.

**Comment by robbyt** [comment]
Ahh, I'm using an old checkout, and I overlooked that the Glide manifest has been added to this project. Thanks.

**Comment by mcardosos** [comment]
Fixed in dev branch
