### ISSUE TITLE
Incorrect nextURL link for  armcompute.VirtualMachinesClient with filter of virtualMachineScaleSet (VMSS flex)

### ISSUE THREAD

**Issue by linguo555** [Azure/azure-sdk-for-go#21291]
### Bug Report

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4"
	"github.com/Azure/azure-sdk-for-go/services/resourcegraph/mgmt/2019-04-01/resourcegraph"

We are currently using armcompute.VirtualMachinesClient to listinstances. At beginning we added a filter for virtualMachineScaleSets, see below: 
`filter := fmt.Sprintf("'virtualMachineScaleSet/id' eq "+
		"'/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/virtualMachineScaleSets/%s'",
		c.subscription, c.resourceGroupName, vmssName)
	option := armcompute.VirtualMachinesClientListOptions{
		&filter,
	}
	pager := client.NewListPager(c.resourceGroupName, &option)`
	
When the VM list has more than 50 vms and needs Pagination, the `nextLink` is proved to be an invalid url which returned with response 400  BAD Request. 
Once we moved the option, everything goes ok. 
We manually take the url out and verified it indeed a bad url:

`400 Bad Request
ERROR CODE: BadRequest
{
  "error": {
    "code": "BadRequest",
    "message": "The request URL is not valid."
  }
}`

There is a bug in the SDK with the VMSS flex option. 

Ps: the VMSS we use is VMSS flex. 

Thanks,
Lin

**Comment by jhendrixMSFT** [comment]
Can you please enable [logging](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore#hdr-Built_in_Logging) and provide the URL that's causing the 400 to be returned?

**Comment by zhuweirongdb** [comment]
I think the issue is not the NextLink URL returned by the server, but how the SDK handles the NextLink. 

An example of the returned NextLink looks like

```
https://management.azure.com:443/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/resourceGroups/prod-azure-cacentral-nephos-0-drh4hc/providers/Microsoft.Compute/virtualMachines?api-version=2022-11-01&$skiptoken=007ae11e-5e49-4893-9367-ca97edc45510!/Subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/ResourceGroups/some-rg-DRH4HC/VMs/C18998F4D2AE-BOOK_ED911355&$filter='virtualMachineScaleSet/id' eq '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/resourceGroups/some-rg-DRH4HC/providers/Microsoft.Compute/virtualMachineScaleSets/c18998f4d2ae-book'
```

In the Go SDK, the NextLink is used to construct a new request directly.  See https://src.dev.databricks.com/databricks/universe@fd633de/-/blob/third_party/go/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4/virtualmachines_client.go?L705.  When this request went out,  it got a Bad Request response from server. 

With AZURE_SDK_GO_LOGGING=all, the url used for the outgoing request is sanitized, so we don't know what is actually used.

We tried

-  the same pattern with Azure CLI, which depends on python SDK. It works fine.   From the CLI --debug,  when can see the NextLink is the same as above. And you can also see that the python SDK parsed and processed the NextLink before sending out the new request:  https://sourcegraph.com/github.com/Azure/azure-sdk-for-python/-/blob/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2022_11_01/operations/_operations.py?L16271.  
- when use Go SDK, to workaround the issue, we had to remove the filter, it works. However, it lists all VMs, and we have to do client side filtering. 

My guess: the returned NextLink was not URL encoded, and relies on the client code (e.g. SDK) to do the encoding (like what the python SDK does).

**Comment by jhendrixMSFT** [comment]
Thanks for the info.  Lack of URL encoding was my suspicion as well which is why I wanted to see what the URL was.
