### ISSUE TITLE
`NewDefaultAzureCredential()` does not return an error 

### ISSUE THREAD

**Issue by leuyentran** [Azure/azure-sdk-for-go#21301]
#### Package and version used:

```go
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.3.0
```

#### Bug details:

While reviewing a [PR](https://github.com/kopia/kopia/pull/3131) that uses `NewDefaultAzureCredential()`, I noticed that the function will not return an error even if none of the credential types is available. Detailed analysis can be found [here](https://github.com/kopia/kopia/pull/3131#discussion_r1273734151) as part of the PR review.

**Comment by chlowell** [comment]
There is an apparent bug here in that `NewDefaultAzureCredential` should return an error when all the constructors it calls did as well but it wouldn't actually do so because the test for that condition is incorrect. However, this isn't a bug in practice because it isn't possible for all those constructors to return an error--`NewAzureCLICredential` [never does](https://github.com/Azure/azure-sdk-for-go/blob/4766d8bc0d5cedc322bae6a0de496b5a351e301f/sdk/azidentity/azure_cli_credential.go#L61). I'll tidy up the code to remove the apparent bug.

To give some more context on the design here, constructor success doesn't imply the returned credential will be able to authenticate because in general the only way to validate credential configuration is to attempt to authenticate. Similarly, `NewDefaultAzureCredential` doesn't know whether a constructor error is meaningful because it doesn't know how the caller intends to authenticate. So, it includes any constructor errors in its error message when authentication fails.

**Comment by leuyentran** [comment]
@chlowell Thank you for the quick turn around! 

What you have pointed out here is an important distinction:
> To give some more context on the design here, constructor success doesn't imply the returned credential will be able to authenticate because in general the only way to validate credential configuration is to attempt to authenticate. Similarly, NewDefaultAzureCredential doesn't know whether a constructor error is meaningful because it doesn't know how the caller intends to authenticate. So, it includes any constructor errors in its error message when authentication fails. 

which wasn't immediately apparent due to `defaultAzureCredentialConstructorErrorHandler()` and lack of comments on what an `error` from `NewDefaultAzureCredential` means. 

Thank you for removing `defaultAzureCredentialConstructorErrorHandler()`!
