### ISSUE TITLE
Azure Service Bus: dial tcp xx.xxx.xx.xx:5671: i/o timeout occuring

### ISSUE THREAD

**Issue by dmartin-r7** [Azure/azure-sdk-for-go#21327]
### Bug Report

- import path of package in question `github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus`
- SDK version `1.4.0`
- go version: `go version go1.19.7 darwin/amd64`

**What happened?**
I have the code below, it is continually timing out when I attempt to `ReceiveMessages`
```
client, err := creds.ServiceBus(namespaceName)
	if err != nil {
		ch <- halt(
			cctx,
			logger,
			err,
			"connectivity test",
			`An error occured when connecting to Service Bus namespace endpoint.
			 Azure Service Bus implements these endpoints as unique subdomains.`,
		)
		return
	}
	receiver, err := client.NewReceiverForQueue(
		queueName,
		&azservicebus.ReceiverOptions{ReceiveMode: azservicebus.ReceiveModePeekLock},
	)

	if err != nil {
		ch <- halt(
			cctx,
			logger,
			err,
			"connectivity test",
			`Received an error when attempting to configure the Azure Service Bus client.`,
		)
		return
	}
	logger.Info("servicebus_queue_receiving")
	var receiveErr error = nil
	for {
		innerCtx, cancel := context.WithTimeout(cctx, 60*time.Second)
		messages, err := receiver.ReceiveMessages(innerCtx, archaius.GetInt(cfg.AzureEdhPrefetchMsgs, 50), nil)
		// this is where the timeout occurs
		if err != nil {
			if err.Error() != "context deadline exceeded" {
				logger.Error(err.Error())
				receiveErr = err
				cancel()
				break
			} else {
				logger.Debug("timeout exceeded with no messages, polling again.")
			}
		}
```

These are the logs I am seeing:

```
    {
            "msg": "servicebus_queue_receiving",
    },
    {
        "@message": "[azsb.Auth] (queue-name) refreshing claim",
    },
    {
        "@message": "[azsb.Conn] Creating new client, current rev: 0",
    },
    {
        "@message": "[azsb.Conn] Links closing (permanent: false)",
    },
    {
        "@message": "[azsb.Receiver] (receiveMessages.getlinks) Retry attempt 0 was cancelled, stopping: dial tcp xx.xxx.xx.xx:5671: i/o timeout",
    },
    {
        "@message": "[azsb.Receiver] Stopped message releaser with ID 'empty'",
    },
    {
        "@message": "[azsb.Conn] Links closing (permanent: true)",
    }
```

This only occurs once I attempt to retrieve messages, I can seemingly instantiate the client without error's being returned but I get this dial timeout that causes the context to expire resulting in nothing being returned. Is there an error being suppressed when I create the client that I can't see? It's strange to me that I can create a client but not use it.

What causes this timeout and is someone able to explain to me how Azure connects to your service bus via the sdk as I have confusion around the networking there?

Thanks

**Comment by richardpark-msft** [comment]
Great questions and points to me needing to write some extra comment text.

So, to the first question:

> Is there an error being suppressed when I create the client that I can't see? It's strange to me that I can create a client but not use it.

The oddness you're seeing here is because clients in the Azure SDK are lazily-initialized - the underlying TCP connection isn't actually created until you perform an operation (any function that takes a `context.Context`). 

So no error is being suppressed, but we only got an error when we tried to actually create the TCP connection.

> What causes this timeout and is someone able to explain to me how Azure connects to your service bus via the sdk as I have confusion around the networking there?

That error is coming back from the underlying Go TCP library, which is just opening a TCP connection (on port 5671) to your Service Bus instance. There's actually an HTTP service on the Service Bus host (used for administration) which you can just open in a browser if you want to check if you can reach it via HTTP, at least, just to see if network connectivity works. For example, `https://<your-sb-instance>.servicebus.windows.net`. 

Sometimes the port trips people up because it's not allowed through their firewall. This doc describes that a bit more: [AMQP ports](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide#amqp-outbound-port-requirements).

Now, if you're _not_ allowed to connect out using `5671` you can use websockets which will tunnel you out via TLS on port 443. We have an example here: [using websockets and proxies](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus#example-NewClient-UsingWebsocketsAndProxies).
