### ISSUE TITLE
Managed identity authentication on AzureML Compute resources broken

### ISSUE THREAD

**Issue by maben-mw** [Azure/azure-sdk-for-go#21396]
### Bug Report

- SDK version `master`, ([99c0a04](https://github.com/Azure/azure-sdk-for-go/commit/99c0a042b1a228db9cd1f0c54df095f24f13cf28)

- What happened?

On AzureML Compute instances, managed identity authentication is not working with current Go SDK version.

It appears that AzureML uses MSI "2017 style" managed identities with an `MSI_ENDPOINT` and `MSI_SECRET` and where the identity is specified using query parameter `clientid` (rather than `client_id`).

I.e. I can obtain the tokens I need successfully with:

```console
curl "${MSI_ENDPOINT}?resource=https://storage.azure.com&clientid=${DEFAULT_IDENTITY_CLIENT_ID}" --header "Secret: ${MSI_SECRET}"
```

In Java and Python SDK I can use these managed identities without issue.

In the Go SDK it appears this used to be supported in the past, but the option got removed (hence reporting this as a bug rather than an enhancement):

https://github.com/Azure/azure-sdk-for-go/commit/d67aff0d17e2cd6e1bf4c341b565bb88366f2dd4

**Comment by chlowell** [comment]
Could you please describe your scenario i.e., how you use Go with Azure ML, and point me to some documentation describing how to deploy Go to Azure ML (I don't find any)? We'd need at least that much to test this feature.

You're correct about the history--`azidentity` coincidentally supported Azure ML's managed identity API until v0.13.2 because that API mimics a version of App Service's managed identity API. When App Service rolled out a new version, we stopped supporting the old one because we didn't see a reason to continue supporting it in `azidentity` v1.x.

**Comment by maben-mw** [comment]
I don't directly use the Azure Go SDK, what I do is:

1. Create a Compute Instance on AzureML with an user assigned managed identity:

   https://learn.microsoft.com/en-us/azure/machine-learning/how-to-create-compute-instance?view=azureml-api-2&tabs=azure-studio

2. On the instance which I created, I try using [rclone](https://rclone.org/) to [mount an Azure Blob using that managed identity](https://rclone.org/azureblob/) (i.e. `use_msi` = `true` and set `msi_mi_res_id` to resource ID of the managed identity). rclone uses Azure Go SDK for this, including the authentication part of Azure Go SDK. This just fails as for authentication, the SDK will try a POST to `$MSI_ENDPOINT` with `client_id` query parameter whereas it should be performing a GET to `$MSI_ENDPOINT`, set a header with `$MSI_SECRET` and use `clientid` query parameter.

**Comment by joshfree** [comment]
Charles is going to open up issues for all languages and we'll fix this in Azure Identity SDK for early 2024 (to adapt to the breaking change below us in the stack)
