### ISSUE TITLE
Add ClientId in Options for `azidentity.NewDefaultAzureCredential`

### ISSUE THREAD

**Issue by somtochiama** [Azure/azure-sdk-for-go#21453]
### Feature Request

Add a `ClientId` field to `DefaultAzureCredentialOptions`. 
This can then be set in `WorkloadIdentityCredentialOptions.ClientID`, to use a `ClientID` that's different from the `AZURE_CLIENT_ID`  environment variable.

More Notes:

The [Python client](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) has the `workload_identity_client_id` string as part of its args and I guess it is similar to what is being requested. So maybe `WorkloadIdentityClientID` might be a better name.

**Comment by chlowell** [comment]
We chose to omit options like this in Go because we want to keep DefaultAzureCredential focused on straightforward scenarios addressed by its default behavior such as getting started with a new service client, or with Azure in general. I take it you're running an application in a pod assigned multiple workload identities? In that case, I'd recommend using [WorkloadIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#WorkloadIdentityCredential) instead.

**Comment by somtochiama** [comment]
@chlowell 

> I'd recommend using [WorkloadIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#WorkloadIdentityCredential) instead.

We currently use `NewDefaultAzureCredential` so we can use the authentication scenario the user has configured (not just workload identity). This addition will also enable us to accommodate users with multiple workload identities. The `WorkloadIdentityCredential` only works for workload identity.

**Comment by chlowell** [comment]
Can you describe your scenario in more detail? How is your code ultimately consumed e.g., is it a library or infrastructure component your users deploy to their own hosting environments?

**Comment by somtochiama** [comment]
An infrastructure component that users deploy in their own hosting environment (FluxCD - it's a Kubernetes controller that gets deployed on clusters). 
We call `NewDefaultAzureCredential`  [here](https://github.com/fluxcd/pkg/blob/4032134563d7dec658e99d6919fcf9f179ae6d6f/oci/auth/azure/auth.go#L70) and the package is used in the [source-controller](https://github.com/fluxcd/source-controller) to authenticate ACR repositories.

**Comment by somtochiama** [comment]
@chlowell

Supporting all the credential types will lead to writing something close to `DefaultAzureCredential` function.

**Comment by chlowell** [comment]
Do you really need to support all credential types? `DefaultAzureCredential` supports authenticating via developer tools like the Azure CLI--are those relevant to your application? Setting that aside though, even if it means writing more code, making authentication an explicit part of user configuration is valuable because it prevents scenarios like the one I described above and makes authentication predictable. DefaultAzureCredential's fallback behavior is convenient during development, but in production users know how they intend to authenticate their applications and are better served by a clear error message than trying some other identity.

Let me also point out that relying on `DefaultAzureCredential` means passing any changes to the default chain along to your users when you upgrade to a new version of `azidentity`.
