### ISSUE TITLE
Extend migration guide

### ISSUE THREAD

**Issue by clausMeko** [Azure/azure-sdk-for-go#21504]
### Feature Request

Reading `https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/migrationguide.md` I had no clue how the authentication works now.

#20022 helped me solving the issue.

However explaining the Token setup now would be beneficial for many.

The current example for authentication where you initialize via:
```go
defaultAzureCred, err := azidentity.NewDefaultAzureCredential(nil)
if err != nil {
  panic(err)
}
```
is simply not realistic because of `nil` and DefaultFunc.

Instead I had to use:
`azidentity.NewClientSecretCredential(...)`

which is probably closer to what most will need to do and therefore more instructive.

**Comment by richardpark-msft** [comment]
@clausMeko, it's an interesting point. We do think that the DefaultAzureCredential is a good starting point, since it picks up so many common credential types. There's a specific bit in the documentation about it that mirrors what you're saying:

> Note: DefaultAzureCredential is intended to simplify getting started with the SDK by handling common scenarios with reasonable default behaviors. Developers who want more control or whose scenario isn't served by the default settings should use other credential types.

With that said, I need to put some some comments in the examples that make it clear that this is not the only type and that there are _many_ different types available. We tend to not over-duplicate docs, but I might have gone overboard there.
