### ISSUE TITLE
Go SDK generates a sas token, and I not found that the parameters specified for ske

### ISSUE THREAD

**Issue by lc-lc0304** [Azure/azure-sdk-for-go#21569]
Hi Team:

Upload images using the go language SDK provided by Azure Blob, and generate a SAS link that can be accessed through the front-end; But today we found a large number of link access errors, such as the following:
https://devbackup.blob.core.chinacloudapi.cn/lowcode-file/picture-default-9b326bd3-e006-4162-8406-89ddde85d869.png?rsct=image%2Fpng&se=2220-10-30T07%3A54%3A44Z&sig=YZbUwrLksKOGLGpHNagzrZVwB0IPzqt4bOOG11p27Us%3D&ske=2023-09-15T07%3A54%3A34Z&skoid=a6fc1480-6128-4e58-af8d-29be12098ebe&sks=b&skt=2023-09-13T07%3A54%3A34Z&sktid=98dcf853-a1d3-4d7d-bd47-544042eef40a&skv=2020-10-02&sp=rl&spr=https&sr=b&st=2023-09-13T07%3A54%3A34Z&sv=2020-02-10

We found that the reason for the problem is that the SKE has reached its expiration date, as shown in the figure:
![image] (https://github.com/Azure/azure-sdk-for-go/assets/82637043/ad85cf80-501d-49bb-9874-3c18232d497b)

We cannot find the specified parameter for 'ske' in the official code. I need to specify its duration to make it exist for a longer time.

Our code is as follows:
![image](https://github.com/Azure/azure-sdk-for-go/assets/82637043/5a68587f-a35c-45c3-ab28-5f375fff7c83)

May I ask if the 'ske' parameter exists, and if so, how can I set it? Thank you.

**Comment by siminsavani-msft** [comment]
Hi @lc-lc0304 ! In order to see the `ske`, you could potentially use a web capturing tool (i.e. Fiddler) to see the request headers. The string to sign seen here: https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#version-2020-12-06-and-later should be similar to what is seen in the request. 

If you want to debug via the IDE, you could potentially set a breakpoint inside of the method `SignWithUserDelegation` at line 199 in service.go (https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/sas/service.go#L199) to see what the value of `udkExpiry` (which is the name for `ske`).

Please let me know if you have any additional questions!
