### ISSUE TITLE
Codegen is missing validation for enums

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-sdk-for-go#2182]
Hi,
   I am working on kubernetes on Azure, recently I found a bug: [create azure storage account failed in azure file plugin](https://github.com/kubernetes/kubernetes/issues/65845), after investigation, I found it's due to our azure-sdk-for-go upgrade, there is a new field `Kind` which is required, so any sdk upgrade from and old version would break the storage account creation since old code won't use `Kind`. So my question is is there any way to make it compatible, e.g. make new field `Kind` as `StorageV2` by default?

**Comment by jhendrixMSFT** [comment]
Can you clarify the upgrade path so I can understand how this broke you, i.e. upgrading SDK versions, API versions etc.
Swagger doesn't let you specify a default value for required parameters so there's no way to default it.

**Comment by jhendrixMSFT** [comment]
I did notice that the codegen is missing validation for enums, this is a bug that needs to be fixed.

**Comment by RickWinter** [comment]
Track2 generator considers the Service the source of truth and does not do client side validation logic.

**Comment by tombuildsstuff** [comment]
@RickWinter reading through [the original comment](https://github.com/Azure/azure-sdk-for-go/issues/2182#issue-338444951) this appears to be more regarding the Enums changing names across versions (than the validation mentioned in Joel's comment, where this got renamed) - for which the root-cause appears to be missing `x-ms-enums` in the Swaggers - whilst this could be fixed in this SDK, is there a plan to go through and add the missing `x-ms-enums` to the Swaggers, which would fix this?

**Comment by andyzhangx** [comment]
this is not an issue now
