### ISSUE TITLE
armkeyvault: KeysClient ListPager doesn't provide all information for a key

### ISSUE THREAD

**Issue by lebogg** [Azure/azure-sdk-for-go#21855]
### Bug Report

- import path:. `.../azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault@v1.3.0/keys_client.go:261`
- output of `go version`: go1.21.1 linux/amd64

- What happened?
I was using `KeysClient`s method `NewListPager` to get a retrieve all keys that we have in a certain key vault. But the returned keys of the key pages miss many information. E.g., `Kty` was always nil.
Now I realized that using the `KeysClient`s method `Get` I get all informaiton about one specific key. But why do  I not get all the key information via the list pager and, in particular, why the list pager method doesn't say anything about it in the comment that some fields won't be filled?

- What did you expect or want to happen?
Either fill out all information or comment the methods appropriately to give advice to be cautious.

Thanks in advance!

**Comment by MBSolomon** [comment]
Hi @lebogg,

Per Key Vault documentations this is an expected behavior when retrieving a list of all the keys in a Key Vault instance ([documentation](https://learn.microsoft.com/en-us/rest/api/keyvault/keys/get-keys/get-keys?tabs=HTTP)) . When you use `NewListPager` to retrieve all keys that you have in a specific key vault you will be returned:

 "_the keys in the Key Vault as JSON Web Key structures that contain the public part of a stored key. The LIST operation is applicable to all key types, however only the base key identifier, attributes, and tags are provided in the response. **Individual versions of a key are not listed in the response**._"
 
 In order to acquire all information about one specific key you will need to iterate through the returned list of keys and send a separate request for each key. [GetKey func](https://github.com/Azure/azure-sdk-for-go/blob/29fe1c0613fc59a1490d0580ebd220fcf0e2659f/sdk/security/keyvault/azkeys/client.go#L390).
 
 It should look something like this once if you already have a `resp` with all keys returned from `NewListPager`:
```
for _, key := range resp.KeyProperties {
            getKeyResp, err := client.GetKey(context.Background(), *key.Name, nil)
            if err != nil {
                log.Printf("Failed to get key: %v", err)
                continue
            }
        }
```
 
 Please let me know if you have any further questions!

**Comment by lebogg** [comment]
Ok, I now understand that you don't want to return all values in the respective `list` function and I can totally respect that. But tbh I find it strange that I don't get this information in the SDK, e.g. in the comment of the function, but I have to go the rest api documentation page to find out the actual behavior.
 
Thank you @MBSolomon
