### ISSUE TITLE
ARM should reject unknown properties and values

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#21892]
Per

https://armwiki.azurewebsites.net/api_contracts/guidelines/openapi.html#oapi018-reject-unknown-properties-and-property-values

Should the generated marshallers reject unknown properties/values?

**Comment by jim-minter** [comment]
I could imagine this being quite undesirable in our SDKs as used by customers (receiving data from us), but useful when we use the same SDKs server side (receiving data from customers).  It'd need to be an option.

**Comment by serbrech** [comment]
We discussed that some time ago @jhendrixMSFT.
This request was in particular because we want to reuse the SDK types on server side. it handles a lot of the quircks of the Azure specific formats in the SDK, so it's nice to take advantage of it.
it also ensure that our swagger spec generates what our service needs, and that the types are exactly the same as what the SDK creates. It allows to stop worrying about some small incompatibilities that have been experienced when hand-rolling the server types.

We generate our types by calling autorest (not by importing the SDK). so server side types options would make sense.

From my earlier analysis, it would be very simple, as the current unmarshaller goes via a map.
if there is anything left in the RawMessage at the end, it means it didn't match a property on the target type, and we can error.

if you have an idea on how to build that as a plugin, that's ok. but I think considering how simple this addition would be inside the Unmarshal implementation, it makes more sense to have it built-in as an option.

**Comment by serbrech** [comment]
I'd also note that we're happy to give it a go with some help if you think this makes sense.

**Comment by serbrech** [comment]
Had a closer look, I think it's even simpler than this, we might just need to add a default case in the switch statement

```go
// UnmarshalJSON implements the json.Unmarshaller interface for type ErrorResponse.
func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return fmt.Errorf("unmarshalling type %T: %v", e, err)
	}
	for key, val := range rawMsg {
		var err error
		switch key {
		case "error":
			err = unpopulate(val, "Error", &e.Error)
			delete(rawMsg, key)
		default: // Unexpected key
			err = fmt.Errorf("unknown key for type %T: %q", e, key)
		}
		if err != nil {
			return fmt.Errorf("unmarshalling type %T: %v", e, err)
		}
	}
	return nil
}
```

**Comment by serbrech** [comment]
ah, the default case would clash with the handling of special AdditionalProperties 

```
 if (addlProps) {
    unmarshalBody += '\t\tdefault:\n';
    unmarshalBody += emitAddlProps('\t', addlProps);
  }
```
