### ISSUE TITLE
[azblob] Un-reported breaking change between 1.0 and 1.2.1..

### ISSUE THREAD

**Issue by sblackstone** [Azure/azure-sdk-for-go#22297]
### Bug Report

I have a wrapper for `azblobs` in that does (basically) this.... (unimportant details omitted)

``` golang
	file, err := os.CreateTemp("", "")
	_, err = client.DownloadFile(context.Background(), blobConfig.ContainerName, blobName, file, nil)
	return file
```

After upgrading from 1.0.0 to 1.2.1 of azblob package, my code silently broke in production because the file descriptor after DownloadFile now pointed to the end of the file rather than the beginning.  This was solved with `Seek(0,0)` before returning..

There haven't been any mentions of this (as far as I can tell) in the CHANGELOG (there have been no breaking changes since 1.0.0)

I've been unable to track down the exact change that caused this but I noticed that in ef349c3d the author of this patch had to update their test to resolve the same problem.

**Comment by vibhansa-msft** [comment]
Interesting observation. Let us investigate on this. As we download the data and write to file handle provided my assumption is it may not always point to begining of the file, if there was an extra code to seek the offset back to 0 we need to check that part.

**Comment by vibhansa-msft** [comment]
We have identified the problem and will be fixed in our next release. That being said, this does not classify as a breaking change. From SDK standpoint breaking change is something where client application stops compiling due to a SDK change something like changing the API signature. As a solution we will keep the file pointer at a location where it was before the operation began,
