### ISSUE TITLE
Allow setting timeout in DefaultAzureCredential

### ISSUE THREAD

**Issue by preslavgerchev** [Azure/azure-sdk-for-go#22477]
### Feature Request

I am using the `DefaultAzureCredential`  struct in the `azidentity` package to support multiple ways of fetching credentials. I have observed that this randomly times out when running on VMs with an attached managed user-identity, spitting out the `managed identity timed out` error.  After digging through the code, it looks like the `NewDefaultAzureCredential` function uses an internal wrapper to wrap the `ManagedIdentityCredential` like this:
```
miCred, err := NewManagedIdentityCredential(o)
	if err == nil {
		creds = append(creds, &timeoutWrapper{mic: miCred, timeout: time.Second})
	}
```

Here's the link to find that code: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/default_azure_credential.go#L105

I suspect that the random timeouts are because the identity endpoint sometimes takes longer than a second to respond.

Would it be possible that this timeout is exposed so that it's made configurable? If not set, it can default back to 1 second.

For now, as a workaround, I have written my own wrapper as seen in https://github.com/Azure/azure-sdk-for-go/pull/19859 but ideally I'd like to avoid that as the code is almost identical to the one that can be seen in `NewDefaultAzureCredential`

**Comment by chlowell** [comment]
Thanks for opening this issue. That's a fine workaround if you want to continue using DefaultAzureCredential in production, but I suggest using a more specific credential type (at least in production) so your app's authentication behavior is more predictable and easier to debug when something goes wrong. We haven't made this timeout configurable because we think it's better for applications to use a different credential type when DefaultAzureCredential's behavior doesn't suit them. We intend DefaultAzureCredential to have a simple API and reasonable default behavior that helps developers get new applications working quickly. It isn't suitable in all scenarios and we don't want to try to make it so because each configuration knob adds complexity to getting a simple app off the ground and implies tweaking DefaultAzureCredential options is a good solution when it would be better to use a more specific credential type instead.
