### ISSUE TITLE
azidentity.validateTenantID returns true for empty tenant id

### ISSUE THREAD

**Issue by bcho** [Azure/azure-sdk-for-go#22544]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`

github.com/Azure/azure-sdk-for-go/sdk/azidentity

- SDK version e.g. `master`, `latest`, `18.1.0` 1.5.1
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `go list -m <module>`, for example `go list -m github.com/Azure/azure-sdk-for-go/sdk/azcore`.
- output of `go version`go version go1.21.3 darwin/arm64

- What happened?

In https://github.com/Azure/azure-sdk-for-go/pull/21883 , the refactor to  `validateTenantID` implementation changed the validation behavior on empty tenant id. Before the change, empty tenant id will result in validate error as the regex requires at least one character. The new implementation will simply return true for empty string.

- What did you expect or want to happen?

Return error for empty tenant id, or clarify the empty tenant id usage.

- How can we reproduce it?

- Anything we should know about your environment.

**Comment by chlowell** [comment]
Thanks for opening this! Can you please describe the behavior in your app that changed as a result of this? I want to make sure we test the right scenario(s).

**Comment by bcho** [comment]
@chlowell in our side we have some unit tests that expecting to reject empty tenant id, this is why we found this issue after upgrading the azidentity library. I believe it's not affecting the overall application behavior is not touched because we have other validations. But I would like to know what's the expected behavior here.

**Comment by chlowell** [comment]
The rule is, if a credential constructor has a tenant parameter, then `""` is an invalid value. It's reasonable to expect such constructors to continue returning errors when given an empty tenant ID, so I'll restore that behavior, and thank you for pointing out the change. Your PR is most of the way there but I'm not certain `validTenantID()` is the best place to address this (in some cases `""` is acceptable because the tenant is optional) and we should test the public API behavior, not its implementation. If you don't mind, I'll add some commits to your PR. In any case, we'll fix this with the next release.

**Comment by bcho** [comment]
Yep feel free to push to my pr :)
