### ISSUE TITLE
Azure Automation Expansion: Support Python Runbooks

### ISSUE THREAD

**Issue by hdost** [Azure/azure-sdk-for-go#2256]
### Feature Request
As of right now there is no support for python run books
This would be needed for terraform-providers/terraform-provider-azurerm#1602

**Comment by marstr** [comment]
Thanks for the input. Doing a quick scan through the specs repository, it's not clear to me whether or not we have an OpenAPI Spec for what you're referring to. If we do, I'll help get it generated or find our existing generation.

The closest thing I've found is in the Azure Automation RP, where they define a runbook type:
[Azure/azure-rest-api-specs/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/runbook.json](https://github.com/Azure/azure-rest-api-specs/blob/be9bf1a97d4e76df0c21652a854cda90ac187d1c/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/runbook.json)

**Comment by hdost** [comment]
That's a bummer, I am assuming this is because the Python Runbooks are still in preview :disappointed:

**Comment by marstr** [comment]
Doing a little more digging with @joshgav, I feel pretty confident that what's missing is a type "Python" in the enum linked below or a subsequent API Version. I'm going to close the issue here and move it over to the Azure Rest API Specs repository.

[Azure/azure-rest-api-specs/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/runbook.json#L1083](https://github.com/Azure/azure-rest-api-specs/blob/be9bf1a97d4e76df0c21652a854cda90ac187d1c/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/runbook.json#L1083)
