### ISSUE TITLE
[azidentity] Understanding when to cast error as credentialUnavailableError

### ISSUE THREAD

**Issue by anlandu** [Azure/azure-sdk-for-go#22662]
I'm trying to understand [this ChainedTokenCredential behavior](https://github.com/Azure/azure-sdk-for-go/blame/main/sdk/azidentity/chained_token_credential.go#L100) and [accompanying discussion](https://github.com/Azure/azure-sdk-for-go/pull/19733). My use case: we have a chain consisting of a ManagedIdentityCredential and a ClientSecretCredential. We pull the ID used for the MIC from envs. If the ID is blank, IMDS returns a 400:
```
"ChainedTokenCredential authentication failed\nGET http://169.254.169.254/metadata/identity/oauth2/token\n--------------------------------------------------------------------------------\nRESPONSE 400 Bad Request\n--------------------------------------------------------------------------------\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"Identity not found\"\n}\n--------------------------------------------------------------------------------\n"
```
In that case, we want to fallback to the CSC. However, as this is not a credentialUnavailableError, the chain never tries the CSC. I'm assuming I should just go ahead and create an MIC wrapper that wraps this particular error as a credentialUnavailableError? Or is there a reason I'm not considering that a 400 from MIC GetToken() is considered fatal? Thanks!

**Comment by chlowell** [comment]
That 400 from the IMDS token endpoint means managed identity was configured for the VM but your app couldn't get a token because it didn't include a required parameter. ChainedTokenCredential considers a response like that fatal because it could indicate a configuration error in your application and if that's the cause, we don't want to authenticate a different identity. [NewCredentialUnavailableError](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewCredentialUnavailableError) exists so you can decide which errors are fatal. You could use it to fall back to ClientSecretCredential as you describe but I recommend doing something simple like this:
```go
var (
    cred azcore.TokenCredential
    err error
)
if clientID, ok := os.LookupEnv("CLIENT_ID"); ok {
    cred, err = azidentity.NewManagedIdentityCredential(&azidentity.ManagedIdentityCredentialOptions{
        ID: azidentity.ClientID(clientID),
    })
} else {
    cred, err = azidentity.NewClientSecretCredential(tenantID, clientID, secret, nil)
}
```
That's short and to the point, doesn't require your app to interpret IMDS errors, and prevents authenticating an unexpected system-assigned managed identity.

**Comment by anlandu** [comment]
Thanks @chlowell, that would be an excellent solution but we have one more wrinkle :) We also run on Arc Kubernetes clusters, with a sidecar that intercepts IMDS calls and handles returning tokens, so we always need to have a ManagedIdentityCredential hanging around to attempt those calls in the case it's running on Arc. Of course, we could check whether it's running on arc, but I imagine at that point we're losing some of the benefits that a chain provides in terms of simplifying logic and maintainability.
