### ISSUE TITLE
Support for setting AZURE_CONFIG_DIR variable for AzureCLICredential via AzureCLICredentialOptions

### ISSUE THREAD

**Issue by juljaeg** [Azure/azure-sdk-for-go#22749]
### Feature Request

To better support multiple azure cli instances separated using the [AZURE_CONFIG_DIR](https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file) this variable should be passable using the options. It should be set when interacting with the azure cli.

In the long shot this will enable better integration with e.g. terraform provider and the azure cli when using multiple service principals logged into the azure cli but also in other automation processes.

The variable can be injected here: https://github.com/Azure/azure-sdk-for-go/blob/9f4c149f19874db605cecb5dd1428ee6968ac921/sdk/azidentity/azure_cli_credential.go#L144

**Comment by chlowell** [comment]
Just to make sure I understand, you want to write code like this:
```go
cred, err := azidentity.NewAzureCLICredential(&azidentity.AzureCLICredentialOptions{
	ConfigDir: "~/.config/azfoo",
})
```
and then we'd set `AZURE_CONFIG_DIR` for the az subprocess with the value of that field?

**Comment by juljaeg** [comment]
Yes, exactly :)

**Comment by chlowell** [comment]
🤔 off the top of my head the only potential problem I see with adding this option is that it depends on the credential acquiring tokens from a subprocess, because the underlying Azure CLI feature is controlled by an environment variable. The subprocess is an implementation detail today. I'm wary of making it an implicit part of the API because we could someday develop a better way to get tokens from the CLI, and I wouldn't want to choose between that and this option.

Can you share some details about the scenario this option would enable? You can of course set `AZURE_CONFIG_DIR` before running your Go program, so the unsupported feature here is instances of `AzureCLICredential` referencing different config files. What's blocked without that feature and how painful is it to work around its absence?

**Comment by juljaeg** [comment]
Thanks for your response and feedback 😀 Well for the use-case I have to take the long route and cover some technologies when explaining how this feature request became a viable solution for our problem: 

We are doing infrastructure deployments to azure and additionally to aks using terraform and the azurerm/kubernetes provider. We are doing this over Azure Pipelines and are authenticating using service connections configured with service principal and their secret key. We have multiple service principals e.g. per subscription/purpose.

From time to time some deployments are spanning multiple subscriptions to e.g. open firewall rules, configure something else or put e.g. vnet peerings. For that we are spinning up multiple instances of the azurerm provider using the alias feature of terraform and just give it the different service principal credentials so that we can work with multiple service principals at the same time. We extract the credentials from the service connection in the pipeline using the given example for the AzureCLI task in the documentation.

We are currently migrating to workload identity federation as advertised by Azure DevOps to make the credentials mangement more future proof. We are executing our deployments using a couple of terraform applies in one pipeline step which might take some time when there is e.g. an aks to create or some database to provision. The id tokens offered by Azure DevOps and extracted as described above are valid for only 10 minutes. This leads to authentication issues when following terraform applies in the same step try to use the previously extracted - but now invalid - id token.

HOWEVER we noticed that when doing an az login beforehand using the id token and point terraform to use the azure cli (internally this uses this sdk) we can authenticate more reliably and for longer amount of times, as it also automatically refreshes the acces token. I am not aware of any way to sign into azure cli with multiple identities at the same time besides using a different config directory, which resulted in this feature request: Being able to make the azure go sdk azure cli credentials account for different config directories to enable using the refresh and access token capabilities after logging in using a short lived id token. And all this from one process.

I hope everything was understandable and one can follow the explanation. If there are any further questiond please just ask :) Of course we encounter the same problem with other tools like e.g. kubelogin, but they all use the sdk at its core.

For your concern regarding a potential future implementation: I can not give a fully valid opinion on this as I dont have every view on this topic, BUT I see config/instance separation as an essential feature for azure cli installations. Its inherently a part of how the/a CLIs concept imo. So a future implementation might just change the technical way how you get the token but a similar conceptual mechanism will very likely remain. Maybe there is a way to mark this as experimental or in the future provide a backwards compatible parameter name/structure?

What do you think? If you have any alternatives feel free to bring them up :)

**Comment by chlowell** [comment]
Thanks for all the details! Let me summarize to make sure I understand what you're trying to do (please correct my mistakes):
- you're deploying ARM resources in an Azure DevOps Pipeline
- you tried using a service connection authenticated with workload identity federation
    - I guess you didn't use azidentity for this because it isn't directly supported? (though I think you could do it with [ClientAssertionCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ClientAssertionCredential))
- the OIDC token provided by the Pipeline, which you exchange for access tokens, expires after 10 minutes
- this is a problem because a task sometimes needs an access token after 10 minutes have passed
- as a workaround you acquire access tokens from the Azure CLI instead
    - ...which doesn't impose a time limit because it authenticates with a long-lived secret

Service connections look like the right approach, if not for the 10 minute limit. There may be a caching solution. Within 10 minutes, can your tasks determine all the Azure service APIs they will need to access?

**Comment by juljaeg** [comment]
Hi @chlowell, please don't see the request as stale. I am currently on vacation and will get back to you in about a week 😄 But already: thank you for your response 😊

**Comment by juljaeg** [comment]
Hi,

so I'm back. Our use case is basically to use two service principals, each responsible for one azure subscription. We use Terraform in that context which internally uses the azure sdk for go to authenticate. We want to e.g. grant managed identities created by identity a in subscription a access in rbac to resources in subscription b. For that the identity b must be used. We want to move away from static credentials. The workload identity tokens issued by azure devops are only valid for a short time which is problematic when multiple longer operations take place (e.g. provisioning clusters and other resources in multiple operations). When logging in azure cli using the token with two different `AZURE_CONFIG_DIR` variables one can login once and use the refresh/token management by the azure cli to enable a longer running operation. Using the sdk we can only use one (the default) config dir  aka one identity, which prevents us from using workload identity tokens.

So the last point in your list (as a workaround) needs to be corrected, as we use the azure cli to login using a workload identity token and are able to get tokens even after the 10 minutes expired.

Determining everything is quite a challenge as there are things depending on each other. And there is no guarantee that some operations take less than 10 minutes.

If you think adding the config dir as a parameter is not really future proof: How about a dedicated "profile" feature in the azure cli which incorporates this feature as first class citizen like the [aws cli does](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-format-profile)? I think this can be implemented in a good backwards compatible way. I am aware tho this is a different issue/project and a bit of a stretch for seeing it any time soon. But assuming it gets implemented, would it then be viable to introduce a `profile` attribute on the `AzureCLICredentialOptions`?

**Comment by chlowell** [comment]
> If you think adding the config dir as a parameter is not really future proof: How about a dedicated "profile" feature in the azure cli

I would feel better about this if it were a higher-level concept than "path to config file". Thinking of the CLI coming up with something new there makes me nervous about getting stuck with a file path option that later becomes redundant or insufficient because the CLI comes up with a more abstract profile idiom.

Where I was going with caching is that while the OIDC token provided by Azure Pipelines is valid for a short time, access tokens you exchange it for are valid for at least 1 hour. Provisioning resources and assigning RBAC roles are handled by the same API (Azure Resource Manager) and you can do both with the same access token. So if that's all you need to do, and you know the tenants you need to do it in, you could acquire all the tokens you need up front with [AzurePipelinesCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0-beta.4#AzurePipelinesCredential) before the OIDC token expires. The credential would cache the access tokens for you, giving you at least 1 hour to authorize everything. Is that feasible?

**Comment by juljaeg** [comment]
Okay, this is fully understandable. Was not aware that this functionality is more of a band-aid.

The AzurePipelinesCredential looks really cool and looks feasible! That feature is quite new right? As we are able to hook right before the execution we can obtain a token there and give that to the terraform provider. But wait, do we get an id token or an access token? For our use case an id token would be already sufficient. Based on https://github.com/Azure/azure-sdk-for-go/blob/4fd61cce02c1cd68dc66d314ce1205ccb93ad828/sdk/azidentity/azure_pipelines_credential.go#L97 we can just do something like this to get a fresh id token right? Exchanging that for an access token with the appropiate scope and so on will be done by the terraform provider using this sdk then. 1 hour seems enough for all of this. Are the other credentials automatically refreshing the access token before it expires after 1 hour? Just in case an operation takes longer than 1 hour.

**Comment by chlowell** [comment]
`AzurePipelinesCredential.GetToken()` returns an access token. It handles the DevOps id token internally; that's the code you linked. You could get id tokens the same way but I thought you had already tried and abandoned that approach because the OIDC endpoint returns a token that's valid for 10 minutes from the start of the job i.e. after 10 minutes you can't get a valid id token? If that's the case, `AzurePipelinesCredential` helps because it acquires and caches access tokens that outlive the id token and you need the access tokens because they authorize your ARM requests. But if you can get valid id tokens as needed for as long as a job runs, you don't need that help and `AzurePipelinesCredential` is just a convenience (maybe a large one).

To answer your other questions,

> That feature is quite new right?

Yes. The DevOps API is stable as of a couple weeks ago and `AzurePipelinesCredential` will soon follow, not in the next stable version (v1.6.0) but the one after that. The constructor API will change before its stable release.

> Are the other credentials automatically refreshing the access token before it expires after 1 hour?

Yes, `azidentity` credential types, except those which delegate to external tools like the Azure CLI, handle token refreshing internally. In this case Pipelines determines whether that can succeed though--`AzurePipelinesCredential` needs a valid id token to exchange for an access token.

> Are there already official plans for a "profile" feature in the azure cli?

None I'm aware of but I don't have any inside knowledge of the CLI team's plans. Their [GitHub repo](https://github.com/Azure/azure-cli) is a better source than me 😊

**Comment by juljaeg** [comment]
Thanks for your response. I fully understand that you want a higher level concept in the cli. 

The code in for the pipelines credentials already helps a lot as a guideline to do this on our own right before we need to have the token. We do not require the exchange into access tokens at the moment, because thats what the terraform provider will do internally using the WorkloadIdentityCredential. The credential in the terraform provider then also handles refreshes and so on and we are out of the equation there for the handling. The workload identity credentials is then also able to process the obtained oidc token when we write it to a file right?

**Comment by chlowell** [comment]
👍 great, I'm glad you have a path. Please feel free to open another issue if something else comes up.
