### ISSUE TITLE
azidentity: get RefreshToken and IDToken

### ISSUE THREAD

**Issue by guilhem** [Azure/azure-sdk-for-go#22776]
### Feature Request

Following #3804 and deprecation of [go-autorest](https://github.com/Azure/go-autorest), it would be good to have more information in `azcore.AccessToken`.

Like `id_token` or `refresh_token`.

#### Why

For example, current implementation of oauth2 in [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/azure.go) use client-secret. I would like to use workload identity for example.

https://github.com/oauth2-proxy/oauth2-proxy/blob/fc701bfd6a992bb074671b91ac89b50a79d3dc3d/providers/azure.go#L161

**Comment by chlowell** [comment]
We don't plan to include refresh or ID tokens in the azidentity API because it's designed to authenticate Azure SDK clients, which need only access tokens. I can add more context to that if it's helpful but I'm not sure it's relevant because workload identity doesn't involve refresh or ID tokens. Can you add some more detail about what you're trying to implement?
