### ISSUE TITLE
SQL Database API version is old

### ISSUE THREAD

**Issue by ThakkarChandresh** [Azure/azure-sdk-for-go#22824]
### Bug Report

I'm using the latest go sdk

_require github.com/Azure/azure-sdk-for-go v68.0.0+incompatible // indirect_

And I'm facing the issue, that when we use the _ListByServer_  API of the _DatabasesClient_ created using the 
"github.com/Azure/azure-sdk-for-go/profiles/latest/sql/mgmt/sql"
`sql.NewDatabasesClient()`

The response of the _ListByServer_ returns the list of databases but it does not contain the tags associated with that respective SQL database.

After debugging I've found that the SQL internally uses the 2014-04-01 API Version and in that API we're not receiving the tags in API response, but the latest API Version for SQL Database is 2021-11-01.

And in 2021-11-01 API Version we're getting the tags associated with respective SQL Database, hence in the SDK there is no way to use the latest API version of API

![image](https://github.com/Azure/azure-sdk-for-go/assets/81959466/73ca8eda-70e5-4a30-ad01-0cc4e1a4a674)

**Comment by jhendrixMSFT** [comment]
This is the legacy SDK which is outdated and no longer supported. You can find the latest SDK for SQL here.

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/sql/armsql/v2

**Comment by jhendrixMSFT** [comment]
For more info, any packages under the following directories are all from the legacy SDK which is out of support.

- github.com/Azure/azure-sdk-for-go/profiles
- github.com/Azure/azure-sdk-for-go/services
- github.com/Azure/azure-sdk-for-go/storage

**Comment by ThakkarChandresh** [comment]
@jhendrixMSFT Thank you for replying, just want to know that all these legacy SDK latest version are available or not?

**Comment by jhendrixMSFT** [comment]
If you're asking, do we have new SDKs that replace all of the packages in the legacy SDK, the answer should be yes. Only thing I can think of is if some service that's supported in the legacy SDK has since been deprecated.

Here are some migration docs that might help you.

https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md
https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/profile-migration-guide.md
