### ISSUE TITLE
[azidentity] ManagedIdentityCredential timed out when using azidentity.NewDefaultAzureCredential

### ISSUE THREAD

**Issue by kasathis** [Azure/azure-sdk-for-go#22859]
### Bug Report
DefaultAzureCredential: failed to acquire a token. 
Attempted credentials: 
ManagedIdentityCredential: managed identity timed out

SDK should support MSI cred in the default azure credential as well.

**Comment by chlowell** [comment]
DefaultAzureCredential does support managed identity authentication in production, however it also supports credentials for local development, which follow the production credentials in a chain. That is to say, DefaultAzureCredential tries the production credentials before the dev credentials. This creates a problem in local development, where no managed identity is available. DefaultAzureCredential has to try managed identity auth to determine it isn't possible, and that can result in a very long timeout before it falls back to a dev credential. So, DefaultAzureCredential imposes a 1-second timeout on its first attempt to authenticate a managed identity. This causes the timeout error you mention. You can avoid it by simply using ManagedIdentityCredential directly in production i.e., call [azidentity.NewManagedIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ManagedIdentityCredential) instead of azidentity.NewDefaultAzureCredential.

**Comment by kasathis** [comment]
We have strange scenario in our use case. Go SDK auth should support Environment credential and it should fall back to the MSI auth incase of missing required ENV vars like client secret. 
 
Due to the issue of managed identity timed out. We are ending up with writing the custom handling of this authentication. If you can write the fix in the SDK for handling both ENV and MSI auth in NewDefaultAzureCredential(It should do ideally). It saves us from maintaining the extra piece of code.

**Comment by chlowell** [comment]
> [DefaultAzureCredential] should support Environment credential and it should fall back to the MSI auth incase of missing required ENV vars like client secret

It does that today. However, as I described above, DefaultAzureCredential supports both production and local development scenarios. The short timeout on its first managed identity authentication attempt is a compromise between prod and dev that you can avoid by using ManagedIdentityCredential instead. Doing so shouldn't take much code and it's generally best to be explicit about an application's authentication mechanism because that makes authentication more predictable and robust, and easier to debug.

> We have strange scenario

Can you add some more detail to explain why this scenario can't be addressed by some combination of [EnvironmentCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#EnvironmentCredential), [ManagedIdentityCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ManagedIdentityCredential), and [ChainedTokenCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ChainedTokenCredential)?
