### ISSUE TITLE
[azidentity] DefaultAzureCredential: add exclude_managed_identity_credential, etc.

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-sdk-for-go#22866]
### Feature Request

There should be feature parity with the [Python SDK](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python).

Specifically I would like to use `exclude_managed_identity_credential`, `exclude_workload_identity_credential`, and `exclude_interactive_browser_credential` with `NewDefaultAzureCredential()`.

**Comment by chlowell** [comment]
Thanks for opening this issue. There are a couple big reasons we don't plan to add options like these. First, they would encourage people to try to make DefaultAzureCredential work in scenarios where it would be better to use a more specific credential type instead. Using a more specific type is generally the best approach in production because it makes authentication more predictable and robust, and easier to debug when something goes wrong. Second, they would needlessly complicate the API. There's no need to selectively disable parts of DefaultAzureCredential because all the credential types it uses are available separately and [ChainedTokenCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ChainedTokenCredential) enables building a similar chain of them.

**Comment by letmaik** [comment]
@chlowell That sounds reasonable. I think though those design principles should be established across the different languages, otherwise it becomes confusing why the Python SDK has the options and others don't.
