### ISSUE TITLE
Authentication to Azure not working in Dev Container

### ISSUE THREAD

**Issue by tgummerer** [Azure/azure-sdk-for-go#23058]
### Bug Report

```
$ go list -m github.com/Azure/azure-sdk-for-go/sdk/azidentity
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.5.1
```

When trying to authenticate to Azure with the Azure SDK (used in pulumi through the gocloud.dev library) in a dev container on Windows, the Azure SDK seems to try to connect to the IMDS authentication service, even though it is not reachable from the devcontainer.

This can be worked around using a SAS token, but that doesn't work in all cases.  I tried looking through the SDK a bit, but I'm not quite sure what makes it think it can authenticate through IMDS on a devcontainer.  

Here's a couple of related issues that were opened for `pulumi/pulumi` through which we noticed this, that also show a potential workaround.  Of course it would be nicer if this could "just work".
- https://github.com/pulumi/pulumi/issues/16319
- https://github.com/pulumi/pulumi/issues/11854

**Comment by chlowell** [comment]
This happens because `DefaultAzureCredential` tries to authenticate a managed identity via IMDS and the only way to determine whether IMDS is available is to send a request to it. Some component of Docker Desktop on Windows responds to IMDS requests with errors like the one you describe. `DefaultAzureCredential` doesn't have a reliable way to distinguish those errors from IMDS's and doesn't know whether you expected IMDS to provide an access token, so it considers the error fatal and stops trying to authenticate. The solution is not to use `DefaultAzureCredential` i.e., to use the credential type specific to your intended authentication method, or to provide service principal configuration for the container in environment variables [as described here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#EnvironmentCredential) so `DefaultAzureCredential` doesn't attempt to authenticate a managed identity.

**Comment by tgummerer** [comment]
Ah it's unfortunate that there is no better way to distinguish whether IMDS is available or not.  It's not possible to prioritize the credentials from `az login` either?

**Comment by chlowell** [comment]
That's possible at the application level--you can use [AzureCLICredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#AzureCLICredential) directly. If you mean prioritizing the CLI by reordering DefaultAzureCredential's constituents, we don't want to do that because it would break applications.

**Comment by tgummerer** [comment]
That makes sense, thank you!
