### ISSUE TITLE
Question: Is there any API to send metered billing for the managed application?

### ISSUE THREAD

**Issue by Imtiaz246** [Azure/azure-sdk-for-go#23108]
Is there any API to send metered billing for the managed application? 
Ref: https://techcommunity.microsoft.com/t5/marketplace-blog/metered-billing-with-azure-managed-applications/ba-p/3949576

**Comment by jhendrixMSFT** [comment]
I took a look but didn't find anything in the OpenAPI specs repo for that endpoint, but maybe I'm looking for the wrong thing. @sandeep-sen do you know?

**Comment by sandeep-sen** [comment]
[Metered Billing](https://learn.microsoft.com/en-us/partner-center/marketplace-offers/marketplace-metering-service-apis) is a part of [Microsoft Partner Center](https://learn.microsoft.com/en-us/partner-center/overview), it is not a part of Azure.
[Partner center developer docs](https://learn.microsoft.com/en-us/partner-center/developer/) states that they have Java and .NET SDKs in addition to REST APIs. They also have sample repos 

- https://github.com/microsoft/Partner-Center-DotNet-Samples
- https://github.com/microsoft/Partner-Center-Java-Samples

@Imtiaz246 you should check out these docs and examples.

Since this is a wrong repo for this service we are going to close this issue. I hope you will find correct guidance there.
