### ISSUE TITLE
DefaultAzureCredential broken in azidentity v1.6.0/v1.7.0

### ISSUE THREAD

**Issue by hamid-elaosta** [Azure/azure-sdk-for-go#23113]
### Bug Report

- "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
-  v1.6.0 and v1.7.0
- go version go1.22.4 linux/amd64

Using code almost identical to the sample found here: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/main/sdk/azstart/azstart.go?plain=1#L47

We have been able to manage secrets in AKV for some time using v1.5.2. Updating to v1.6.0 or v1.7.0 of the package breaks, while v1.5.2 works as expected.

The output when using v1.6.0 or above is as follows:

```
DefaultAzureCredential authentication failed. failed to acquire a token.
Attempted credentials:
        EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
        WorkloadIdentityCredential: no token file specified. Check pod configuration or set TokenFilePath in the options
        ManagedIdentityCredential authentication failed. ManagedIdentityCredential authentication failed. authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 404 Not Found
--------------------------------------------------------------------------------
not found
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 404 Not Found
--------------------------------------------------------------------------------
not found
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 404 Not Found
--------------------------------------------------------------------------------
not found
--------------------------------------------------------------------------------
```
Downgrading back to v1.5.2 works as expected.

See also for how I came across this issue: https://github.com/helmfile/vals/issues/441

**Comment by chlowell** [comment]
Thanks for opening this issue! I take it from the issue you linked that you want to authenticate via the Azure CLI? If so, the solution is to use AzureCLICredential directly i.e., call `NewAzureCLICredential()` instead of `NewDefaultAzureCredential()`. DefaultAzureCredential spans production and local development scenarios and doesn't have enough information to do the right thing in all environments, so it's generally best to use a more specific credential type instead.

To explain the error, DefaultAzureCredential tries a sequence of credential types until one returns an access token or a fatal error. It requests a token from an IMDS managed identity before `az`. Something in your environment responds 404 to IMDS managed identity token requests. DefaultAzureCredential can't know whether you expect these requests to succeed, so it considers the 404 a fatal error and doesn't try running `az`.

To explain why you see this error starting with v1.6.0, that's because of [this change](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/BREAKING_CHANGES.md#behavioral-change-to-defaultazurecredential-in-imds-managed-identity-scenarios). The doc doesn't mention this--it will after I update it--but the change also affected DefaultAzureCredential's retry behavior for IMDS managed identity token requests such that in your scenario, a nonfatal timeout in v1.5.2 became a fatal error in v1.6.0. The change made DefaultAzureCredential more reliable in apps deployed to Azure but has this side effect in your scenario. DefaultAzureCredential is a compromise between competing priorities and can't always do the best thing, so again I recommend using a more specific credential type instead.

**Comment by hamid-elaosta** [comment]
@chlowell Thanks for the explanation.

I want to authenticate by (az) CLI when I'm running on the CLI, but of course, not when I'm not; e.g. I'm running in a pod on AKS. I suppose this is the same reason the vals project used the same generic client we did, independently.

If I understand you correctly, its now up to the individual developer to handle the different environments and manage fallback scenarios where this was working previously?

One issue I'd query with the new behaviour is that it takes minutes to timeout with the error shown above; I can understand 404 errors being fatal if they must, but why hang for several minutes before doing so?

What would you suggest is the correct implementation if I want to be able to run with Azure CLI but also work with say workload-identity or similar?

**Comment by hamid-elaosta** [comment]
> Something in your environment responds 404 to IMDS managed identity token requests. DefaultAzureCredential can't know whether you expect these requests to succeed, so it considers the 404 a fatal error and doesn't try running az.

I've looked into this further in an attempt to fix our implementation, bearing in mind the documentation is all incorrect now this change in behaviour has been made.

If I use A `ChainedTokenCredential` as described here: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#readme-define-a-custom-authentication-flow-with-chainedtokencredential

The result, during local development, is that no error is thrown at credential creation, but the ManagedIdentityCredential will hang for ~ 1 minute and 44 seconds, before failing fatally, and no further credential in the chain is attempted.

I can't speak to why something in my environment responds with a 404, I'm on a corporate network, but even if DefaultAzureCredential should fail in this case (I don't agree), ManagedIdentityCredential shouldn't cause an entire explicitly-configured chain of credentials also to fail, particularly when best-practice for production is to have production-credentials attempted first. WorkloadIdentityCredential fails at credential creation if the environment is not configured, allowing a developer simply to not add it to the chain.

In lieu of updated documentation which provides a solution I can't see, I consider the behaviour of ManagedIdentityCredential broken, and the documentation agrees.

**Comment by chlowell** [comment]
You ask good questions asked and raise important issues, thanks for the comments.

> ManagedIdentityCredential will hang for ~ 1 minute and 44 seconds, before failing fatally

This is because it's attempting to acquire a token for an Azure VM managed identity. That would come from an HTTP service called IMDS which listens on `169.254.169.254`. Your corporate network evidently has some other service on that IP which responds 404 to IMDS token requests because it doesn't have a resource at the IMDS token URL. That's the expected HTTP behavior, no problem with that. However, [IMDS recommends clients retry on 404](https://learn.microsoft.com/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#error-handling). Because ManagedIdentityCredential is designed to support Azure authentication and can't tell whether it's running in an Azure hosting environment, it must assume the caller expects it to be able to authenticate and that responses to IMDS requests come from IMDS. That implies retrying 404s until it reaches its configured limit--this is what it's doing for 1:44--and treating that as a fatal error.

This scenario is an example of how `azidentity` sometimes has to make guesses and assumptions because it doesn't have enough information to do the best thing. Applications provide the necessary information by their choice of credential type. So if you want to authenticate via `az`, use `AzureCLICredential`. It won't try to authenticate any other way.

> best-practice for production is to have production-credentials attempted first

The best practice for production--and I'll update the documentation to make this clearer--is to use the specific credential type you expect to work in a given environment. That makes authentication predictable and errors easier to debug. You could write a wrapper to make ChainedTokenCredential work in your scenario but if your app tries authenticating a series of unrelated identities, its runtime behavior is less predictable and may have confusing or even dangerous failure modes. I recommend an explicit pattern like this instead:

```go
var (
	cred azcore.TokenCredential
	err  error
)
// test whatever condition makes sense for your app
if config.Production {
	cred, err = azidentity.NewManagedIdentityCredential(nil)
} else {
	cred, err = azidentity.NewAzureCLICredential(nil)
}
if err != nil {
	// TODO: handle error
}
```

> no error is thrown at credential creation

Constructors return errors for obvious problems like a required string argument being empty but don't do any I/O i.e., they don't try to authenticate. One returning a non-nil error therefore doesn't mean the credential it also returned can authenticate.
