### ISSUE TITLE
arm/resources: DeploymentProperties object seems slightly off for template/parameters fields

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#232]
Take, as an example:

https://msdn.microsoft.com/en-us/library/azure/dn790564.aspx

That page describes Template and Parameters as "complex types". The example shows the fields as being set to the actual JSON content of the template and deployment. 

Hence, where `azure-sdk-for-go` currently defines DeploymentProperties:

```
type DeploymentProperties struct {
	Template       *map[string]*string `json:"template,omitempty"`
	TemplateLink   *TemplateLink       `json:"templateLink,omitempty"`
	Parameters     *map[string]*string `json:"parameters,omitempty"`
	ParametersLink *ParametersLink     `json:"parametersLink,omitempty"`
	Mode           DeploymentMode      `json:"mode,omitempty"`
}
```

I would have expected:
```
	...
	Template       *map[string]interface{} `json:"template,omitempty"`
	...
	Parameters     *map[string]interface{} `json:"parameters,omitempty"`
	...
```

This also applies to DeploymentPropertiesExtended, and possibly others.

Alternatively, my expectations of the API are just wrong... and it's my responsibility to serialize the template/parameters first? But if that's the case, I'm not sure I understand why it's a map, rather than just a string.

**Comment by brendandixon** [comment]
Agreed. I am in the midst of making changes to the Autorest generator for Go anyway. I'll add this. Thanks!

**Comment by brendandixon** [comment]
BTW: This will be a general change. The challenge is that the Swagger defines such fields "objects" (in the JSON sense). The closest analogue in Go is a map[string]xxxx. I do not know why I chose to map to "map[string]string". It should be map[string]interface{}. (The pointer to string within the map was to handle JSON serialization in Go which, due to default values, cannot distinguish between the default case and the null case.)

**Comment by colemickens** [comment]
I can confirm the deployment functionality works as expected. Thanks!
