### ISSUE TITLE
Remove azservicebus ApplicationInsights-Go requirement

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-go#23283]
After #23231, Component Governance still flags `azservicebus` for requiring `yaml.v2@v2.2.1`, apparently because that version still appears in `go mod graph` output. The lowest-effort solution that comes to my mind is moving the `stress` package into a separate module under `testdata`, [like this](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity/testdata/managed-id-test).

**Comment by richardpark-msft** [comment]
Hm. I don't think moving it under testdata would be right because I want the project to be built along with the module it's testing.

I can think of a couple of other solutions:
* Update a fork of appinsights, and then use the fork's commit in the stress project (commits from forks are accessible from the main project)
* Migrate over to the OpenTelemetry exporter, which probably has the same issue, but isn't hosted in our repo. I've been wanting to do this one for awhile (based on @lmolkova's enthusiasm) so this might be the better long-term solution.

**Comment by richardpark-msft** [comment]
> > Migrate over to the OpenTelemetry exporter
> 
> I'm very excited about it :) Also would be very surprised if exporter needed yaml.

Looking at the repo I think this might be a case of an indirect dependency of a dependency of a dependency, which might explain why we can't override it like we've tried (maybe). I'm investigating now to see if I can do a cheap fix, then a better one later.

**Comment by richardpark-msft** [comment]
This has been done. We can bring telemetry back using the opentelemetry exporter.
