### ISSUE TITLE
feedback on azidentity/cache

### ISSUE THREAD

**Issue by dlorych** [Azure/azure-sdk-for-go#23471]
Came across the feature as I'm looking for a way to authenticate user with Entra, obtain necessary tokens from it and store them securely in between CLI executions.
In case of the API, user can be a human user (using DeviceCodeCredential or InteractiveBrowserCredential) or a machine users (using e.g. ClientSecretCredential or WorkloadIdentityCredential).

The cache supports DeviceCodeCredential and InteractiveBrowserCredential only at the moment.

CLI tools would benefit from caching also other access tokens. Is there a plan to support/cache for other credentials in the future?

**Comment by chlowell** [comment]
They already do; any credential type with a `Cache` option supports persistent caching. So, you can do this, for example:
```go
import (
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity/cache"
)

c, err := cache.New(nil)
if err != nil {
	// TODO
}
o := azidentity.ClientSecretCredentialOptions{Cache: c}
cred, err := azidentity.NewClientSecretCredential("tenantID", "clientID", "secret", &o)
```

Did you infer from the lack of an example like this in the docs that these types don't support persistent caching? I haven't written one because this scenario is much more straightforward than persistently caching user credentials. Maybe I should add a note to the user auth example to point out that other credentials support this feature, albeit with a different usage pattern?

**Comment by dlorych** [comment]
Hi @chlowell, that's great news.

Yes, possibly it is a lack of example or my lack of attention :). Providing an extra example, next to persistent caching could indeed make it more apparent.

Closing this one.
