### ISSUE TITLE
AzIdentity with Cache - logout?

### ISSUE THREAD

**Issue by DariuszPorowski** [Azure/azure-sdk-for-go#23499]
Hi there

I am trying caching (1.8.0-beta.3) for user context authentication - so far looks good. But I wonder how to do "logout"?
I assume that simply deleting the cache file does not solve the problem (it only contains user metadata) and the rest is in the encryption facility. So how to do "logout" and remove stuff from the encryption facility according to the user's operating system?

**Comment by chlowell** [comment]
Neither azidentity nor its underlying cache implementation has an API for logging users in or out because applications decide whether a user is logged in or not. azidentity only authenticates users, and the cache is just a simple data store; neither has a concept of a "logged in" user. azidentity does require an [AuthenticationRecord](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.8.0-beta.3#AuthenticationRecord) to access persisted user data, so at the application level "logging in" means authenticating a user and storing an AuthenticationRecord, and "logging out" means deleting deleting it.

Is it important for your application to actually delete cached data when a user logs out?

**Comment by chlowell** [comment]
Why do you need to delete the data? Sure, it's sensitive, but it's encrypted and the OS protects it from other users.
