### ISSUE TITLE
Add "Exclude" options to DefaultAzureCredentialOptions

### ISSUE THREAD

**Issue by daveneeley** [Azure/azure-sdk-for-go#23899]
### Feature Request

I have a use case for DefaultAzureCredential where my preferred authentication method is never attempted because a previous one succeeds. In my case, a github actions workflow runs on a private agent which uses a managed identity with generic permissions in the azure tenant. Within the workflow, azure CLI is used to login with a more appropriate client ID. However, the tool that I'm using calls `DefaultAzureCredential`, which does not check for the azure CLI login because the managed identity is present. This is similar to #23113, except that a `ChainedAzureCredential` that mimics `DefaultAzureCredential` could not be used in my case because the azure CLI login would still not be attempted.

This behavior of the azure identity client is also present in python and .net. But at least in those clients, there is a path to remove authentication methods in the chain. On python this can be done [by passing an exclude_ keyword in the constructor](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python#keyword-only-parameters), such as `exclude_managed_identity_credential`. In dotnet, there is a [DefaultAzureCredentialOptions class](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet) class that can be passed in the constructor.

The [sdk for go has no such options](https://github.com/Azure/azure-sdk-for-go/blob/bcb396b3e6c9cc7c48051f6fa0192b65e5d34ad4/sdk/azidentity/default_azure_credential.go#L21).

Potential actions:

1. Move the breaking change in azidentity to the next major release
1. In lieu of that, provide a default chained azure credential that works the way 1.5.2 and earlier worked
1. Provide similar DefaultAzureCredentialOptions to those in python and dotnet so that implementers such as [vals](https://github.com/helmfile/vals/issues/441) can expose these for their downstream consumers.

**Comment by chlowell** [comment]
Thanks for opening this issue. I'm sorry to close it right away, but we've exhaustively discussed these options and decided not to add them because they make DefaultAzureCredential needlessly complex and encourage developers to try to make it fit scenarios in which it would be best to build a custom credential chain with [ChainedTokenCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ChainedTokenCredential) or use a single, specific credential type. DefaultAzureCredential is great for getting started on Azure. We support that by keeping its API simple and encouraging developers to switch to a more specific type when they're ready for production (see e.g. [this doc](https://learn.microsoft.com/azure/developer/go/sdk/authentication/credential-chains#usage-guidance-for-defaultazurecredential)).

Stepping back from all that though, the tool in question doesn't need more DefaultAzureCredential options to address your need because all the credential types used by DefaultAzureCredential are available separately. The tool just needs to enable configuring its authentication behavior. I suggest asking the tool's developers to expose that configuration.

**Comment by daveneeley** [comment]
In my mind, DefaultAzureCredential is not for getting started until you're ready to move to production. It's for automatically supporting the 7 different authentication methods that Azure offers, plus any future ones, across an entire ecosystem of tools and multiple language SDKs. It's already in production everywhere and it's very, very nice.
