### ISSUE TITLE
[DataFactory] RepoConfiguration validation failure

### ISSUE THREAD

**Issue by hbuckle** [Azure/azure-sdk-for-go#2445]
### Bug Report

* import path of package in question - `.../services/datafactory/mgmt/2018-06-01/datafactory`
* SDK version - `18.0.0`
* output of `go version` - `go1.10.2 windows/amd64`

Trying to create a data factory with a repo configuration produces the following error

```go
accountName := "xxx"
collaborationBranch := "master"
projectName := "dftest"
repositoryName := "dftest"
rootFolder := "/"
tenantID := "xxx"
location := "northeurope"

dataFactory := datafactory.Factory{
	Location: &location,
	FactoryProperties: &datafactory.FactoryProperties{
		RepoConfiguration: datafactory.FactoryVSTSConfiguration{
			AccountName:         &accountName,
			CollaborationBranch: &collaborationBranch,
			ProjectName:         &projectName,
			RepositoryName:      &repositoryName,
			RootFolder:          &rootFolder,
			TenantID:            &tenantID,
		},
	},
}

_, err := client.CreateOrUpdate(ctx, resourceGroup, name, dataFactory, "")
if err != nil {
	return err
}
```

```
azurerm_data_factory.data_factory: datafactory.FactoriesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=factory.FactoryProperties.RepoConfiguration constraint=Null value=datafactory.FactoryVSTSConfiguration{ProjectName:(*string)(0xc042078750), TenantID:(*string)(0xc042078780), AccountName:(*string)(0xc042078720), RepositoryName:(*string)(0xc042078760), CollaborationBranch:(*string)(0xc042078730), RootFolder:(*string)(0xc042078770), LastCommitID:(*string)(nil), Type:""} details: field "factory.FactoryProperties.RepoConfiguration" doesn't exist
```

If I remove the `factory.FactoryProperties.RepoConfiguration` validation from CreateOrUpdate then the factory is created succesfully

**Comment by marstr** [comment]
@hbuckle, thanks for filing this. You definitely found a rough edge we should grind down.

By updating your `RepoConfiguration` to be a pointer as so: 

``` Go
RepoConfiguration: &datafactory.FactoryVSTSConfiguration{
```

What's tripping things up is that the methods `AsFactoryVSTSConfiguration`, `AsFactoryGitHubConfiguration`, and `AsFactoryRepoConfiguration`  found [here](https://github.com/Azure/azure-sdk-for-go/blob/4e8cbbfb1aeab140cd0fa97fd16b64ee18c3ca6a/services/datafactory/mgmt/2018-06-01/datafactory/models.go), are dangled off of `FactoryVSTSConfiguration` instead of type `*FactoryVSTSConfiguration`. This means that our validation checks to see if something non-nil-able is nil, causing this failure.

I'm going to open a generic issue that mentions this problem, and credit you for finding it. But I'll close this issue out since we have a simple work-around.
