### ISSUE TITLE
Figure out a way to eliminate `preview` directory

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#2451]
Sometimes packages are released in the wrong parent dir (i.e. preview not under preview directory or vice versa).  Then you have to deprecate one and deal with the headache.  For vNext release strategy figure out a way to eliminate the need for a preview directory.

**Comment by vladbarosan** [comment]
@jhendrixMSFT with a folder or not, we will need a way which package is stable or not ( i.e. sem ver doesnt apply to it ) as this is to reflect the API Specs repo.

Or we can decide not to pickup at all on the master release branch the preview packages

**Comment by tombuildsstuff** [comment]
@vladbarosan 

> with a folder or not, we will need a way which package is stable or not ( i.e. sem ver doesnt apply to it ) as this is to reflect the API Specs repo.
> Or we can decide not to pickup at all on the master release branch the preview packages

Whilst it could cause complicate things - would it make sense to provide a "weekly" release for Preview API's in a separate repo using date based releases, rather than having them in the main repo? That would allow this repo to follow SemVer (and the currently fortnightly-ish releases) without having to worry about breaking changes

I can understanding API's needing to change during Preview - however I feel like once an API reaches Public Preview it  should be fairly stable and thus shouldn't have breaking changes for either the Schema/it's Behaviour within the same API version - such that downstream consumers (incl. the Azure CLI) don't break and force users to upgrade? Given that currently each Preview defines it's own process here - I believe a common definition of how the Preview process should work for API's would be the best way to solve this?

Thanks!

**Comment by chamons** [comment]
Is this still an issue @jhendrixMSFT ? I'm having trouble finding the preview directory, and folks on the call didn't have any context.

**Comment by RickWinter** [comment]
Addressed in track2 with semantic versioning of modules.
