### ISSUE TITLE
Question: how can I filter out resources from an ARM template

### ISSUE THREAD

**Issue by kargakis** [Azure/azure-sdk-for-go#2617]
I want to iterate over an ARM template, filter out resources of a specific type, and apply the filtered template. How can I do this via the SDK? An example would be nice (btw this repo used to have examples but not anymore?)

**Comment by marstr** [comment]
Howdy, 

To answer half of your question, you can find our examples regarding resources (including ARM Template deployment) here: https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/resources. 

That said, I don't believe we have much tooling to support that scenario in our SDK. Could you tell me more about why you want to only deploy a partial template?

**Comment by kargakis** [comment]
Our template includes NSGs which are getting updated post-deploy by Azure as the LB services are created. When we try to apply the same template during an upgrade, the NSG updates performed by Azure are getting overwritten, resulting in a temporary outage (see https://github.com/openshift/openshift-azure/issues/329) so I wanted to filter out NSGs. Since we use a Golang template to generate the ARM template, I ended up doing the filtering during the generation of the ARM template. Although there have been other times I wanted to do some sort of filtering in Go on a deployment template (eg. another time I wanted to parse a template, filter the scale set, record its CSE value), I don't have any immediate need for this so feel free to close.

**Comment by marstr** [comment]
Thanks for expanding on this. I think the scenario you're describing warrants some attention from our Azure Networking team. Tools like Terraform work around this by not overwriting existing NSGs, and I'd love to see that same logic reproduced when an ARM deployment is issued.

Mind opening an issue in the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repository describing the temporary outage that you're seeing, @kargakis? That will help us escalate to the correct team. Feel free to mention me so that I can help follow up on it.

**Comment by kargakis** [comment]
> Mind opening an issue in the Azure/azure-rest-api-specs repository describing the temporary outage that you're seeing, @kargakis? That will help us escalate to the correct team. Feel free to mention me so that I can help follow up on it.

@amanohar and @jim-minter should have more info about it

**Comment by tariq1890** [comment]
+1 on this. My team would benefit from this as well.

**Comment by marstr** [comment]
I'm going to close this issue, but we'll note that there is demand for being able to work with ARM Templates in Go.
