### ISSUE TITLE
Dependency Vendoring

### ISSUE THREAD

**Issue by jen20** [Azure/azure-sdk-for-go#262]
Hi all. I appreciate this is a contentious issue, but it would be _very_ helpful to people using the library for ARM if you would stop vendoring Autorest and use the mainline version of it instead. The rationale for this is twofold:

1. The apparently accepted practice in the Go world if vendoring is required at all, only applications should vendor their dependencies and libraries should not. Since `azure-sdk-for-go` is a library it seems to contravene this. Alone, this would not be an issue, except...

1. The usage of Autorest is not as encapsulated as one might hope, so import paths proliferate through application code and must be specified as: `github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest` rather than `github.com/Azure/go-autorest/autorest` if this were not vendored. This breaks all of the standard Go tooling for people using your libraries - I've lost count of the number of times that `goimports` has imported the external package automatically and caused type errors during compilation.

**Comment by ahmetalpbalkan** [comment]
I feel the same for (1). We're doing path rewriting mostly because for any release of azure-sdk-for-go, we would like to snapshot all its dependencies as well. This makes me think maybe we should host `go-autorest` repository in this very repo and tag these altogether.

Other projects using `go-autorest` would still use godeps etc to vend only `go-autorest` directory from this repo and they'd be just fine as if it was on its own GitHub repository. What do you think @brendandixon?

**Comment by brendandixon** [comment]
@ahmetalpbalkan @jen20 I loathe path rewriting. I understand why it can be sometimes necessary, but it is a hack around Go's immature vendor strategy. If Go packages had a package.info or some such file defining dependencies and versions and so forth (as does nearly every other library available) this problem would not exist.

Ok. Stepping off of my soapbox.

I agree we should remove the path rewrites. I'm less convinced that we should host go-autorest as part of the SDK since it has other legitimate uses.

**Comment by jen20** [comment]
:+1: @brendandixon - I'm in agreement.

My view here is that if you want to snapshot the dependencies at the point of release the best approach might be to use `Godep` as part of the release generation process and commit the file - similar to the approach we take [with Terraform](https://github.com/hashicorp/terraform/tree/master/deps) such that interested people can restore them. For the most part I'd imagine people will run on the latest version though and deal with breakage incrementally (generally better than the big bang when you need a feature/fix IMO).

**Comment by ahmetalpbalkan** [comment]
@jen20 I agree. I guess we don't have many options to snapshot the release with its dependencies other than the method you mentioned from Terraform.

People should ideally `go get ./...` this repo and its dependencies, vend them, `godep save` them and stick to them until they need a fix or a new feature. When that happens, they can remove this repo (and its dependencies) and then `go get ./... && godep save` again. We just need to make sure _at any time master should be go-gettable/buildable with its dependencies_.

**Comment by ahmetalpbalkan** [comment]
I believe we solved this. We no longer vendor dependencies in azure-sdk-for-go and go-autorest. Instead we provide glide.lock files. Please close as you see fit @jen20.
