### ISSUE TITLE
Search Management Service ID missing

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#268]
The [search service](https://msdn.microsoft.com/en-us/library/dn911001.aspx) returns the following response object:

```
type ServiceResource struct {
	autorest.Response `json:"-"`
	Name              *string                    `json:"name,omitempty"`
	Location          *string                    `json:"location,omitempty"`
	Tags              *map[string]*string        `json:"tags,omitempty"`
	Properties        *ServiceReadableProperties `json:"properties,omitempty"`
}
```

This doesn't follow the normal convention of having the ID as part of the response. The documentation suggests the ID will be part of the return:

```
{
   "id": "/subscriptions/[subscriptionId]/resourceGroups/[resourceGroupName]/providers/Microsoft.Search/searchServices/[serviceName]", 
      "name": "service name", 
      "location": "service geo region", 
      "type": " Microsoft.Search/searchServices", 
      "tags": {
         "key": "value",
         . . . 
         },  
       "sku": { 
            "name": "free | standard | standard2" 
         }, 
      "properties": { 
		           	"replicaCount": 1 - 12, 
			           "partitionCount": 1 | 2 | 3 | 4 | 6 | 12 
              "status": "running | provisioning | deleting | degraded | disabled | error", 
              "statusDetails": "details of the status", 
              "provisioningState": "succeeded | provisioning | failed" 
       } 
}

```

**Comment by stack72** [comment]
I believe this may be due to the missing ID in this part of the Swagger definition:

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-search/2015-02-28/swagger/search.json#L380

IF this is the case, then I will open a PR to add it

**Comment by brendandixon** [comment]
@stack72 Yup, that'd be the reason. Opening a PR would help. Thanks.

**Comment by stack72** [comment]
@brendandixon I will open a PR as soon as I find an example of a swagger doc with an ID :)

**Comment by brendandixon** [comment]
@stack72 Look at this line https://github.com/Azure/azure-rest-api-specs/blob/master/arm-search/2015-02-28/swagger/search.json#L421. I believe that is what's missing.

**Comment by stack72** [comment]
@brendandixon thanks :) https://github.com/Azure/azure-rest-api-specs/pull/120

**Comment by brjohnstmsft** [comment]
@stack72 -- Very cool that you're working on a Go client for Azure Search. However, please keep the change in your own fork for now. We are using this Swagger spec for generating a C# pseudo-client that we use for testing the Azure Search .NET SDK, and as you can see, it's not ready for prime time. Changing this spec will likely break our tests.

**Comment by colemickens** [comment]
@brjohnstmsft I'm confused. If the API returns this field, why are you not interested in taking this change? The Swagger specs are used by other Azure teams as well - it's important that they reflect the actual live service.

Either [the REST documents](https://msdn.microsoft.com/en-us/library/dn832694.aspx) should be updated, or the Swagger spec should be, No?

**Comment by brjohnstmsft** [comment]
@colemickens It depends. Is the purpose of these Swagger specs to exactly capture Azure APIs, or is it to provide a model from which to generate high-quality client libraries? Sometimes these goals are in conflict. In this case, we (the Azure Search team) chose to omit ID since it didn't seem like it would serve a useful purpose in the client library (name is used as a unique identifier for resources everywhere in ARM, not ID). This decision was completely academic at the time we made it, because we didn't (and still don't) ship a management client library for Azure Search. Right now we use this spec to generate some C# stubs that we use to test our data plane .NET SDK.

@stack72 Can you tell me a bit more about your scenario? What are you using this spec for, and in what situations do you need the ID?

If we decide that adding ID is the right thing to do, I'd be happy to take the change, as long as we make sure that re-generating the code [in this project](https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/Search/Search.Management.Tests) doesn't break the Azure Search SDK tests.

**Comment by colemickens** [comment]
The Swagger spec intentionally doesn't describe the service accurately because you're using the Swagger spec to generate some test code? I'm not sure I understand how making the Swagger spec accurate could have any impact on tests, or rather, why tests would rely on something so fragile as "whether or not a field named `id` is surfaced in the object that is created".

An API that doesn't return an `id` field doesn't feel much like a REST API, to me. Azure already differs from what I perceive as mainstream REST, in that we don't have any sort of "link" fields on our resources or lists. Going further and removing what we do have (virtually the same thing in the `id` field), makes me feel we're even further from REST conventions.

In a more general sense, I just don't see why we would intentionally drop data from the response that was deemed necessary information when the API was created -- the ARM endpoints don't return it for no reason. As far as I can tell from looking at `azure-sdk-for-go`, the search service would be the one of only  specs to not surface the `id` field. And including this value doesn't make the generated client any harder to use.

> (name is used as a unique identifier for resources everywhere in ARM, not ID).

I also am very confused by this statement. In ARM, the information in the `id` field is a *superset* of the information in the `name` field. This is an identifier in the ARM world.: `/subscriptions/[subscriptionId]/resourceGroups/[resourceGroupName]/providers/Microsoft.Search/searchServices/[serviceName]"` while `[serviceName]` is not. Imagine if the user wants to take the "SearchService" object returned and persist it and restore it later. They'll never be able to get back to that resource with only the data returned by the code-gen'd client. But if it were the actual response from the service, the resource's full identity would be included.

Another reason: I don't know that much about SearchService, but in the networking stack, you have to create links between resources to create logical relationship. When creating those relationships, the ARM APIs require the full qualified ID... because it's the only way to unique identify the resource. This is another place where I should be able to just use the ID that was returned from my prior POST.

Finaly, I can't speak for @stack72, but at the very least, a number of other Azure SDKs are generated from the Swagger specs, which is why I'm interested in seeing them as accurate as possible. I would argue that any unfriendliness that results from an accurate Swagger specification indicates an unfriendliness in the API call itself, not the client. And I would like to see those fixed on the API side, rather than on the caller since not everyone is lucky enough to be using a generated, supported client. We already give outsiders to the Azure/ARM/AD ecosystem enough pain points.

**Comment by brjohnstmsft** [comment]
Let's unpack this, because we're starting to cover a lot of ground.

First off, thanks for the examples of practical usage of the ID field in the networking stack. I also buy the consistency argument, so in this case I agree we should add ID. My bad for having the PR closed before we had a chance to have this discussion. @stack72 , I'll have it re-opened and merged tomorrow (can't do it myself because I don't have write access to azure-rest-api-specs).

That said, there are many more problems with this particular Swagger spec than the missing ID field. I left it in a half-finished state many months ago because it was good enough for my purposes at the time. This is actually the first I've heard of anyone taking a dependency on this spec outside of the Azure Search team. I hadn't intended to revisit this particular spec for a while because shipping a management client is pretty low on our priority list (not many customers ask for it because most get by with ARM templates and our data plane client is *way* more important to our customers).

If other contributors want to finish adding all the missing features and fixing the idiosyncrasies of the arm-search spec, I'm happy to take those changes, but there are a couple things I think we need to figure out first:

1. Who is responsible for making sure that all downstream dependencies on the spec don't break? In the case of this PR there is likely no impact, but someone still has to re-run AutoRest to regenerate the C# code in azure-sdk-for-net and make sure everything still works. It's not a lot of work for this change, so to make things simple I'll do that this time. But in general, who takes this work? A contributor changing the spec won't necessarily be familiar with all the other languages and SDK projects.
2. If the service team (Azure Search) isn't responsible for creating a particular client like the Go client, then who is going to support it? Document it (not just references, but how-to articles on azure.com)? Keep it up-to-date as the REST API changes? AutoRest only gives you code and reference docs, not a complete product, so what exactly is the endgame for this client?

**Comment by stack72** [comment]
thanks @brjohnstmsft and @colemickens - FWIW, not having the ID actually breaks the convention so it's good to have this agreed on :)

Look forward to the merge coming!

P.

**Comment by brendandixon** [comment]
@brjohnstmsft I believe these is a misunderstanding regarding the Swagger. It *must* define the public API correctly, including all accepted and returned data. It cannot arbitrarily omit fields since that will, by definition, create code that breaks the API.

**Comment by brjohnstmsft** [comment]
@stack72, your PR has been merged. Sorry for the delay while we sorted this out.

@brendandixon Let's follow up offline on the question of the role of service teams in this spec work.

**Comment by brjohnstmsft** [comment]
One final comment: In the future, let's try to keep issues related to Swagger specs filed in the azure-rest-api-specs repo. I missed this thread because I wasn't watching this repo (I am now). Thanks.

**Comment by brendandixon** [comment]
@brjohnstmsft Agreed. Simple oversight this time.

**Comment by stack72** [comment]
Closing this - have written our own implementation to allow us to proceed
