### ISSUE TITLE
Question: SQL Database ARM Package

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#270]
Hi,

On the Azure [documentation](https://msdn.microsoft.com/en-us/library/mt163571.aspx) it seems to suggest that SQL Servers and Databases can be controlled by the ARM part of the SDK. This doesn't seem to be the case though

Is this a missing package or is the documentation wrong?

Paul

**Comment by brendandixon** [comment]
@stack72 Sigh. The documentation is likely thinking in terms of the .NET SDK only. The Go SDK relies, for all ARM services, wholly upon the Swagger available at https://github.com/Azure/azure-rest-api-specs/. We do not yet have a Go package since the SQL ARM Swagger is not yet present and / or ready.
