### ISSUE TITLE
Godoc for functions that handle polling for the user

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#293]
If we're dolling polling for x-ms-long-running stuff for the user, godoc should indicate that.

**Comment by brendandixon** [comment]
@ahmetalpbalkan Agreed, but the documentation for the SDK (unlike go-autorest) is generated. We cannot safely infer such behavior without injecting commentary whenever we see the x-ms-long-running attribute. I'm not sure how to squeeze that in...maybe append?

**Comment by ahmetalpbalkan** [comment]
I'm not familiar with how we generate code, but just appending a paragraph to godoc describing the behavior would be very useful.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I'll have @garimakhulbe inject some commentary on our next build.

**Comment by garimakhulbe** [comment]
Yes, its straightforward. I will add in next build.

**Comment by garimakhulbe** [comment]
This has been added in latest release. Please check.

**Comment by ahmetalpbalkan** [comment]
hah this looks great, thanks

> ![image](https://cloud.githubusercontent.com/assets/159209/14154845/a028456e-f673-11e5-806b-226c7428664f.png)

**Comment by brendandixon** [comment]
@ahmetalpbalkan @garimakhulbe The latter part is our hand-crafted text. The poor preceding sentence fragment is pulled, sigh, directly from the Swagger.

**Comment by ahmetalpbalkan** [comment]
@brendandixon yeah I figured, no big deal though.

**Comment by garimakhulbe** [comment]
Yeah. Not a high priority issue for now. Will see if we can improve it any way in next release.

**Comment by brendandixon** [comment]
@ahmetalpbalkan @garimakhulbe The improvement is to lean on the service teams and get them to write real English in their Swagger. Further, they'll need to adopt conventions (e.g., how the text begins) so that each generator can massage the text as needed to idiomatically fit it's documentation style (e.g., Go requires that all documentation begin with the method name...therefore, we need either a) know that the text begins with such or b) know how to manipulate the text so that we can automatically generate good text).
