### ISSUE TITLE
Godoc for List operation is potentially misleaiding

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#296]
func (Client) List

```
func (client Client) List(filter string, top *int32) (result ResourceListResult, err error)
List get all of the resources under a subscription.
```

filter is the filter to apply on the operation. top is query parameters. If null is passed returns all resource groups.

---

I don't think it really turns all resource groups. I think this only returns the first page as the server sends it. (I'm assume that in OData the server can set a maximum page size that forces the client to page.)

Is my assumption true?

If so, should we update the docs, or should we update the `List()` call so that it automatically pages if you pass `nil` for the `top *int32` parameter?

**Comment by brendandixon** [comment]
@colemickens This might be because we have to implement the OData support.

**Comment by marstr** [comment]
>I don't think it really turns all resource groups. I think this only returns the first page as the server sends it. (I'm assume that in OData the server can set a maximum page size that forces the client to page.)
> 
> Is my assumption true?

Your assumption is true. It returns to you a `ResourceListResult` of which the definition looks like this:
```
// ResourceListResult is list of resource groups.
type ResourceListResult struct {
	autorest.Response `json:"-"`
	Value             *[]GenericResource `json:"value,omitempty"`
	NextLink          *string            `json:"nextLink,omitempty"`
}
```
_Above code from [arm/resources/resources/models.go](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/models.go#L353)_

If `NextLink` is not **nil** then there are additional values that still need to be iterated over. 

That said, I believe the whole Azure SDK for Go team would agree that this is not as intuitive as it could be. What would you think of a future Azure SDK release where list results were returned as readonly channels? We could update go-autorest to take care of paging the responses for folks and because we'd be using channels, the threading required to make it happen could be completely opaque to the user.
 
Thoughts?

**Comment by colemickens** [comment]
>What would you think of a future Azure SDK release where list results were returned as readonly channels? We could update go-autorest to take care of paging the responses for folks and because we'd be using channels, the threading required to make it happen could be completely opaque to the user.

Hm. I guess if it was optional, maybe. A `GetAll` set of functions that do the paging would be fine. The channel would be an optimization on that for really huge results lists, I suppose. Interesting idea!

**Comment by marstr** [comment]
Alright, we've talked a little about what we could do to improve the results of List operations in general. At the end of the day, it basically means refactoring/rewriting the ms-pageable extension. At the moment, that would go on the backlog. (Though, personally, that's something that I would love to knock out as a hack-a-thon project or something.)

In terms of the original question, which is that documentation [like this](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/networkSecurityGroup.json#L185) is sorta misleading. It neglects to mention that while it does "return" all, it does so in chunks and requires multiple network hits. Even worse, at the moment, it requires surrounding code in a loop. However, it's not _wrong_, just sorta scummy and speaking logically instead of practically. I hate to say this, but if we're just talking about improving the docs, we should create more targeted documentation issues that bother us. For now, I'm going to close this issue. Please open it back up if you disagree with my evaluation of the situation.

**Comment by colemickens** [comment]
Hm, not sure what all was discussed, but I can leave the docs bugs be for now - the API signature makes it pretty obvious that there is paging the user needs to handle.

But... I still think it'd be pretty easy to generate a a real GetAll function that implements the same loop that every single consumer of the SDK is probably writing today as it were.

Will you keep an Issue open for that? :) Or do you want me to file it against `AutoRest` maybe since it would be a change in the C#/razor?

**Comment by marstr** [comment]
That is totally legit! I'll open one up against the AutoRest repository and see what I can do about it. :)
