### ISSUE TITLE
Exposing Error Messages

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#299]
Hi

Currently the SDK returns messages as follows:

```
* azurerm_virtual_machine.test: autorest:DoErrorUnlessStatusCode 400 PUT https://management.azure.com/subscriptions/d81fd384-a96c-4197-b121-bf0006119534/resourceGroups/acctestrg/providers/Microsoft.Compute/virtualMachines/acctvm?api-version=2015-06-15 failed with 400 Bad Request
```

To debug this, I need to use charles proxy when my API calls are happening. This error was actually:

```
{
    "error": {
        "code": "InvalidParameter",
        "target": "computerName",
        "message": "Linux host name cannot exceed 64 characters in length or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \\ | ; : ' \" , < > / ?."
    }
}
```

Using the SDK would be a lot easier if the error messages were exposed. IS this something that can be done?

Paul

**Comment by ahmetalpbalkan** [comment]
I remember we fixed this but apparently there's a regression (assuming you're on tip of master). We should be returning a typed error struct containing those details included in the response. @garimakhulbe @brendandixon PTAL.

**Comment by stack72** [comment]
@ahmetalpbalkan 

Was it a recent fix or quite a while ago? Thanks for the info

Paul

**Comment by ahmetalpbalkan** [comment]
@stack72 that was like 2 months ago. https://github.com/Azure/go-autorest/blob/master/CHANGELOG.md#v300 If your copy of the SDK uses `go-autorest-3.0.0` (`azure.WithErrorUnlessStatusCode()` in SDK methods) then you probably have the fix.

**Comment by garimakhulbe** [comment]
@stack72 Is this working for you now?

**Comment by stack72** [comment]
@garimakhulbe / @ahmetalpbalkan 

I am having to bump our version of the repo. We pinned the dep when master was broken for weeks and now there are a huge amount of changes needed since the change to the vendored packages and autorest

So having to trawl through those changes first

P.

**Comment by brendandixon** [comment]
@stack72 Ah, the joys of consuming beta code. Let us know how it goes!

**Comment by jen20** [comment]
@brendandixon for clarity here: is the Go client beta, or is the ARM API in its entirety considered beta?

**Comment by brendandixon** [comment]
@jen20 Just the Go SDK ARM packages. The ARM services are in varying states evident in the API version exposed (e.g., 2015-06-15-preview).

**Comment by stack72** [comment]
FYI, trying to use the newer version of the SDK is a complete nightmare. I have been trying to do this for 3 weeks now. The code has changes *so much* as the functionality has changed. the return types from the api are now `autorest.Response` - how can this be turned into an actual response?

**Comment by brendandixon** [comment]
@stack72 The APIs have returned autorest.Response objects for quite some time. autorest.Response wraps the http.Response object (see https://github.com/Azure/go-autorest/blob/master/autorest/client.go#L34).

**Comment by stack72** [comment]
So how do i get the ID of the resource?

Before I could do the following:

```
resp, err := cdnProfilesClient.Create(name, cdnProfile, resGroup)
	if err != nil {
		return err
	}
```

I could then access the ID by saying `resp.ID`

What's the new way? the examples folder have had this removed - https://github.com/Azure/azure-sdk-for-go/commit/9c6d88ffd9d12fac21805c33ad10b1716aabe355

**Comment by ahmetalpbalkan** [comment]
@stack72 This operation is a long-polling operation, just like Create Virtual Machine. The response does not actually return the ID, but the status of the long running operation. So internally this method's requests go like:

    PUT CDN Profile - GET status - GET status - GET status

The response of `PUT` contains ID, however it is an incomplete CDNProfile object, because the resource creation is still going on. With the breaking change, we started polling on the resource and returning the overall result of the Create operation.

It is exactly the same in .NET SDK as well, it's not going to return you ID either. We just made golang SDK do the polling correctly (before the breaking change, it wasn't polling until the creation was completed, so it had to be done) and consistent with .NET SDK (and other SDKs we have).

You just need to issue another `cdnProfilesClient.Get()`  to retrieve the ID.

**Comment by brendandixon** [comment]
@stack72 Got it. This change came because we had to completely rewrite handling of Azure asynchronous operations, of which cdn.ProfilesClient.Create is one (you can tell since it accepts a cancelation channel).

Azure asynchronous operations are not guaranteed to return the full state upon completion. For example, most of the ARM APIs poll against an OperationResource which conveys only completion / failure (vs. polling against the object itself). Since we could not reliably guarantee consistent results, we elected to no longer try and return them. You were getting lucky in the past. :)

Generally, to get what you need, follow up the Create with a Get. In this case, invoke cdn.ProfilesClient.Get(profileName, resourceGroupName). That should return what you need.

Ok?

**Comment by stack72** [comment]
Thank you both very much. I wasn't able to find anything about this in documentation and have been trying all sorts

**Comment by brendandixon** [comment]
@stack72 Ah, come on! We put a one line comment in the CHANGELOG! :P

We're hoping the SDK will begin stabilizing soon. We're actively working compatibility tests used by the other SDKs.
