### ISSUE TITLE
[Go] Provide sdk api for using resource ids

### ISSUE THREAD

**Issue by praveenvaltix** [Azure/azure-sdk-for-go#3080]
### Service Package Request

Hi,

I have a question on how resources are linked and exposed in Azure through the REST APIs/Go SDK. From my understanding every resource has a name and a resource ID. What I am noticing is that the Get APIs take the resource name while the references within a resource may refer to other resources through an ID. 

As an example, the compute.virtualmachines.Get() returns a VirtualMachine which has references to network interfaces and the network references to IDs. But there is no way to get a resource based on the ID. The only way to get the resources than is to scrape and save all the resource names/IDs and use APIs to retrieve.

Is my understanding correct or wrong?

Thanks,
Praveen.

**Comment by praveenvaltix** [comment]
I got some ideas after looking at https://gist.github.com/vladbarosan/fb2528754cbd97df51ca11fe7be27d2f

This is written by @vladbarosan

**Comment by praveenvaltix** [comment]
Thanks @vladbarosan for confirming.

I guess my follow up question is, to reduce boiler plate code for us developers, there should ideally be a Get APIs which take the resource id instead of the name. 

See below for e.g -

		resource, err := ParseResourceID(nicID)
		if err != nil {
			log.Printf("Error parsing resource id %v", err)
			return nil, err
		}

		// get nic info
		nicInfo, err := nicClient.Get(
			context.TODO(),
			p.ResourceGroup,
			resource.resourceName,
			"",
		)
		if err != nil {
			log.Printf("Error getting nic info %v", err)
			return nil, err
		}

If instead nicclient.Get() took an ID, we could have avoided the "ParseResource". 

Thanks for confirming though.

**Comment by vladbarosan** [comment]
Thanks @praveenvaltix for the feedback. We are considering various improvements for our next iteration and this is one of them.

**Comment by tombuildsstuff** [comment]
@vladbarosan given that Resource ID's _shouldn't_ be case-sensitive (but are in a bunch of places) - I feel like it'd be more helpful to expose a function which parses and returns the items needed for the Get call as a struct - rather than just accepting an ID (which, could fail given the casing is incorrect)? FWIW we have support for this within Terraform as [the `parseAzureResourceID` function](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/resourceid.go#L14-L103) - but it's not ideal (given not all ID's contain a Subscription ID, for example)

**Comment by ArcturusZhang** [comment]
Staled issue, closing

**Comment by tombuildsstuff** [comment]
@ArcturusZhang since this is a feature request, can this be re-opened? It'd be great to see this added to the Generator - since at the moment we're having [to do this ourselves](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/network_security_group.go#L9-L31) in each resource (which would also allow this SDK to subsequently validate all the components are present when building up / parsing a URI - which would allow consumers of the SDK to provide better validation without writing this by hand)

Thanks!

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang since this is a feature request, can this be re-opened? It'd be great to see this added to the Generator - since at the moment we're having [to do this ourselves](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/network_security_group.go#L9-L31) in each resource (which would also allow this SDK to subsequently validate all the components are present when building up / parsing a URI - which would allow consumers of the SDK to provide better validation without writing this by hand)
> 
> Thanks!

Reopened by request.

**Comment by stephengroat-dd** [comment]
Is there any movement on this?

i've been using https://godoc.org/github.com/Azure/go-autorest/autorest/azure#ParseResourceID, but it seems to be failing me on BlobContainer ResourceIDs, specifically with the ability to pull the StorageAccount from the ResourceID

**Comment by jhendrixMSFT** [comment]
Can you elaborate on the problem with parsing blob containers?

**Comment by Erouan50** [comment]
Hi,

I had the same issue navigating between resources using the ID instead of the name until I found this issue. While you may work on a solution to accept ID and name in the `Get` method, it might be a good idea to add in the documentation an example that shows how to properly extract the ID from the name with the function `ParseResourceID`. It took me a while to find this issue and document it could same some precious time to other :).
