### ISSUE TITLE
arm: "Create" API methods no longer return model types

### ISSUE THREAD

**Issue by axw** [Azure/azure-sdk-for-go#326]
As of f704479992cd6232ab22c70717feb4ba6532f2b0, Create(OrUpdate) methods only return autorest.Response, and never the model types that are being created.

e.g. arm/compute.VirtualMachinesClient.CreateOrUpdate used to return a compute.VirtualMachine, but now returns only an autorest.Response.

Was this intentional? What's the rationale? What's the correct/recommended way to obtain the details of the created entity? I'd prefer not to have to make a Get call if I can avoid it.

**Comment by ahmetalpbalkan** [comment]
@axw yes this was very much an intentional decision. I will try to explain the rationale rather in detail, hoping this will serve as a reference to similar discussions in the future:

When you make a call the REST API corresponding to the `VirtualMachinesClient.CreateOrUpdate`, we often return you 201 Created response with a JSON object reflecting _partial_ details of the VM you just requested to be created. The response to single REST invocation indicates that Azure received your creation request; not the VM is actually created (it may fail to create later on). We call such APIs "long running operations".

The response from such endpoints often contain `Azure-AsyncOperation` header and the clients are supposed to poll the URL indicated in this header to learn more about the status and the result of the operation (i.e. Succeeded or Failed or some other outcome) for a period of time or indefinitely. 

Previously our SDK did not actually wait for the resource to be created (or failed to be created) and this was not intended at all. Now this SDK in fact queries the operation progress endpoints and returns to the caller when the resource is successfully provisioned/ready to use (or failed) –the correct behavior which should have been implemented in the first place.

However, there's a gimmick: When we PUT a resource (e.g. Create Virtual Machine) the resource (.e.g Virtual Machine) JSON object we get back is almost always incomplete or does not reflect the reality when the resource is ready to use. This is because the resource is not fully provisioned yet.

When we changed the SDK to PUT the resource and then GET the operation status (and poll until it is complete), we lost access to the resource properties JSON object (e.g. the response of Get Virtual Machine) because the API which gives the operation status has a very simple response such as:

    {"status":"InProgress"}

Therefore when it turns into `{"status" : "Succeded"}`, we need to retrieve the resource properties (GET Virtual Machine) to return you that type we were returning before. However some callers may not need this and putting a GET call on the client-side does not make the code very long or unmanageable. Therefore we err on the side of making less implicit requests on caller's behalf.

I hope that makes it more clear.

**Comment by axw** [comment]
@ahmetalpbalkan Thanks for the explanation. We really only care about the IDs returned, so I think we'll just create them "by hand" now. It would be nice if they at least could be returned from Create(OrUpdate) calls, so clients don't have to choose between crafting them and making an additional HTTP request.
