### ISSUE TITLE
subscriptions.NewClientWithBaseURI no longer exists

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-go#356]
I updated to v3.0.0-beta, and the only issue I hit was that subscription.NewClientWithBaseURI no longer exists.  This method was being used to construct a subscription appropriate to the target cloud, which may be any of the sovereign clouds already supported or for Azure Stack.  

I can recreate it like so, but the convenience was nicer the other way.

```go
client := subscriptions.Client{
		subscriptions.ManagementClient{
			Client:     autorest.NewClientWithUserAgent(subscriptions.UserAgent()),
			BaseURI:    baseURI,
			APIVersion: subscriptions.APIVersion,
		},
	}
```

Is this expected?  Is this the best way?

**Comment by colemickens** [comment]
I had noticed the same thing and pointed it out, but apparently it was by-design.

It bloated my code a bit, https://github.com/colemickens/kubernetes/blob/9e6a86b013765e564332dfc786ce939cfec78eb5/pkg/cloudprovider/providers/azure/azure.go#L80 an extra 8 lines since I have to have 8 different clients. Not the end of the world, but not great either - somewhat of an unnecessarily breaking change.

**Comment by brendandixon** [comment]
@colemickens What was the "by design" reason given? Removing the convenience method does not, at first blush, feel like the right choice.

**Comment by colemickens** [comment]
My comment: https://github.com/Azure/azure-sdk-for-go/pull/350#issuecomment-229238954

Follow-up: https://github.com/Azure/azure-sdk-for-go/pull/350#issuecomment-229391112

I guess it wasn't explicitly declared as by-design...

**Comment by garimakhulbe** [comment]
NewxxxxClientWithBaseURI methods are added back in latest release.
