### ISSUE TITLE
Requesting metrics insights API version 2018-01-01

### ISSUE THREAD

**Issue by tariq1890** [Azure/azure-sdk-for-go#3682]
The azure management endpoint of metrics insights is available for use with API version 2018-01-01.

This should be made available in azure-go-sdk as well.

**Comment by jhendrixMSFT** [comment]
We have `2018-09-01` here:
`
github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-09-01/insights
`
It's incorrectly classified as `preview` which I'll get fixed.  Can you use this API version or do you need `2018-01-01`?

**Comment by tariq1890** [comment]
Any new version that is in a `not preview` stage would be fine I guess :)

**Comment by tariq1890** [comment]
Looking forward to the moving of the 2018-09-01 version

**Comment by jhendrixMSFT** [comment]
Unfortunately this isn't as clear-cut as I thought.  The `2018-09` package is marked as `preview` because a subset of it contains preview content, see the authoring [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/readme.md#tag-package-2018-09).

**Comment by 804873052** [comment]
Hi @tariq1890  thanks for this issue!

The latest monitor is https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/monitor/mgmt/2021-07-01-preview/insights
