### ISSUE TITLE
Media Service Account ID's (not Resource ID's) don't get deserialized correctly

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#4124]
### Bug Report

Using v25.1.0 of the Azure SDK and this package:

```
"github.com/Azure/azure-sdk-for-go/services/mediaservices/mgmt/2018-07-01/media"
```

We've noticed that when creating a Media Services Account, we get the following response back from the Create/Get API calls:

```json
{
	"name": "acctestmsapqbia",
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/190222141804566116/providers/Microsoft.Media/mediaservices/acctestmsapqbia",
	"type": "Microsoft.Media/mediaservices",
	"location": "West Europe",
	"properties": {
		"mediaServiceId": "995656da-aa0b-41bb-a1f8-e8199daef04f",
		"storageAccounts": [{
			"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/190222141804566116/providers/Microsoft.Storage/storageAccounts/acctestsa1pqbia",
			"type": "Primary"
		}]
	}
}
```

However when deserializing this, it appears [the `resp.ServiceProperties.MediaServiceID` field](https://github.com/Azure/azure-sdk-for-go/blob/v25.1.0/services/mediaservices/mgmt/2018-07-01/media/models.go#L8589) isn't being deserialized correctly and comes back as nil.

Is there a particular reason this is being returned as a UUID rather than a String? Whilst that's technically the correct underlying value, I'm not sure it particularly makes much difference to users of the SDK?

Thanks!

**Comment by jhendrixMSFT** [comment]
Using your provided response body, I tried to unmarshal it into a Service struct and it works as expected.  Maybe there's more to the repro?
The decision to use `uuid.UUID` instead of `string` was before my time on the SDK so I don't know why this decision was made.  Unfortunately changing to `string` would be a pretty significant breaking change so I suspect we're stuck with this for now (if we ever do a "next gen" side-by-side SDK we can revisit this).

**Comment by ArcturusZhang** [comment]
No further response from the customer, closing this one.
Feel free to reopen or raise new issues if any other questions occur.
