### ISSUE TITLE
Stop releasing as "-beta"

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#432]
Is there a plan to stop using suffix `-beta` in release names/tags? I know we still make a ton of breaking changes but that does not make it a `-beta` really.

Many products and customers are using Go SDK in production for quite a while, as well as some of the new internal services that are ramping up nowadays. We feel confident using it just fine. And it's in top 3 in terms of requests sent to the ARM FrontDoor. I'm thinking maybe it's not a `-beta` anymore?

**Comment by mcardosos** [comment]
:D
Our plan is to release a non beta version in spring

**Comment by stack72** [comment]
Spring 2017? That means that the SDK will have been in beta for well over a year - why is this the case?

**Comment by eduardkoller** [comment]
We have a set of internal criteria for lifting the beta tag. Once the criteria are met, we will release without the beta.

**Comment by tombuildsstuff** [comment]
@eduardkoller out of interest - are the criteria that you refer to publicly available?

**Comment by colemickens** [comment]
+1 for being open about the exit criteria for moving from beta to stable.

**Comment by tombuildsstuff** [comment]
@eduardkoller is there any update on this?

**Comment by marstr** [comment]
I've just opened up issue #517 which I hope, at least when resolved, answers this question.

For now, I'm going to close this issue, because I hope that the conversation I just mentioned addresses the community's concern about both release status and transparency. Feel free to re-open or start a new thread if you do not feel this has been properly addressed.
