### ISSUE TITLE
Come up with a servicing story for a given SDK version

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#448]
Need to define a servicing story for a given SDK version (branch structure, code flow, versioning etc).

**Comment by marstr** [comment]
Well, there are handful of givens that I think we might as well enumerate.
Assuming that #517 resolves to have some sort of semantic versioning:

- The latest major version will be in support unless the whole product falls out of support.
- Individual patches are never altered, the support story is to adopt the most recent patch in the support band.
- We may allow ourselves to have multiple support bands. I.e. Just because there is a major version 7 doesn't mean we won't publish more minor version releases for version 6. However, the back support may be limited to supporting more services or making security patches.
- Our version numbers will not be directly tied to the Azure Service version numbers. As much as possible, if Azure is still supporting a means of calling them, we would like to support it. (Despite the fact that this is not how things work today)

Assuming that we decide not to use semantic versioning:

- At that point, all of our bits would be identified by Git branches and commit hashes alone.
- Each support band would be captured by a branch. (Though, at the moment nothing comes to mind in terms of support bands outside of master)
- Inside of a support band, the support model would always be, "take the latest commit or switch support bands."
- We would still like to devise a way of targeting the different Azure versions.

So, hopefully the above narrows the question we have to answer to, "How long will we support different support bands?" For instance, in semantic version world, the question is: "How many major versions back do we support?"

**Comment by marstr** [comment]
To close this issue, we'll need to modify the README to have a section on our servicing story.
