### ISSUE TITLE
SoftwareUpdateConfigurationsClient

### ISSUE THREAD

**Issue by OffColour** [Azure/azure-sdk-for-go#4516]
### Bug Report

"github.com/Azure/azure-sdk-for-go/services/automation/mgmt/2017-05-15-preview/automation"

I'm new to the SDK, so I could be wrong here on naming standards, but it seems odd that SoftwareUpdateConfiguration has the plural SoftwareConfiguration**s**Client

**Comment by jhendrixMSFT** [comment]
Hello!  The packages in this SDK, excluding the `storage` package, are generated from [swagger specs](https://swagger.io/docs/specification/about/).  In our swagger authoring, the convention for operation IDs is to use a `noun_verb` pattern where the `noun` is plural; you can find out more about why we recommend this [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r2063-operationidnounconflictingmodelnames).
In this case you can see and example [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/preview/2017-05-15-preview/softwareUpdateConfiguration.json#L58) where the operation ID is `SoftwareUpdateConfigurations_Create` which is why we end up with a type named `SoftwareUpdateConfigurationsClient`.
