### ISSUE TITLE
Question: How often this SDK is updated to match changes in azure-rest-api-specs?

### ISSUE THREAD

**Issue by uthark** [Azure/azure-sdk-for-go#505]
Hi! 

Sorry for creating an issue, I wasn't able to quickly find other way to connect with the developers.

My question is the following: how long does it take to update SDK for GO to be update to match changes in Azure REST API Specs?

I submitted pull request (https://github.com/Azure/azure-rest-api-specs/pull/789)  which was merged month ago but I don't see the changes propagated to this repo.

Other thing that I noticed is that AutorestCI automatically created PR for some SDKs (Python (https://github.com/Azure/azure-sdk-for-python/pull/928) , Ruby (https://github.com/Azure/azure-sdk-for-ruby/pull/633) , Node (https://github.com/Azure/azure-sdk-for-node/pull/2013) ), but not for SDK for Go.

I have a patch for other project that depends on this fix, so I'm wondering how long will it take to make the original fix to propagate to this repo.

What's more interesting, is that it is only one-line fix and complete patch for SDK for go looks like this:

```

diff --git a/arm/compute/models.go b/arm/compute/models.go
index 80570cb..9342986 100644
--- a/arm/compute/models.go
+++ b/arm/compute/models.go
@@ -1123,6 +1123,7 @@ type VirtualMachineScaleSetVMProfile struct {
 // machine scale set virtual machine.
 type VirtualMachineScaleSetVMProperties struct {
        LatestModelApplied *bool                       `json:"latestModelApplied,omitempty"`
+       VMID               *string                     `json:"vmId,omitempty"`
        InstanceView       *VirtualMachineInstanceView `json:"instanceView,omitempty"`
        HardwareProfile    *HardwareProfile            `json:"hardwareProfile,omitempty"`
        StorageProfile     *StorageProfile             `json:"storageProfile,omitempty"`
```

**Comment by marstr** [comment]
Howdy @uthark,

To answer your question: In general, we generate a new SDK from the current api's once every month. We are slated to do so again in a couple of weeks on January 31st. As you pointed out however, your changes haven't been picked up because due to the holidays we didn't release in December.

However, there is a more important point here, which is: "Why wasn't it easy to find the answer to these relatively straight forward questions?" To which there is no particularly good answer.

There is good news though, as we're planning on overhauling this project and making everything more transparent. In the next few days, I'm going to publish some thoughts on how I'd like to restructure the repository for public comment. As part of that conversation, I'm explicitly going to bring up how we could tie automatic PRs to the Azure SDK for Go.

-Martin

P.S. I'll leave it up to you to close this issue, don't do so until you feel your question has been adequately answered.

**Comment by uthark** [comment]
Hi Martin,

My thoughts are the following:

1. Having documented process of how the changes are propagated to this repo is good. 
1. As a I see, some parts of the repo are auto-generated from `go-autorest`, so it would be nice at least to have this documented (i.e. if you find issue in the API, then spec should be fixed, I had to figure out it manually, although I found repo https://github.com/Azure/adx-documentation-pr which is not publicly accessible)
1. Since it is a go, and to get dependency I need to specify exact commit id, it would be nice if on-going changes from spec repo will be merged more often than once a month.

I'm going to close the issue since my initial question was answered (expected release date is Jan 31st)
