### ISSUE TITLE
Update API version of ARM compute client to 2016-08-30 (at least)

### ISSUE THREAD

**Issue by moritzheiber** [Azure/azure-sdk-for-go#525]
Working with Virtual Machine Scale Sets with Ubuntu using this SDK isn't very easy since it neither allows for Scale Sets to carry extensions, nor, [since the compute API is using an outdated version](https://github.com/Azure/azure-sdk-for-go/blob/master/arm/compute/client.go#L29-L35), modification of `customData` passed to each instance.

However, `customData` is the only way of passing data to Scale Set instances using the go SDK. This means modifying the `customData` property will only work if you take down the Scale Set prior to modification.

[API version 2016-08-30 does support modification of the `customData`](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/2e81dd6a-1741-48aa-ab02-fc5c8c4450c1/how-to-update-vm-scale-sets-customdata-without-down-time?forum=WAVirtualMachinesforWindows#ed3246c3-2109-4443-881c-2da88705a908) property and I'ld vouch for a bump in API versions in the compute client, if possible.

//cc @pellepelster @fbernitt

**Comment by marstr** [comment]
Thanks for raising this issue. Unfortunately, this issue is outside of this scope of this repository for now. I've gone ahead and transferred this to the Azure Swagger repository, and we will follow up with the relevant teams.

For now, I'll close this issue. If you believe that the linked item above doesn't represent your issue, feel free to re-open this issue.
