### ISSUE TITLE
Breaking changes in v8.0.1-beta

### ISSUE THREAD

**Issue by stack72** [Azure/azure-sdk-for-go#542]
Hi

It looks as though some packages are missing in the 8.0.0/8.0.0-beta releases. The terraform codebase is now complaining as follows:

```
builtin/providers/azurerm/config.go:42: undefined: compute.UsageOperationsClient
builtin/providers/azurerm/config.go:77: undefined: resources.Client
builtin/providers/azurerm/config.go:87: undefined: redis.Client
```

This relates to the following code:

```
usageOpsClient         compute.UsageOperationsClient
resourceFindClient  resources.Client
redisClient redis.Client
```

Where have these clients disappeared to?

Paul

**Comment by mcardosos** [comment]
`UsageOperationsClient` got renamed to `UsageClient`.
In resources, `Client` got renamed to `GroupClient`.
In redis, `Client` got renamed to `GroupClient`.

**Comment by marstr** [comment]
To add to what @mcardosos pointed out correctly:
We're going to be publishing more information on this soon, but when we generated the latest release there were a lot of name changes introduced. We backed out all of the changes where there was no additional value brought. However, the packages you mentioned above had the some changes (largely removing blocking validation changes) that warranted publishing despite the name change.

The majority of the new names we really do feel are better, so next month we're going to go through with the name changes. However, before we do we're going to come up with a complete list of those changes and give folks a heads up.

Long term, we're working on figuring out some policies and infrastructure to improve our release story so that this kind of thing becomes rare.

**Comment by stack72** [comment]
Hi @mcardosos / @marstr 

So are you saying I shouldn't change my code yet? Or should i change now and then be prepared for more changes later?

Paul

**Comment by marstr** [comment]
The changes mentioned above will not be backed out. There will be additional packages that have similar name changes next month.

**Comment by stack72** [comment]
k thanks - when it comes to the release notes, please can these be marked on them? 

Thanks

**Comment by marstr** [comment]
Request noted, thanks @stack72
