### ISSUE TITLE
Rename doesn't work for `storagedatalake#PathClient.Create`

### ISSUE THREAD

**Issue by kahing** [Azure/azure-sdk-for-go#5550]
From https://github.com/Azure/azure-sdk-for-go/issues/5502#issuecomment-521840401

during rename, the source object needs to be url escaped (url.PathEscape), otherwise you get 400 InvalidSourceUri

**Comment by loarabia** [comment]
Triaging and assigning out per comment in other issue.

**Comment by jhendrixMSFT** [comment]
Unfortunately swagger doesn't have a way to describe that a value should be URL-encoded and we cannot simply URL-encode all header values.  I suspect the best we'll be able to do here is update the description for this header indicating that it must be URL-encoded.

**Comment by jhendrixMSFT** [comment]
Looks like the docs already mention that this must be URL-encoded.

> // xMsRenameSource - an optional file or directory to be renamed.  The value must have the following format:
// "/{filesystem}/{path}".  If "x-ms-properties" is specified, the properties will overwrite the existing
// properties; otherwise, the existing properties will be preserved. This value must be a URL percent-encoded
// string. Note that the string may only contain ASCII characters in the ISO-8859-1 character set.
