### ISSUE TITLE
no buildable fo source file for  dns/mgmt/dns

### ISSUE THREAD

**Issue by Azee77** [Azure/azure-sdk-for-go#5575]
Log : github.com/coredns/coredns/plugin/azure/azure.go:16:2: no buildable Go source files in /some_path/src/github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns

Building was started externally into this directory via coredns and got above error.

**Comment by ArcturusZhang** [comment]
Hi @Azee77 , this should be a dependency issue not an issue caused by go sdk. I noticed `github.com/coredns/coredns` uses go modules, so please make sure the dependencies are in their right places, conventionally should be `$GOPATH/src/github.com/Azure/azure-sdk-for-go`. You can try `go get -u github.com/Azure/azure-sdk-for-go/...` in your working directory to update your dependencies, or just clone the sdk repo in `$GOPATH/src/github.com/Azure/`.
BTW, we do not recommend to use `profile/latest` as dependency, which will also point to the newest version and may occur breaking changes time to time.

**Comment by Azee77** [comment]
@ArcturusZhang thanks. I did the same, still faced the error. Maybe due to profile/latest. I commented the azure code from coredns.
