### ISSUE TITLE
submodule file conflicts break glide/git

### ISSUE THREAD

**Issue by vikstrous** [Azure/azure-sdk-for-go#581]
We use glide to vendor this repo and a recent change broke glide's ability to depend on old versions of this repo.

The issue is that glide clones the latest version of Azure/azure-sdk-for-go and then tries to check out an old version. When it does that, it gets the following errors:

```
[ERROR]	Failed to set initial config references: Unable to update checked out version
[DEBUG]	Output was: error: The following untracked working tree files would be overwritten by checkout:
	storage/blob.go
	storage/blob_test.go
	storage/client.go
	storage/client_test.go
	storage/file.go
	storage/file_test.go
	storage/queue.go
	storage/queue_test.go
	storage/util.go
	storage/util_test.go
```

This happens because the storage directory was replaced with a submodule.

See https://github.com/Masterminds/glide/issues/749

We can blame git, glide or azure-sdk-for-go, but I think the simplest solution that doesn't require new code to be written is here. That's why I'm hoping that you guys can simply rename the storage directory on master to something else. That way these conflicts won't exist and we can move on without having to wait for code changes elsewhere.

Meanwhile, we'll probably just fork this repo and remove the latest commits as a workaround :(

Edit: I believe the breaking change was introduced in https://github.com/Azure/azure-sdk-for-go/pull/569

**Comment by marstr** [comment]
Howdy, @vikstrous sorry you're running into trouble.

**Assuming you don't have any alterations to the SDK that you need to keep**, the _easiest_ way forward is to checkout a fresh copy of the SDK. For the benefit of others who have found this thread, I'll include instructions for folks using glide and otherwise.

## Glide
1. `cd <project directory>/vendor/github.com/Azure`
2. `rm -rf azure-sdk-for-go`
3. `cd ../../..`
4. `glide install`

## Go Get
1. `cd $GOPATH/src/github.com/Azure/`
2. `rm -rf azure-sdk-for-go`
3. `go get -u github.com/Azure/azure-sdk-for-go`

**Comment by vikstrous** [comment]
This is not sufficient. `glide update` works by cloning the repo first, running get submodule init/update, then checking out the version specified in the glide.yaml file. By the time it has cloned master, and initialized submodules it's too late and checking out an old version will fail unless the submodule directory is deleted. There is no workaround without code changes to glide from what I can tell.

On April 4, 2017 10:49:54 AM PDT, Martin Strobel <notifications@github.com> wrote:
>Howdy, @vikstrous sorry you're running into trouble.
>
>**Assuming you don't have any alterations to the SDK that you need to
>keep**, the _easiest_ way forward is to checkout a fresh copy of the
>SDK. For the benefit of others who have found this thread, I'll include
>instructions for folks using glide and otherwise.
>
>## Glide
>1. `cd <project directory>/vendor/github.com/Azure`
>2. `rm -rf azure-sdk-for-go`
>3. `cd ../../..`
>4. `glide install`
>
>## Go Get
>1. `cd $GOPATH/src/github.com/Azure/`
>2. `rm -rf azure-sdk-for-go`
>3. `go get -u github.com/Azure/azure-sdk-for-go`
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Azure/azure-sdk-for-go/issues/581#issuecomment-291579187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marstr** [comment]
Sorry @vikstrous, I'm having trouble repro'ing your issue. When I go to migrate our samples (e.g. [Azure-Samples/network-go-manage-network-security-group](https://github.com/Azure-Samples/network-go-manage-network-security-group)) to the latest version, I don't get a conflict. Mind sharing some details about the version of glide your using, maybe send me a link to the repository where you're running into trouble?

**Comment by rogpeppe** [comment]
We also have been running into problems from this issue. We use a different
dependency management system, but the issue is the same - git submodules
make it very hard to checkout different commits when the submodules change.

For example:

    git clone git@github.com:Azure/azure-sdk-for-go
    cd azure-sdk-for-go
    git submodule update --init --recursive              # "go get" does this.
    git checkout 902d95d9f311ae585ee98cfd18f418b467d60d5a

This fails with the "error: The following untracked working tree files would be overwritten by checkout:" problem, and has broken our continuous integration process.

Unfortunately no automatic dependency management system
can switch between pinned commits when there are submodules without
potentially destroying valuable information held in the .git directories
in the submodules.

Perhaps git subtree might be a better fit here?

**Comment by marstr** [comment]
I just updated my first comment. After clearing my glide cache I'm running into the same issue. Thanks for bringing this to my attention, @vikstrous and @rogpeppe.

**Comment by marstr** [comment]
Alright, my knee-jerk plan here is that we NEED to revert the addition of the submodule and replace it with the actual source files in order to unblock folks using older versions. We'll release that as version v9.1.0-beta.

The plan will still be to move storage into its own repository. But we'll have to do something else to support folks still using it through this repository.

**Comment by marstr** [comment]
Alright, this should be resolved for now. Can you confirm @vikstrous and/or @rogpeppe?

**Comment by vikstrous** [comment]
works for me!

**Comment by rogpeppe** [comment]
Works for me too. Thanks very much for the quick fix.
