### ISSUE TITLE
security center: Cannot delete a cosmos DB after enabling Advanced Threat Protection (API also has no update/create metholds)

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#6310]
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
- output of `go version`
```
18:05:45] kt@katbook:~/hashi/tf/azure/azurerm▸f/resource_adv_threat_protection-new$ find azurerm -type f -print | xargs grep "security\"$" | cut -d\" -f 2 | sort -u
github.com/Azure/azure-sdk-for-go/services/preview/security/mgmt/v1.0/security
[18:06:18] kt@katbook:~/hashi/tf/azure/azurerm▸f/resource_adv_threat_protection-new$ cat go.mod | egrep "(autorest|Azure)"
	github.com/Azure/azure-sdk-for-go v35.0.0+incompatible
	github.com/Azure/go-autorest/autorest v0.9.2
	github.com/Azure/go-autorest/autorest/date v0.2.0
[18:06:35] kt@katbook:~/hashi/tf/azure/azurerm▸f/resource_adv_threat_protection-new$ go version
go version go1.13.1 darwin/amd64
```

- What happened?
After enabling & then disabling ATP on a cosmos DB account i am unable to delete the cosmosDB. I get the following error:

```
 testing.go:630: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: Error issuing AzureRM delete request for CosmosDB Account 'acctest-191109182228101498': documentdb.DatabaseAccountsClient#Delete: Failure sending request: StatusCode=412 -- Original Error: Code="PreconditionFailed" Message="There is already an operation in progress which requires exlusive lock on this service acctest-191109182228101498. Please retry the operation after sometime.\r\nActivityId: a34dd703-7207-4705-8631-3b28e6d7a74f, Microsoft.Azure.Documents.Common/2.7.0"
```

Also there is a spelling error in the error message: `exlusive`

Also also there is no update or delete method for the ATP API, just create which seems.. different.

- What did you expect or want to happen?
the cosmos DB should have been able to be deleted. Also there should be at least an update method to change the ATP setting, possibly a delete that waits for such operations on the cosmos DB tok stop before returning.

- How can we reproduce it?
enabled ATP and then disable ATP on a cosmos DB account and try and delete the account.

- Anything we should know about your environment.

**Comment by Drewm3** [comment]
Removing the compute label because the compute label here is generally interpreted as Virtual Machines or Scale Sets.

**Comment by shurd** [comment]
Hi @katbyte thank you for opening this issue. From our logs, I can see that the operation to disable ATP on the account was running from 2:33:53 to 2:36:30. This operation has an exclusive lock on the database account. The request to delete the database account was sent at 2:34:55, while the account was locked for the other operation. Please wait for the disable ATP operation to complete before attempting to update or delete the database account. You can check the status of the operation from where you initiated the "remove ATP" or you can retry deletes on the database account until you do not see this preconditioned failed exception.

ATP is owned by the Microsoft.Security team, so requests to update this setting are sent to that resource proivder (which then internally sends us a notification that the setting should be updated). We do not have a method to update this setting on your account because we only allow notifications from the Microsoft.Security team to make changes.

**Comment by tombuildsstuff** [comment]
@shurd thanks for taking a look / getting back to us here.

Given the CosmosDB API is seeing the ATP Resource still kicking around, it sounds like the ATP API isn't actually disabling the ATP functionality before returning it as "Deleted". As such could we re-open this so that the Security/ATP Team could take a look here?

From our side @katbyte has mentioned there's no Update/Delete API in either [version 1.0 of the API/SDK](https://github.com/Azure/azure-sdk-for-go/blob/961851084b22af00900473bc704eb2f06e3a4e6c/services/preview/security/mgmt/v1.0/security/advancedthreatprotection.go) or [version 2.0 of the API/SDK](https://github.com/Azure/azure-sdk-for-go/blob/961851084b22af00900473bc704eb2f06e3a4e6c/services/preview/security/mgmt/v2.0/security/advancedthreatprotection.go)) - as such we're having to use the "Create" SDK call ([which is just a "PUT"](https://github.com/Azure/azure-sdk-for-go/blob/961851084b22af00900473bc704eb2f06e3a4e6c/services/preview/security/mgmt/v2.0/security/advancedthreatprotection.go#L93) so whilst this may be misnamed, the API call itself should be fine?). Our code is here for reference: https://github.com/terraform-providers/terraform-provider-azurerm/pull/4848/files#diff-046f984d7549198c6869293bbd1a15feR138-R147

On a separate note - why does the Security service use a completely different versioning strategy to the rest of this SDK (e.g. 1.0/2.0 vs 2019-01-01/2019-06-01)?

Thanks!

**Comment by AddySanto** [comment]
Looking for appropriate owner for this.

BTW regarding this: "On a separate note - why does the Security service use a completely different versioning strategy to the rest of this SDK (e.g. 1.0/2.0 vs 2019-01-01/2019-06-01)?" - answer is that the Security service provides security for several products and they aligned to the versioning convention of one of the other products.

**Comment by yoavfr** [comment]
@katbyte - This has been languishing here for quite some time and I apologize for this. 
Having said that I am wondering whether this is still relevant? Is it?

**Comment by katbyte** [comment]
afaik this has not been fixed so yes

**Comment by PinakiKundu** [comment]
@RickWinter still facing the same issue with the latest version of azurerm. Kindly share some good news.

**Comment by RickWinter** [comment]
The original bug was filled against a version of the SDK that is deprecated.  Are you seeing this problem with the latest compute package?

github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4

**Comment by tombuildsstuff** [comment]
@RickWinter 

> The original bug was filled against a version of the SDK that is deprecated. Are you seeing this problem with the latest compute package?
> github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4

Since this is an error coming back from the API (see the status code/error message below), the version of the SDK being used isn't going to make much difference there? It's worth noting this is an issue with the CosmosDB API and not Compute, however.

> StatusCode=412 -- Original Error: Code="PreconditionFailed" Message="There is already an operation in progress which requires exlusive lock on this service acctest-191109182228101498. Please retry the operation after sometime.\r\nActivityId: a34dd703-7207-4705-8631-3b28e6d7a74f, Microsoft.Azure.Documents.Common/2.7.0"

Since this is an API issue this issue would need to be fixed by the Service Team - as this issue [has been tagged with `Service Attention` back in December 2020](https://github.com/Azure/azure-sdk-for-go/issues/6310#event-4087647686), however this is still waiting for someone from the Service Team to take a look - as such, is there would you mind pinging the Service Team again?

Thanks!
