### ISSUE TITLE
Deployments' CreateOrUpdate's return does not match the response body

### ISSUE THREAD

**Issue by weinong** [Azure/azure-sdk-for-go#639]
`CreateOrUpdate` in https://github.com/Azure/azure-sdk-for-go/blob/master/arm/resources/resources/deployments.go currently returns `DeploymentExtended` channel.
However, upon inspecting the http response, it is not `DeploymentExtended` at all. So the returned `DeploymentExtended.Properties` is always nil.

The concern is that why do we return `DeploymentExtended` at all? It simply adds confusion to the user.

`DeploymentExtended` is only returned in Get call.

**Comment by marstr** [comment]
Howdy @weinong, sorry for the delayed response here, we've been away on a holiday weekend!

Since moving to the channel model, this is something that jumped out to me as bizarre as well. First and foremost, the reason that it is setup that way is because of the Swagger documents which can be found here: [Deployments Put Swagger Definition](https://github.com/Azure/azure-rest-api-specs/blob/559116780819474db8605387c4bc3de4a038533a/arm-resources/resources/2017-05-10/swagger/resources.json#L126) and here: [Deployments Extended Swagger Defintion](https://github.com/Azure/azure-rest-api-specs/blob/559116780819474db8605387c4bc3de4a038533a/arm-resources/resources/2017-05-10/swagger/resources.json#L2144). As a generator, we are trying to stay honest to what is declared in the Swagger so that our tool can hold value outside of just targeting Azure Services.

That said, this does feel misleading, and we need to take one or both of the following actions:
1. Investigate if the Swagger definitions can be rewritten or at least have an updated pattern in future API Versions.
2. Add more documentation to make clear how we believe these should work.

I hope this addresses your question!

**Comment by colemickens** [comment]
This was quite confusing to me as well. Is there an issue tracking this on the azure-rest-api-specs repo?

**Comment by marstr** [comment]
Not that I'm aware of. However, I'm trying to drive some conversations internally about this to understand what their reasoning is.

**Comment by marstr** [comment]
I'm going to close this out for now, but I'll be chasing down this issue internally.
