### ISSUE TITLE
Adding Accept-Language on down stream calls

### ISSUE THREAD

**Issue by JackQuincy** [Azure/azure-sdk-for-go#658]
I'm trying to use this sdk for  production service. I would love to be able to pass error messages from the sdk to the user in cases that in makes sense. But that is only possible if they are localized to the language requested in my accept language header. So I want to be able to do something similar how .Authorizer. I want to be able to either do a  client.CustomHeaderFunc = func(headers){ //add my headers} or client.AcceptLanguageValue = myServiceRequest.Headers.Get("Accept-Language").

I'd be willing to help write the code if someone could point me in the right direction.

**Comment by mcardosos** [comment]
Hello @JackQuincy !
What you can do is use the preparer, sender and responder for each operation and add the `Accept-Language` header after preparing the request. Lets say you want to create a resource group, the code would look like this:
```go
	resourceGroupParameters := resources.Group{
	// Location: &location,
	}

	req, err := groupClient.CreateOrUpdatePreparer(groupName, resourceGroupParameters)
	if err != nil {
		fmt.Println(err)
	}
	req.Header.Add("Accept-Language", "es-es")

	resp, err := groupClient.CreateOrUpdateSender(req)
	if err != nil {
		fmt.Println(err)
	}
	_, err = groupClient.CreateOrUpdateResponder(resp)
	if err != nil {
		fmt.Println(err)
	}
```
Because location parameter is not included (but it is a required parameter), this code fails. But because of the `Accept-Language` header, the error looks like this:
`autorest/azure: Service returned an error. Status=400 Code="LocationRequired" Message="Se necesita la propiedad de ubicación de esta definición."`

**Comment by JackQuincy** [comment]
Thanks, I think this should work.

**Comment by JackQuincy** [comment]
I wrote the code for this and there was alot of copy and pasting needed to do this. Am I doing it wrong in  https://github.com/Azure/acs-engine/issues/808

**Comment by mcardosos** [comment]
You are not doing it wrong, but I have to agree code looks cumbersome. I we were to  add this kind of functionality to the clients, I think the best place to add this is in [go-autorest](https://github.com/Azure/go-autorest). Thoughts @marstr  @jhendrixMSFT ?

**Comment by mcardosos** [comment]
Ok, yes, there is a better way to do this :)
``` go
import (
	"github.com/Azure/go-autorest/autorest"
)

func WithAcceptLanguageHeader(language string) autorest.PrepareDecorator {
	return autorest.WithHeader("Accept-Language", language)
}

func main() {
	groupClient.ManagementClient.Client.RequestInspector = WithAcceptLanguageHeader("es-es")
	resourceGroupParameters := resources.Group{
		Location: to.StringPtr("nonexisitinglocation"),
	}

	_, err := groupClient.CreateOrUpdate(groupName, resourceGroupParameters)
	if err != nil {
		fmt.Println(err)
	}
}
```
Again the error is in Spanish...
`resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" Message="La ubicación proporcionada, 'nonexisitinglocation', no está disponible para el grupo de recursos. La lista de las regiones disponibles es 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,so
uthcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth'.`

**Comment by JackQuincy** [comment]
Apparently I forgot to hit comment. So this is better but it is limited to a single prepare decorator as I can't nest prepare decorators. Is there a reason why not?

**Comment by mcardosos** [comment]
A PrepareDecorator can do more than just adding a single header if that is what you mean. Take a look at [this example](https://github.com/Azure/go-autorest/blob/3a30515cff8ca0504593132b55cd9e5aa2136f74/autorest/azure/azure.go#L100).

**Comment by JackQuincy** [comment]
that last example worked. It would of been easier if we had a function like 
`// Nest returns a PrepareDecorator that nests the prepare decorators together.`

`func Nest(pds ...PrepareDecorator) PrepareDecorator {
	return func(p Preparer) Preparer {
		for _, pd := range pds {
			p = pd(p)
		}
		return p
	}
}`

**Comment by marstr** [comment]
Howdy folks, sorry I haven't weighed in earlier, I know this issue is closed.

I wanted to point out quickly that part of why this hasn't come up before is that just all of the functions that take a PreparerDecorator already take a variadic number of them. The notable exception to this seems to be the autorest.Client model which has one PreparerDecorator. This seems odd to me, my gut tells me it should be a Preparer, but I'm willing to look the other way a bit.

One thing I will mention here (as well as on the PR that is open) is that if we do it, we should make sure to extend this across to ResponderDecorators as well.
