### ISSUE TITLE
Support creating SQL databases in resource groups other than the SQL Server

### ISSUE THREAD

**Issue by zsims** [Azure/azure-sdk-for-go#663]
The `DatabasesClient` supports creating databases via `CreateOrUpdate` however, it assumes the given resource group name is both the target resource group and the resource group where the server can be found.

As a result, it's not possible to create databases in different resource groups from the server.

**Comment by mcardosos** [comment]
Hello @zsims !
@marstr will take a look at this

**Comment by marstr** [comment]
Howdy @zsims, 

I'm afraid that this problem is larger than the scope of our repository. While I don't see any mention of this capability while reading through the documenation here: [Azure SQL Servers Overview](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-server-overview), it seems to be stated pretty clearly here: [Resource Manager - Cross Resource Group Deployment](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-cross-resource-group-deployment) that this scenario is one the ARM team is aware of in general.

I'm going to escalate this issue to the [Azure REST API Specs repository](https://github.com/Azure/azure-rest-api-specs) where any fix from the service team will be picked up by all AutoRest based Azure SDKs. Please note, this kind of fix will likely need to be in a new API Version of the service.

Thanks for logging this issue!

**Comment by marstr** [comment]
Closing this issue in favor of the newly created one above.

**Comment by zsims** [comment]
Thanks for the prompt follow up, much appreciated.
