### ISSUE TITLE
How to specify APIVersion when using ARM Generic Resource operations

### ISSUE THREAD

**Issue by dave-read** [Azure/azure-sdk-for-go#679]
In prior version of the SDK (v7.0.0-beta), the Management Client (azure-sdk-for-go/arm/resources/resources/client.go) included an APIVersion property that allowed use of Generic Resource operations like CreateOrUpdate with preview APIs (e.g. Azure PostgresSQL requires 2017-04-30-preview)
```
type ManagementClient struct {
	autorest.Client
	BaseURI        string
	APIVersion     string
	SubscriptionID string
}
```
When updating to the latest releases (v10.x.x-beta) that APIVersion property is no longer available and the API version appears to be fixed at 2016-09-01.  Was that change by design?  If so, is there any other way to specify an APIVersion when using the SDK with Generic Resource operations (e.g. GroupClient CreateOrUpdate)?

**Comment by marstr** [comment]
Howdy @dave-read,

As you suspected, this change was done by design. Here are a few threads that explain why this happened, and which problems we're trying to solve:

- Azure/azure-sdk-for-go#517
- Azure/azure-sdk-for-go#631
- Azure/autorest#2080

Also, checkout my experimental branch, were I've started regenerating code to conform to a pattern which supports all API Versions here:
[Azure/azure-sdk-for-go experimental/allAPIVersions](https://github.com/Azure/azure-sdk-for-go/tree/experimental/allAPIVersions)

**Comment by marstr** [comment]
Feel free to ask for this to be re-opened if you don't find the answers you're looking for in those threads!
