### ISSUE TITLE
AuthenticationFailed error in PutBlockWithLength

### ISSUE THREAD

**Issue by cswarth** [Azure/azure-sdk-for-go#683]
storage.PutBlockWithLength() returns AuthenticationFailed error when passed an [io.LimitedReader](https://golang.org/pkg/io/#LimitedReader), but works when passed an [io.Reader](https://golang.org/pkg/io/#Reader).
```
--- FAIL: TestBlobStorage (0.09s)
	azure_test.go:30: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
		RequestId:d54be8b8-0001-00b9-15fc-f8fc17000000
		Time:2017-07-09T21:45:36.8668954Z, RequestInitiated=Sun, 09 Jul 2017 21:45:36 GMT, RequestId=d54be8b8-0001-00b9-15fc-f8fc17000000, API Version=, QueryParameterName=, QueryParameterValue=
```
The substitution of io.LimitedReader for io.Reader should be transparent to PutBlockWithLength().

Substitute your own account name, access key, and pre-made container name in the follow code and note the failure. Run with `go test`.

```
package azure

import (
	"io"
	"strings"
	"testing"

	"github.com/Azure/azure-sdk-for-go/storage"
)

func TestBlobStorage(t *testing.T) {

	accountName := "account_name"
	accountKey := "account_key"
	container := "preconstructed_container"

	azsClient, err := storage.NewBasicClient(accountName, accountKey)
	if err != nil {
		t.Fatal(err)
	}

	blobsvc := azsClient.GetBlobService()
	contref := blobsvc.GetContainerReference(container)
	b := contref.GetBlobReference("some/key")

	// this succeeds.
	//lr := strings.NewReader("abcde")

	// this fails with AuthenticationFailed
	lr := io.LimitReader(strings.NewReader("abcde"), 5)

	err = b.PutBlockWithLength("0000", 5, lr, nil)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by majedev** [comment]
Having exactly the same issue. Just posting a note quickly as to why I think it happens: the `Content-Length` header might not be set correctly for any io.Reader implementation except `bytes.Buffer`, `bytes.Reader` and `strings.Reader` because the storage http client uses `http.NewRequest(verb, url, body)` to create requests. The latter (in go 1.8.3) detects and sets the request's `ContentLength` property correctly [only for the mentioned Reader types](https://github.com/golang/go/blob/352996a381701cfa0c16e8de29cbde8f3922182f/src/net/http/request.go#L788-L817). It appears that modifying request's `Content-Length` header does not override the `ContentLength` value in the generated request, which generates an invalid authorization header, hence the 403.

Will come back later with more details, maybe post a PR.

**Comment by jhendrixMSFT** [comment]
Resolved in https://github.com/Azure/azure-sdk-for-go/pull/704.
