### ISSUE TITLE
MSI support requirements

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-go#717]

**Comment by marstr** [comment]
The scope of this work-item (at least for Sprint-105) is coming to understand the expectations around MSI support for the Go SDK.

For those unfamiliar, in this context MSI stands for "Managed Service Identity" and speaks to the ability to add support for scoping a Service Principal to a particular resource instead of forcing identity to a particular application or individual.

My initial expectation is that there will be categories of work involving support of new Swaggers, and a few tweaks to our [go-autorest ADAL](https://github.com/Azure/go-autorest/tree/0545944f0d7822e1c75b036402f6ca4a1ce7e570/autorest/adal) package to support the new functionality.

**Comment by marstr** [comment]
This work is done :) @mcardosos did a bunch of the work!
