### ISSUE TITLE
Cosmos-db delete function 404 Not Found

### ISSUE THREAD

**Issue by julienstroheker** [Azure/azure-sdk-for-go#759]
When we call the delete function for the cosmosdb provider we have a 404 - Not Found response

## Simple steps to reproduce : 

- Account created via the portal with the name `jujudb123` in the resource group `MyRG`

```
package main

import (
	"fmt"
	"log"

	"github.com/Azure/go-autorest/autorest"

	"github.com/Azure/azure-sdk-for-go/arm/cosmos-db"
	"github.com/Azure/azure-sdk-for-go/arm/examples/helpers"
	"github.com/Azure/go-autorest/autorest/azure"
)

func main() {

	resourceGroup := " MyRG"
	name := "jujudb123"

	client := "xxxxxxxxxxxxxx"
	secret := "xxxxxxxxxxxxxx"
	sub := "xxxxxxxxxxxxxx"
	tenant := "xxxxxxxxxxxxxx"

	c := map[string]string{
		"AZURE_CLIENT_ID":       client,
		"AZURE_CLIENT_SECRET":   secret,
		"AZURE_SUBSCRIPTION_ID": sub,
		"AZURE_TENANT_ID":       tenant,
	}

	spt, err := helpers.NewServicePrincipalTokenFromCredentials(c, azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		log.Fatalf("Error: %v", err)
		return
	}

	mydbclient := cosmosdb.NewDatabaseAccountsClientWithBaseURI("https://management.azure.com/", sub)
	mydbclient.Authorizer = autorest.NewBearerAuthorizer(spt)

	cancelCh := make(chan struct{})
	deleteResp, errChan := mydbclient.Delete(resourceGroup, name, cancelCh)
	if err := <-errChan; err != nil {
		fmt.Errorf("error deleting cosmosdb server: %s", err)
	}
	resp := <-deleteResp
	fmt.Printf("%s", resp.Response.Status)

}
```
## Output
After few minutes we have the following response : 

```
resp.Response.Status :  "404 Not Found"
resp.Response.StatusCode :  "404"
```

The account is well deleted though, but I think the `404 Not found` is not the response that we should have right?

Thanks

**Comment by marstr** [comment]
Thanks for raising this issue, @julienstroheker. Digging into the Swagger for Cosmos DB management, I see here that the server does expect to send a Success response as acknowledgment: [cosmos-db.json#L167 @ f4729014](https://github.com/Azure/azure-rest-api-specs/blob/f4729014caa04727c86f37bad1d1b36305942297/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/2015-04-08/cosmos-db.json#L167)

Seeing that it is a Long Running Operation, which will occur asynchronously, our current generator wraps the call with a `GET` request, which ends up failing because the resource did actually get deleted. This demonstrates a little glitch in the code we generate. For now, I don't want to commit to the breaking change that it would take to fix this. However, @jhendrixMSFT and I have been pow-wowing about what we could to to add intermediate responses back into the mix. Once we add that, this issue should be solved. For the moment there is no open issue tracking that work, but I'll bring it up today during our sprint planning meeting.
