### ISSUE TITLE
API output difference between virtualmachineclient ListAll and Get Method

### ISSUE THREAD

**Issue by kirankumarbv** [Azure/azure-sdk-for-go#786]
Hi,

I use both ListAll and Get methods in my application. However the ID value of vm result returned by ListAll has **resource group capitalized** and ID value obtained from Get method does not do that, which is causing my application to break. Is there any particular reason this happens or is it a bug?

Below is the code snippet for ListAll 

resp, err = vmClient.ListAll()
for _, vm := range *resp.Value {
       log.Println(*vm.ID) 
}

**Comment by marstr** [comment]
Howdy @kirankumarbv,

Sorry this has gone unaddressed for a couple of weeks! I'm going to have to dig a little to verify that we aren't doing any case munging. If we are, I'll try to figure out why and if we still have to. If we aren't, I'll forward this issue on to the service team.

-Martin

**Comment by marstr** [comment]
Howdy Again,

I just spent some time perusing through [code generated for `ListAll` operations](https://github.com/Azure/azure-sdk-for-go/blob/86e3d518ea7e13072823dcf4aeda064314461257/services/dns/mgmt/2015-05-04-preview/dns/recordsets.go#L412). With a quick glance, I didn't notice anything that would be munging the case. Because of that, I'm going to chalk this one to weird behavior from the service. I'll try to start a thread internally to drive a conversation. Sorry there isn't a more useful answer!

-Martin
