### ISSUE TITLE
General Availability of the Azure-Go-SDK

### ISSUE THREAD

**Issue by hxeml** [Azure/azure-sdk-for-go#804]
What is the current plan for moving the Azure Go SDK out of preview mode and making it generally available? I wasn't able to find a roadmap detailing this information.

**Comment by marstr** [comment]
@salameer is going to have my head for this one!

To answer your question, we're a little behind schedule, but expect to release a GA version in the next couple of months At the moment, the biggest blockers to releasing are
- Supporting Multiple API Versions, progress on this front can be seen [here](https://github.com/Azure/azure-sdk-for-go/tree/experimental/allAPIVersions) and [here](https://github.com/Azure/azure-sdk-for-go/pull/793).
- Rewriting Long Running Operation support, so that we don't have a confusing mess of channels returned to people. (Live and learn, sorry folks!)
- Adding context.Context to each of our method headers. The issue that will track progress on that front is #797.

In general though, you are correct we haven't done a great job with being organized about sharing our roadmap. It's something @salameer has been wanting us to improve for a good long while. I'll add a roadmap to our README here shortly for the time being, until we can figure out the best way to share our progress and vision long term.

**Comment by hxeml** [comment]
Thanks. I'll keep an eye on the README for your changes.

**Comment by marstr** [comment]
I've started a Wiki for our project, and published a detailed Road Map of the most pressing issues that we plan to fix before hitting GA. You can see that page here:  https://github.com/Azure/azure-sdk-for-go/wiki/Road-Map.

**Comment by carlsoane** [comment]
Sorry to write a comment on a closed issue, but I went to  https://github.com/Azure/azure-sdk-for-go/wiki/Road-Map link and wasn't able to find any more information on the GA status of the SDK. Is there an update on when the SDK will be GA? Would it be correct to say that it is currently in Beta and a GA data has not been set?

Thanks,

**Comment by marstr** [comment]
To close the loop, @joshgav has answered this question in #955.
