### ISSUE TITLE
Add support for the publicNetworkAccess property on sql server

### ISSUE THREAD

**Issue by gpduck** [Azure/azure-sdk-for-go#8161]
### Service Package Request

Please add support for the properties.publicNetworkAccess property of the sql/servers type.

https://docs.microsoft.com/en-us/rest/api/sql/servers/createorupdate#serverpublicnetworkaccess

I'm looking to get this added to terraform via https://github.com/terraform-providers/terraform-provider-azurerm/issues/6374

**Comment by ArcturusZhang** [comment]
Hi @gpduck thanks for this issue. But this property has already been supported by go SDK [here](https://github.com/Azure/azure-sdk-for-go/blob/68d483faf640e457e33779443ebc5108b900d3ff/services/preview/sql/mgmt/v3.0/sql/models.go#L18363) in a composite package.
I recommend to use this composite package of sql in terraform, since the separate api-versions of this service only supports a subset of all things in sql, but a composite package combined them all.

**Comment by ArcturusZhang** [comment]
And based on this I will close this issue since the requested package has already been released
