### ISSUE TITLE
SendGrid accounts support

### ISSUE THREAD

**Issue by jaygridley** [Azure/azure-sdk-for-go#8376]
### Service Package Request

We are in need of support of SendGrid account API https://schema.management.azure.com/schemas/2015-01-01/Sendgrid.Email.json#/resourceDefinitions/accounts in the SDK.

This could be later on leveraged in Terraform provider, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/6510

**Comment by ArcturusZhang** [comment]
Hi @jaygridley thanks for this issue.
A little awkward that I did not find the corresponding swagger in [this repo](https://github.com/Azure/azure-rest-api-specs), since this SDK (the `services` directory) is all auto-generated from their corresponding swagger. For something that does not have a swagger, unfortunately it cannot have its SDK supported by this repo.... Sorry about this...

**Comment by jaygridley** [comment]
@ArcturusZhang So should I create an issue in https://github.com/Azure/azure-rest-api-specs to add that? The API exists and I do not know why it is not documented.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang So should I create an issue in https://github.com/Azure/azure-rest-api-specs to add that? The API exists and I do not know why it is not documented.

Sure thanks so much.

**Comment by ieelleme** [comment]
We would also like to be able to deploy Sendgrid using Terraform. Are there any plans to make this possible?

**Comment by JoseFMP** [comment]
Seriously, not supported in terraform? Really annoying now every time we deploy our infrastructure we need to quasi manually create the SendGrid resources

**Comment by frecke** [comment]
+1 on this. I would also like to be able to deploy Sendgrid using Terraform.

**Comment by TheYoxy** [comment]
Hi,

Any status update for this issue ?

**Comment by lirenhe** [comment]
Close it as the API is not documented is Swagger.
