### ISSUE TITLE
Add support for Azure Load Balancer Standard and associated components

### ISSUE THREAD

**Issue by justaugustus** [Azure/azure-sdk-for-go#871]
Hey peeps, long-time listener, first-time caller.
Do you have a timeline for adding support for the following components:
* Azure LB Standard: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-standard-overview
* Availability Zones: https://docs.microsoft.com/en-us/azure/availability-zones/az-overview
* High Availability Ports: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ha-ports-overview

Is this on the roadmap for `azure-sdk-for-go` (if so, when?) or are you actively looking for community contributions?

We (CoreOS) are looking to integrate this functionality into https://github.com/coreos/tectonic-installer and get the jump on testing while these features are still in Preview.

Thanks in advance for any information you can provide.
It's greatly appreciated! :)

x-refs:
* coreos/tectonic-installer#2443
* terraform-providers/terraform-provider-azurerm#579

cc: @robszumski / @metral

**Comment by marstr** [comment]
Howdy @justaugustus, thanks for calling in!

The way our project is structured, a bulk of our code is auto-generated from OpenAPI Spec Markup that can be found here: https://github.com/Azure/azure-rest-api-specs. As one of our closest partners, the Networking team tends to do a good job of updating their service definitions fairly expediently. I'll have to do a little research to get back to you on exactly when we expect those swaggers to become available, and when we believe they'll get folded in to our SDK. (It should be relatively soon though!)

I'll close this issue for now, because there isn't any new actionable work, but feel free to continue the conversation here and @mention me if you'd like updates.

**Comment by justaugustus** [comment]
Hey @marstr, just wanted to ping you and see if there was an update w.r.t. pulling in support for LB Standard, AZs, and HA ports.
