### ISSUE TITLE
[Stream Analytics] Error unmarshalling Output structure

### ISSUE THREAD

**Issue by thsutton** [Azure/azure-sdk-for-go#898]
I'm using the Go SDK (v11.1.0-beta sha 80f6cbcb1d6295ebb8fbeb5afab826a94aa67d11) to manage Stream Analytics Jobs but have run into a problem with the where the SDK can marshal an `Output` struct to JSON (directly or within a `StreamingJob` struct) but cannot unmarshal it (generally returning an `Output` struct with all fields set to `nil`).

Implementing `func (o *Output) UnmarshalJSON(body []byte) error` following the pattern of `func (i *Input) UnmarshalJSON(body []byte) error` seems to resolve the issue.

**Comment by thsutton** [comment]
Maybe this is related to https://github.com/Azure/autorest.go/pull/66?

**Comment by vladbarosan** [comment]
Hi @thsutton from what I can see, the issue you referenced is not directly related to what you are encountering. Can you provide a gist with repro steps ?

**Comment by thsutton** [comment]
@vladbarosan https://gist.github.com/thsutton/8ea9034e3fa1d379fa60c513bf116bf6

It includes a test that `marshal(output) == marshal(unmarshal(marshal(output)))` (which I think is an uncontroversial property to expect of serialisation code) for an output datasource, an OutputProperties containing that datasource, and an Output containing that OutputProperties. The test fails unless I apply the included patch.

I suspected it might be related to the PR linked above because the missing code is generated by [`ModelTemplate.cshtml` in autorest.go](https://github.com/Azure/autorest.go/blob/master/src/Templates/ModelTemplate.cshtml#L180) which is guarded by [`Model.HasPolymorphicFields`](https://github.com/Azure/autorest.go/pull/66/files#diff-22b44f7a76de7319033b552671c11271L129) which was modified in that PR.

**Comment by vladbarosan** [comment]
Thanks for the repro @thsutton . Figured out the issue. The problem is that `Output` has an embedded type and that type has a custom unmarshaller. Since `Output` doesn't the embedded type's method gets called with the body of the whole `Output` and hence the unmarshaling fails. What you suggested ( having a custom unmarshaller ) in this cases when we have embedded types should work. 

Will look to put a fix today and try to make it in release in this next major release. Thanks for helping in catching this!
