### ISSUE TITLE
[v12.0.0] Inconsistent return types for same operation across clients

### ISSUE THREAD

**Issue by radu-matei** [Azure/azure-sdk-for-go#926]
The `Delete` method for `VaultsClient` returns an `autorest.Response`, while most of the others return either the value of the deleted object (as is the case for container groups, or a future, as is the case for virtual machines).

The question is: why do some clients (KeyVault, SQL databases and storage accounts) return an `autorest.Response`?
Below is [the function signature for Delete, as found here](https://github.com/Azure/azure-sdk-for-go/blob/990842d1126ef6e294152c5f6f4e3f804a3cfd6d/services/keyvault/mgmt/2016-10-01/keyvault/vaults.go#L132)

```go
func (client VaultsClient) Delete(ctx context.Context, resourceGroupName string, vaultName string) (result autorest.Response, err error)
```

In comparison, here is [the signature for Delete on ContainerGroup, as found here](https://github.com/Azure/azure-sdk-for-go/blob/990842d1126ef6e294152c5f6f4e3f804a3cfd6d/services/containerinstance/mgmt/2017-08-01-preview/containerinstance/containergroups.go#L130)

```go
func (client ContainerGroupsClient) Delete(ctx context.Context, resourceGroupName string, containerGroupName string) (result ContainerGroup, err error)
```

And here is the signature for VMs, which returns a future:

```go
func (client VirtualMachinesClient) Delete(ctx context.Context, resourceGroupName string, VMName string) (result VirtualMachinesDeleteFuture, err error) {

```

Having three different responses for the Delete operation on different clients is rather counter-intuitive...

Thanks,
Radu M

**Comment by radu-matei** [comment]
Ok, apparently I stumbled across the same thing a while back (see https://github.com/Azure/azure-sdk-for-go/issues/633), but the issue is only getting worse with now three different types os responses for the same type of operation.

**Comment by vladbarosan** [comment]
Hi @radu-matei thanks for highlighting this again. As it was previously mentioned by @marstr this comes from how the specs for the services are designed. We can look for some improvements though ( e.g. instead of returning an `autorest.Response` we can add some extra logic and return `true` and `false`).  

@marstr, @jhendrixMSFT  thoughts on how we can further improve this ?

**Comment by radu-matei** [comment]
Hi, @vladbarosan, thanks for the reply!
Returning a boolean still doesn't address the fact that there are two different return types for short running delete tasks. 


Looking at the latest REST API specs for the three services mentioned earlier for the `Delete` method ([KeyVault](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L102), [Container Instance](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/preview/2017-10-01-preview/containerInstance.json#L208) and [Compute](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L118)), they have, obviously, HTTP response codes.

How are handled differently by [go-autorest](https://github.com/Azure/go-autorest) the specs for KeyVault and Container Instance (both short running operations, I assume?)

And if they are handled differently, is there an additional step we can do before returning (I'm talking in the case of returning `autorest.Response`) so that we are consistent in returning?

Two ideas that come in mind are:
- either have all short running `Delete` (and all that behave the same) return an `autorest.Response` or boolean
- for the ones that return an `autorest.Response`, before actually deleting, make a request to get the resource, have the `Delete` request and if successful return the result of the get operation.

In any case, consistency should be important.

Thanks,
Radu M

**Comment by jhendrixMSFT** [comment]
For generated code (vaults and virtual machines in your example), the methods will return whatever is specified in the swagger; this could be an autorest.Response, a user-defined type, or a future type for long-running operations that wraps the underlying response.  For ARM I believe there are already well-defined rules about what these operations can return and should be the mechanism used to enforce uniformity.
Note that the /storage package is completely hand-written, based on the current C# implementation which is why it's different from the AutoRest generated code.  We are (slowly) moving to use AutoRest generated code for storage and have this for blobs, see the new [blob storage repo](https://github.com/Azure/azure-storage-blob-go) for what that looks like.

**Comment by jhendrixMSFT** [comment]
As we cannot have the generator coalesce disparate return types into a simple boolean I'm closing this issue.
