### ISSUE TITLE
go-get problem: no buildable Go source files in the repo

### ISSUE THREAD

**Issue by allomov** [Azure/azure-sdk-for-go#93]
I try to run `go get github.com/MSOpenTech/azure-sdk-for-go` as it is written in README file, but I get following error message:
```
→ go get github.com/MSOpenTech/azure-sdk-for-go
can't load package: package github.com/MSOpenTech/azure-sdk-for-go: no buildable Go source files in /Users/allomov/work/altoros/microbosh/go/src/github.com/MSOpenTech/azure-sdk-for-go
```

**Comment by ahmetalpbalkan** [comment]
You're right this must be fixed. Meanwhile, try go get -d.

**Comment by allomov** [comment]
Thank you for your answer, I was able to fix it by fetching `v1.2` tag.

**Comment by paulmey** [comment]
Alternatively, `go get github.com/MSOpenTech/azure-sdk-for-go/...` will get you all packages and their dependencies under that path...

**Comment by michaelsync** [comment]
Has it been fixed? 

I've tried the following commands and didn't work. 

```
go get github.com/Azure/azure-sdk-for-go
go get -u github.com/Azure/azure-sdk-for-go
go get -d github.com/Azure/azure-sdk-for-go
go get github.com/Azure/azure-sdk-for-go/...
```

**Comment by marstr** [comment]
Howdy @michaelsync, to avoid getting the error messages you can target the individual packages that you need. (i.e github.com/Azure/azure-sdk-for-go/arm/compute)

The error message about having no buildable Go files is expected behavior of the `go get` tool when targeting a whole repository instead of the particular package/packages that you need.
