### ISSUE TITLE
Support disk attach/detach to VMSS instances

### ISSUE THREAD

**Issue by feiskyer** [Azure/azure-sdk-for-go#944]
[VM Scale Sets attach-detach disk](https://github.com/Azure/vm-scale-sets/tree/master/preview/disk) has been in preview for while. When will it be included in Go SDK?

**Comment by joshgav** [comment]
Hi @feiskyer - I believe we don't have a method in the SDK which handles [the algorithm](https://github.com/Azure/vm-scale-sets/tree/master/preview/disk#attach-detach-rest-api-description) described in the doc you referenced. You'd have to implement that yourself at the moment by getting the VM, updating its properties, then putting it back. Something like this:

```go
vmssVMs := compute.NewVirtualMachineScaleSetVMsClient(...)
vm, _ := vmssVMs.Get(ctx, groupName, vmssName, vmID)
vm.VirtualMachineScaleSetVMProperties.StorageProfile.DataDisks[0].CreateOption = compute.DiskCreateOptionTypesAttach
// ... more modification of properties
// not currently available in SDK
// vmssVMs.Put(...)
```

Unfortunately, we don't yet have a method which corresponds to the PUT operation described in [that doc](https://github.com/Azure/vm-scale-sets/tree/master/preview/disk), which is because it's not yet described in [the API spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json).

@gbowerman can you help us update the spec? Thanks!

**Comment by feiskyer** [comment]
@joshgav @joshgav Thanks. Do you know when will PUT be supported?

**Comment by brendandburns** [comment]
@joshgav does this mean that it's not in the compute swagger spec?

**Comment by joshgav** [comment]
@brendandburns yes AFAI can tell. I believe it would be represented by an additional `put` operation in this section: https://github.com/Azure/azure-rest-api-specs/blob/9c8629c40c9a103b1a67e5d3dc99306b7fe036ea/specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json#L3085 per the [list of fields](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-4) in the spec.

**Comment by feiskyer** [comment]
@joshgav Yep, a PR (https://github.com/Azure/azure-rest-api-specs/pull/2180) is under reviewing for it.

**Comment by joshgav** [comment]
thanks @feiskyer! we'll make sure that's in our next point release (cc @Azure/go-admins)

**Comment by feiskyer** [comment]
Update: https://github.com/Azure/azure-rest-api-specs/pull/2180 has been merged.

**Comment by feiskyer** [comment]
@joshgav May I ask when will be the next release out?

**Comment by djsly** [comment]
@joshgav any chance an ETA for the next release could be provided? We are waiting the VMSS support in k8s and the dead line is approaching. 

From what I can get here, @feiskyer  seems to have all he needs to complete the missing piece, an official azure-sdk-fo-go release is what's left to get the ball rolling again.

Thanks!

CC: @brendandburns

**Comment by joshgav** [comment]
@jhendrixMSFT is looking into this, we hope to get it in the next point release.

**Comment by jhendrixMSFT** [comment]
This is now available in https://github.com/Azure/azure-sdk-for-go/releases/tag/v12.4.0-beta.

**Comment by feiskyer** [comment]
@jhendrixMSFT awesome thanks
