### ISSUE TITLE
Include types and helpers for Event Grid events

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-sdk-for-go#974]
Our [specs](https://github.com/Azure/azure-rest-api-specs) include definitions of events which Event Grid will send to HTTP listeners (i.e. [webhooks](https://en.wikipedia.org/wiki/Webhook)), such as 

* https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.EventHub/stable/2018-01-01/EventHub.json
* https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json

We would like to create a package with types for these events and helpers for deserializing them so that users can easily handle them in HTTP listeners.

**Comment by marstr** [comment]
I'm digging into this now that I'm back from vacation.

For the examples you give, I think we already have the types necessary to unmarshal easily: 

For:
> - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.EventHub/stable/2018-01-01/EventHub.json

We have:
https://github.com/Azure/azure-sdk-for-go/blob/56332fec5b308fbb6615fa1af6117394cdba186d/services/eventgrid/2018-01-01/eventgrid/models.go#L225

For:
> - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json

We have:
https://github.com/Azure/azure-sdk-for-go/blob/56332fec5b308fbb6615fa1af6117394cdba186d/services/eventgrid/2018-01-01/eventgrid/models.go#L440

The only remaining portion then is the helpers.

Today, using only the standard library, our scenario could look something like this:

``` Go
package exampleA

import (
    "encoding/json"
    "fmt"
    "io"
    "io/ioutil"
    "net/http"

    "github.com/Azure/azure-sdk-for-go/services/eventgrid/2018-01-01/eventgrid"
)

func main() {
    http.Handle("/myPath", myHandler)
    log.Fatal(http.ListenAndServce(":8080", nil))
}

func myHandler(resp http.ResponseWriter, req *http.Request) {
    var payload eventgrid.StorageBlobCreatedEventData

    bodyContents, err := ioutil.ReadAll(io.LimitReader(req.Body(), 5 * 1024 * 1024))
    if err != nil {
         resp.WriteHeader(http.StatusBadRequest)
         fmt.Fprint(resp, err.Error())
         return
    }

    json.Unmarshal(bodyContents, &payload)

    // do whatever I need to with payload

    resp.WriteHeader(http.StatusOK)
}
```

As far as I can tell, the best place for improvement above, would be to create a delegate type like this:
``` Go
type StorageBlobCreatedEventDataHandler func(resp http.ResponseWriter, req *http.Request, event eventgrid.StorageBlobCreatedEventData)
```

But, this is only valuable if people are using the stdlib, instead of something like [labstack/echo](https://github.com/labstack/echo). Not to mention, the work to either write a generation stage, or manually maintain those types only really buys the end user a few lines above. All in all, I'm not convinced there's any work to do here.

For now, I'm going to close-out this issue. However, let me know if I've completely missed the point! I'd be happy to re-open.

**Comment by marstr** [comment]
After chatting with @devigned offline this afternoon, I stand-by the position of closing this issue. However, he brought up some pretty interesting points about moving beyond adding some improved helper packages to the existing Azure SDK for Go. 

The main thing we talked about, was that while EventGrid uses HTTP, creating a service that's wired-up takes a fair amount of boiler plate, regardless of the web framework you're using. As a completely separate thing to our existing autorest products, we could create a code generator that builds out boiler-plate Go programs ready to accept specific events. The web framework to use could be parameterized.
