### ISSUE TITLE
Unexpected Authorization header error

### ISSUE THREAD

**Issue by meirf** [Azure/azure-sdk-for-go#980]
My code does `PutBlock` followed by `PutBlockList`.

My http request for `PutBlockList` is:
```
PUT /my-folder/mypath/5317?comp=blocklist HTTP/1.1
Host: myaccount.blob.core.cloudapi.de
User-Agent: Go/go1.9.2 (amd64-linux) azure-storage-go/v12.2.0-beta api-version/2016-05-31 blob
Content-Length: 96
Authorization: SharedKey myaccount:<22 letters and numbers>/<12 letters and numbers>/<7 letters and numbers>=
x-ms-blob-content-type: text/plain; charset=utf-8
x-ms-date: Mon, 22 Jan 2018 22:02:56 GMT
x-ms-meta-x_amz_website_redirect_location: /foo/bar/-7\u00a0-
x-ms-version: 2016-05-31
Accept-Encoding: gzip
```
(I've replaced shared key values with the count of letters and number since I wasn't sure if those need to be private.)

The error is:

> StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**Am I correct in thinking this is not an auth issue but rather because** `x-ms-meta-x_amz_website_redirect_location: /foo/bar/-7\u00a0-` **has unicode**?

**Comment by jhendrixMSFT** [comment]
In my reading of [RFC 822](https://tools.ietf.org/html/rfc822#section-3.1) I don't believe that Unicode characters are allowed in header values which is ultimately the root cause.  However, all headers in a request are used when calculating the [string-to-sign](https://docs.microsoft.com/en-us/rest/api/storageservices/authentication-for-the-azure-storage-services), so I suspect that the signature mismatches causing the authentication failure.
