### ISSUE TITLE
ActiveDirectoryResourceId is missing in the environment configs

### ISSUE THREAD

**Issue by seyadava** [Azure/azure-sdk-for-go#989]
Looks like Go SDK uses ServiceManagementEndpoint parameter to refer to token audience. Other SDKs (Ruby/CLI/Python) call this parameter as ActiveDirectoryResourceId. Should we stick to the same name across different SDKs?

**Comment by vladbarosan** [comment]
Hi @seyadava a couple of things: 
1. Changing this would be a big breaking change.
2. this endpoint should be use mostly for managing classic ASM resources ( cloud services ). Otherwise for ARM resources the endpoint would be `ResourceManagerEndpoint`.
3. The change to the name `ActiveDidrectoryResourceId` would be much more misleading than the current `ServiceManagementEndpoint`.
4. .NET is caliing it [ManagementEndpoint](https://github.com/Azure/azure-libraries-for-net/blob/92d655ef918b2b31b59012f4fce7d2c87e33e396/src/ResourceManagement/ResourceManager/AzureEnvironment.cs#L17) so it doesn't seem to be a consistent name over SDK's ( and if it was I would oppose `ActiveDidrectoryResourceId` for the reason mentioned above )

If this is not blocking anything, I would go ahead and close this issue.

**Comment by seyadava** [comment]
+Bala

**Comment by vladbarosan** [comment]
@seyadava not sure what you mean by pasting that email here

**Comment by joshgav** [comment]
@seyadava @vladbarosan  we agreed offline that we wouldn't remove the `ServiceManagementEndpoint` field but could still consider adding an `ActiveDirectoryResourceID` field.

Still, IMHO ActiveDirectoryResourceID is a generic name for a scope/resource (token audience) and @seyadava a more specific name should be used in other SDKs rather than adding a generic name here.

**Comment by jhendrixMSFT** [comment]
Closing as we aren't renaming this.
